
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ehRadio entity (relies on MQTT)
media_player:
  - platform: ehradio
    name: My ehRadio
    root_topic: ehradio/myradio/
