site_name: ehRadio
site_description: ESP32 Radio (yoRadio fork)
site_url: https://trip5.github.io/ehRadio/
repo_url: https://github.com/trip5/ehRadio
repo_name: trip5/ehRadio

theme:
  name: material
  favicon: images/icon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - toc.follow
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: trip5
      repo: ehRadio
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Readme: index.md
  - Hardware: Hardware.md
  - Audio/Power Isolation: Isolation.md
  - Controls: Controls.md
  - Commands: Commands.md
  - Trip 5's Notebook: notebooks/notebook.md
  - Old Readme: README.old.md
  - ёRadio Images: Images.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trip5