[platformio]
src_dir = ./src
data_dir = ./data

; -----------------------------------------------------------------------
; Trip5's Radios
; -----------------------------------------------------------------------
; patch_pio_ini_files can automatically patch this file

[ehradio]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
build_flags =
	-DCORE_DEBUG_LEVEL=0 ; Set to 0 for no debug; saves memory / 5 for full debug (> 0 adds 1s delay after cold boot to ensure serial logs fully visible)
  ;-DCONFIG_HEAP_POISONING_COMPREHENSIVE=1
;monitor_filters = esp32_exception_decoder
lib_deps =
  ; These libraries are not optional (version numbers here should work but you can try newer/older versions)
  bblanchon/ArduinoJson@^7.4.3
  adafruit/Adafruit GFX Library@^1.12.6
  adafruit/Adafruit BusIO@^1.17.4
  ESP32Async/ESPAsyncWebServer@^3.11.2
  ESP32Async/AsyncTCP@^3.4.10
  marvinroger/AsyncMqttClient@^0.9.0
  trip5/ESPFileUpdater@^1.4.2
  trip5/ehDP@^1.0.0
  jnthas/Improv WiFi Library@^0.0.4
build_src_filter =
  -<*> ; exclude all files by default
  +<../myoptions.h>
  +<main.cpp>
  +<core/*>
  +<displays/*>
  +<locale/*>
  ; additional local libraries can be included in each environment as so:
  ;+<libraries/ES8311_Audio/*> ; for ES8311 Audio
  ;+<libraries/LiquidCrystalI2C/*> ; for LC1602 Display
; These scripts package do pre- and post-steps to make sure SPIFFS gets .gz files for www and an edited font for Wi-Fi signal bars
extra_scripts = pre:builds/platformio_pre_gzip_www.py, post:builds/platformio_post_gzip_www.py

; -----------------------------------------------------------------------
; Optional External Libraries (here to simplify version number updating)
; Add them under lib_deps as: ${library.onebutton}
; -----------------------------------------------------------------------
[library]
onebutton          = mathertel/OneButton@^2.6.2
rotaryencoder      = igorantolic/Ai Esp32 Rotary Encoder@^1.7
irremote           = crankyoldgit/IRremoteESP8266@^2.9.0
neopixel           = adafruit/Adafruit NeoPixel@^1.15.4
rtclib             = adafruit/RTClib@^2.1.4 ; untested
; Displays (may be incomplete, some are local libraries)
gc9a01a            = adafruit/Adafruit GC9A01A@^1.1.0 ; untested - may need to try 1.0.0
ili9341            = adafruit/Adafruit ILI9341@^1.6.2 ; SPI TFT
n5110              = adafruit/Adafruit PCD8544 Nokia 5110 LCD library@^2.0.3 ; untested
sh110x             = adafruit/Adafruit SH110X@^2.1.14 ; OLED
ssd1305            = adafruit/Adafruit SSD1305^2.2.3 ; untested
ssd1306            = adafruit/Adafruit SSD1306@^2.5.16 ; Tiny OLED
ssd1327            = adafruit/Adafruit SSD1327@^1.0.4 ; untested OLED
st7735             = adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ; SPI TFT (Red Board, probably others)
st7789             = ${library.st7735} ; alias
; Touchscreens
tamc_gt911         = tamctec/TAMC_GT911@^1.0.2 ; untested but should be fine
xpt2046            = paulstoffregen/XPT2046_Touchscreen ; only 1 version: 0.0.0-alpha+sha.26b691b2c8
 

; -----------------------------------------------------------------------
; Board: ESP32-S3 N16R8 (16MB Flash 8MB PSRAM)
; -----------------------------------------------------------------------
[esp32_s3_n16r8]
extends = ehradio
board = esp32-s3-devkitc-1
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = builds/partitions/default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;board_build.psram = disable
build_flags =
  ${ehradio.build_flags}
  -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1

; -----------------------------------------------------------------------
; Board: ES3C28P (ESP32-S3-N16R8)
; -----------------------------------------------------------------------
[es3c28p]
extends = ehradio
board = esp32-s3-devkitc-1
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = builds/partitions/default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  ${ehradio.build_flags}
  -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

; -----------------------------------------------------------------------
; RADIO FIRMWARES
; -----------------------------------------------------------------------

[env:sh1106_pcm_remote]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DSH1106_PCM_REMOTE
lib_deps =
  ${ehradio.lib_deps}
  ${library.sh110x}
  ${library.onebutton}
  ${library.rotaryencoder}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>

[env:sh1106_pcm_1button]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DSH1106_PCM_1BUTTON
lib_deps =
  ${ehradio.lib_deps}
  ${library.sh110x}
  ${library.onebutton}
  ${library.rotaryencoder}
  ${library.irremote}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>

[env:sh1106_vs1053_3buttons]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DSH1106_VS1053_3BUTTONS
lib_deps =
  ${ehradio.lib_deps}
  ${library.sh110x}
  ${library.onebutton}
  ${library.rotaryencoder}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/VS1053_Audio/*>

[env:st7735_pcm_1button]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DST7735_PCM_1BUTTON
lib_deps =
  ${ehradio.lib_deps}
  ${library.st7735}
  ${library.onebutton}
  ${library.rotaryencoder}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>

[env:ili9488_pcm_1button]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DILI9488_PCM_1BUTTON
lib_deps =
  ${ehradio.lib_deps}
  ${library.onebutton}
  ${library.rotaryencoder}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>
  +<libraries/ILI9488/*>

[env:ili9488_pcm_1button_full]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DILI9488_PCM_1BUTTON_FULL
lib_deps =
  ${ehradio.lib_deps}
  ${library.rotaryencoder}
  ${library.onebutton}
  ${library.irremote}
  ${library.rtclib}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/ILI9488/*>
  +<libraries/I2S_Audio/*>

[env:ili9488_vs1053_1button]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DILI9488_VS1053_1BUTTON
lib_deps =
  ${ehradio.lib_deps}
  ${library.onebutton}
  ${library.rotaryencoder}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/VS1053_Audio/*>
  +<libraries/ILI9488/*>

[env:es3c28p]
extends = es3c28p
build_flags =
  ${es3c28p.build_flags}
  -DES3C28P
lib_ignore = Adafruit SH110X ; weird... without this line, it gets included... but no side-effects either way.  So... this is just a note.  Lol.
lib_deps =
  ${ehradio.lib_deps}
  ${library.ili9341}
  ${library.onebutton}
  ${library.neopixel}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>+<libraries/ES8311_Audio/*>+<libraries/FT6336_Touchscreen/*>
