#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate locale_js.h from src/locale/locale.js

Usage:
    py src/locale/locale_js_to_h.py
"""

import io, os, sys, gzip

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_JS  = os.path.join(SCRIPT_DIR, 'locale.js')
OUTPUT_H  = os.path.join(SCRIPT_DIR, 'locale_js.h')


def bytes_to_hex_array(data, indent=2):
    """Convert bytes to C hex array string."""
    hex_str = ', '.join(f'0x{b:02X}' for b in data)
    prefix = ' ' * indent
    lines = []
    current = prefix
    for i, h in enumerate(hex_str.split(', ')):
        chunk = h + (',' if i < len(data) - 1 else '')
        if len(current) + len(chunk) + 1 > 100:
            lines.append(current.rstrip())
            current = prefix + chunk
        else:
            if current == prefix:
                current += chunk
            else:
                current += ' ' + chunk
    if current.strip():
        lines.append(current.rstrip())
    return '\n'.join(lines)


def generate():
    with open(INPUT_JS, 'r', encoding='utf-8') as f:
        raw = f.read()

    compressed = gzip.compress(raw.encode('utf-8'), compresslevel=9)

    lines = []
    lines.append('// AUTO-GENERATED by locale_js_to_h.py — DO NOT EDIT')
    lines.append(f'// locale.js — {len(compressed)} bytes gzipped ({len(raw)} bytes raw)')
    lines.append('#pragma once')
    lines.append('#include <pgmspace.h>')
    lines.append('')
    lines.append(f'const uint8_t locale_js_gz[] PROGMEM = {{')
    lines.append(bytes_to_hex_array(compressed))
    lines.append('};')
    lines.append('')
    lines.append(f'#define LOCALE_JS_GZ_SIZE {len(compressed)}')
    lines.append('')

    return '\n'.join(lines)


def main():
    if not os.path.exists(INPUT_JS):
        print(f"ERROR: {INPUT_JS} not found")
        sys.exit(1)

    header = generate()
    with open(OUTPUT_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
    print(f"Generated: {OUTPUT_H} ({len(header)} bytes)")


if __name__ == '__main__':
    main()
