#ifndef options_h
#define options_h
#pragma once

#define RADIOVERSION "2026.07.20"

/*******************************************************
THIS FILE IS THE DEFINITIVE HANDLER OF COMPILE OPTIONS.
Most macros used in the codebase are here somewhere.
There are notes and options and examples that can be
used in myoptions.h when compiling.

                                   DO NOT EDIT THIS FILE!

myoptions.h should exist in the root folder.
You can use the myoptions.h and platformio.ini generator:
https://trip5.github.io/ehRadio/myoptions/generator.html
or examine the examples in builds/trip5 and make your own!

mytheme.h is no longer compiled in - if you have a
custom theme, use importtheme.py in src/display folder
********************************************************/

#if __has_include("../../myoptions.h")
  #include "../../myoptions.h" // write your variable values here
#endif

#if !(defined(ARDUINO_ESP32_DEV) || defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV))
  #error define error in platformio.ini: only ARDUINO_ESP32_DEV, ARDUINO_ESP32S3_DEV, or ARDUINO_ESP32C3_DEV boards are supported
#endif


/*******************************************************
Use this tool to setup connections:
https://trip5.github.io/ehRadio/myoptions/generator.html
(a basic tool and not definitive for all possible configurations)
********************************************************/


/* ============================== DISPLAY ============================== */

/* --- DISPLAYS ENUM --- */
// DSP_MODEL identifies the controller / driver chip.
// Resolution variants use DSP_WIDTH / DSP_HEIGHT (see below).
// Interface (I2C vs SPI/parallel) is auto-detected from pin definitions.
// If I2C_SDA != 255 && I2C_SCL != 255 → I2C, otherwise SPI/parallel.
// ST7735 sub-models uses DTYPE (required by Adafruit_ST7735 library).

#define DSP_DUMMY       0 // no display
#define DSP_1602        1 // 16x2 (fixed in displayLC1602.h): Parallel or I2C (auto-detected from pins)
#define DSP_2004        2 // 20x4 (fixed in displayLC1602.h): Parallel or I2C (auto-detected from pins)
#define DSP_GC9A01A     3 // 240x240 round (fixed in displayGC9A01A.h)
#define DSP_GC9106      4 // 160x80 (fixed in displayGC9106.h)
#define DSP_ILI9225     5 // 220x176 (default)
#define DSP_ILI9341     6 // 320x240 (fixed in displayILI9341.h)
#define DSP_ILI9488     7 // 480x320 (default)
#define DSP_ILI9486     8 // 480x320 (default) (not fully tested - see notes inside the library regarding gamma correction)
#define DSP_NOKIA5110   9 // 84x48 (fixed in displayN5110.h)
#define DSP_SH1106      10 // 128x64 (default): SPI or I2C (auto-detected from pins)
#define DSP_SH1107      11 // 128x64 (default): SPI or I2C (auto-detected from pins)
#define DSP_SSD1305     12 // 128x64 (default): SPI or I2C (auto-detected from pins)
#define DSP_SSD1306     13 // 128x64 (default): SPI or I2C (auto-detected from pins)
#define DSP_SSD1322     14 // 256x64 (default): SPI
#define DSP_SSD1327     15 // 128x64 (default): SPI or I2C (auto-detected from pins)
#define DSP_ST7735      16 // 160x128 / 128x128 / 160x80 (dimensions derived from DTYPE in displayST7735.h)
#define DSP_ST7789      17 // 320x240 (default)
#define DSP_ST7796      18 // 480x320 (default)
#define DSP_ST7920      19 // 128x64 (fixed in displayST7920.h)

/* Define your display as #define DSP_MODEL DSP_ILI9488 */

#ifndef DSP_MODEL
  #define DSP_MODEL DSP_DUMMY
#endif
#if DSP_MODEL==DSP_DUMMY
  #define DUMMYDISPLAY // do not use directly in myoptions.h!
  #define DSP_WIDTH  0
  #define DSP_HEIGHT 0
  #undef ONE_CLICK_SWITCH
  #define ONE_CLICK_SWITCH true // need to force this on with no display
#endif

/* --- DISPLAY RESOLUTION --- */
// DSP_WIDTH / DSP_HEIGHT set the panel resolution in pixels.
// Displays whose constructor accepts dimensions have defaults below - override in myoptions.h for variants
// Some displays have a constructor that does NOT accept dimensions - they have fixed values in their display*.h header (see notes above)
// These values are consumed by dspconf.h (conf file) and dspfont.h (fonts/bootlogo).

#if DSP_MODEL==DSP_ILI9225
  #ifndef DSP_WIDTH
    #define DSP_WIDTH  220
  #endif
  #ifndef DSP_HEIGHT
    #define DSP_HEIGHT 176
  #endif
#elif DSP_MODEL==DSP_ILI9488 || DSP_MODEL==DSP_ILI9486 || DSP_MODEL==DSP_ST7796
  #ifndef DSP_WIDTH
    #define DSP_WIDTH  480
  #endif
  #ifndef DSP_HEIGHT
    #define DSP_HEIGHT 320
  #endif
#elif DSP_MODEL==DSP_SH1106 || DSP_MODEL==DSP_SH1107 || DSP_MODEL==DSP_SSD1305 || DSP_MODEL==DSP_SSD1306 || DSP_MODEL==DSP_SSD1327
  #ifndef DSP_WIDTH
    #define DSP_WIDTH  128
  #endif
  #ifndef DSP_HEIGHT
    #define DSP_HEIGHT 64
  #endif
#elif DSP_MODEL==DSP_SSD1322
  #ifndef DSP_WIDTH
    #define DSP_WIDTH  256
  #endif
  #ifndef DSP_HEIGHT
    #define DSP_HEIGHT 64
  #endif
#elif DSP_MODEL==DSP_ST7789
  #ifndef DSP_WIDTH
    #define DSP_WIDTH  320
  #endif
  #ifndef DSP_HEIGHT
    #define DSP_HEIGHT 240
  #endif
#endif

/* --- TFT DISPLAY --- */
/* SPI displays always use SPIA bus by default (see below for more) */
#ifndef TFT_CS
  #define TFT_CS 255
#endif
#ifndef TFT_RST
  #define TFT_RST -1 // Or set to -1 and connect to Esp EN pin
#endif
#ifndef TFT_DC
  #define TFT_DC 255
#endif

/* ST7735 display submodel */
// INITR_BLACKTAB // 1.8" https://aliexpress.ru/item/1005002822797745.html
//     See this note If INITR_BLACKTAB have a noisy line on one side of the screen https://github.com/e2002/yoradio#note-if-initr_blacktab-dsp-have-a-noisy-line-on-one-side-of-the-screen-then-in-adafruit_st7735cpp
// INITR_144GREENTAB // 1.44" https://aliexpress.ru/item/1005002822797745.html
// INITR_MINI160x80 // 0.96" 160x80
// INITR_GREENTAB
// INITR_REDTAB
#ifndef DTYPE
  #define DTYPE INITR_BLACKTAB
#endif

/* --- I2C DISPLAY PINS --- */
#ifndef I2C_SDA
  #define I2C_SDA 255 // Defaults: ESP32 21, ESP32-S3 8
#endif
#ifndef I2C_SCL
  #define I2C_SCL 255 // Defaults: ESP32 22, ESP32-S3 9
#endif
#ifndef I2C_RST
  #define I2C_RST -1 // -1 means not used
#endif

/* --- LCD DISPLAY PINS --- */
#ifndef LCD_RS
  #define LCD_RS 255
#endif
#ifndef LCD_E
  #define LCD_E 255
#endif
#ifndef LCD_D4
  #define LCD_D4 255
#endif
#ifndef LCD_D5
  #define LCD_D5 255
#endif
#ifndef LCD_D6
  #define LCD_D6 255
#endif
#ifndef LCD_D7
  #define LCD_D7 255
#endif

/* --- DISPLAY OPTIONS --- */
#ifndef ROTATE_90
  #define ROTATE_90 false // Optional 90 degree rotation for square displays
#endif
#ifndef BRIGHTNESS_PIN
  #define BRIGHTNESS_PIN 255 // BRIGHTNESS Pin
#endif

/* Can the display be dimmed? If it is set to true but the Brightness Pin is not set... */
/* This enables / disables the ability, not the default option DIMMING_ENABLED */

#if defined(DSP_DIMMING_ENABLED) && DSP_DIMMING_ENABLED && BRIGHTNESS_PIN==255
  #warning DSP_DIMMING_ENABLED is true but BRIGHTNESS_PIN is not set so setting DSP_DIMMING_ENABLED false
  #undef DSP_DIMMING_ENABLED
#endif
#ifndef DSP_DIMMING_ENABLED
    #define DSP_DIMMING_ENABLED false
#endif  

#ifndef LIGHT_SENSOR
  #define LIGHT_SENSOR 255 // Light sensor
#endif
#ifndef AUTOBACKLIGHT // Auto-dimming with the light sensor (not related to DSP_DIMMING_ENABLED)
  #ifndef AUTOBACKLIGHT_MAX
    #define AUTOBACKLIGHT_MAX 1500
  #endif
  #ifndef AUTOBACKLIGHT_MIN
    #define AUTOBACKLIGHT_MIN 12
  #endif
  #define AUTOBACKLIGHT(x) ({uint16_t _lh=(x>AUTOBACKLIGHT_MAX?AUTOBACKLIGHT_MAX:x); map(_lh, AUTOBACKLIGHT_MAX, 0, AUTOBACKLIGHT_MIN, 100);}) // autobacklight function
#endif

/* --- DISPLAY TRANSFORM --- */

#ifndef DSP_INVERT_QUIRK
  #define DSP_INVERT_QUIRK false // if a display shows inverted colors by default, override it by setting this to true
#endif
#ifndef RSSI_DIGIT
  #define RSSI_DIGIT false // display RSSI as number
#endif
#ifndef RSSI_STEPS
  #define RSSI_STEPS -50,-60,-70,-80
#endif
/* Use #define BIG_BOOT_LOGO with big displays (480x320) displays if you want a bigger boot logo */
#if DSP_WIDTH >= 480
  #ifndef BIG_BOOT_LOGO
    #if defined(CONFIG_IDF_TARGET_ESP32) // ESP32 is already low on flash size and this is huge
      #define BIG_BOOT_LOGO false
    #else
      #define BIG_BOOT_LOGO true
    #endif
  #endif
#endif

/* Define your display font as: #define DISPLAYFONT X11       */
#define MATRIXLIGHT     0
#define MATRIXCHUNKY    1
#define X11             2   // Unix X11 6x9 fixed-width

#ifndef DISPLAYFONT
  #define DISPLAYFONT MATRIXCHUNKY
#endif

/* Define your clock/volume page font as #define CLOCKFONT CHUNKY6 */
#define YO_MONO         0  // Default modern yoRadio 7-Segment font (monospaced)
#define CHUNKY6_PX      1  // Default (spacing pixels) - great on color screens
#define CHUNKY6         2  // Really heavy looking - great on mono screens

/* Chunky6 with spaces between pixels is the default (except on OLEDs) */
#ifndef CLOCKFONT
  #if DSP_MODEL==DSP_SH1106 || DSP_MODEL==DSP_SH1107 || DSP_MODEL==DSP_SSD1305 || DSP_MODEL==DSP_SSD1306 || DSP_MODEL==DSP_SSD1327
  // note that using YO_MONO on the above list of displays will revert to the display font.
    #define CLOCKFONT CHUNKY6
  #else
    #define CLOCKFONT CHUNKY6_PX
  #endif
#endif

/* This makes the characters get an LED/VFD background color that makes it look like a real clock (only has an effect on color displays) */
#ifndef CLOCKGLOW // CLOCKGLOW uses a special character to color COLOR_CLOCK_BG behind the clock for a glow effect
  #if CLOCKFONT == YO_MONO || CLOCKFONT == CHUNKY6_PX
    #define CLOCKGLOW true
  #else
    #define CLOCKGLOW false // with CHUNKY6, this effect looks not great
  #endif
#endif

/* Playlist Mode: some displays have trouble displaying the fancy "fade" playlist - this list may be incomplete */
// ILI9488 uses 24 bits per pixel instead of 16 or 8, resulting in a 33% slower refresh rate... making a nasty slowdown on a big display when it needs to redraw the entire screen
// use PLAYLIST_MODE_PAGED true if your display has issues on the playlist screen or if you just want to use page mode (but it doesn't scroll long station names)
#if DSP_MODEL==DSP_1602 || DSP_MODEL==DSP_2004 // LCD tiny displays can't do different playlist modes
  #undef PLAYLIST_MODE_PAGED
#elif DSP_MODEL==DSP_ILI9488 || DSP_MODEL==DSP_ILI9486 // These screens are known to be slow to refresh and benefit from a simpler playlist mode
  #ifndef PLAYLIST_MODE_PAGED
    #define PLAYLIST_MODE_PAGED true
  #endif
#else
  #ifndef PLAYLIST_MODE_PAGED
    #define PLAYLIST_MODE_PAGED false
  #endif
#endif

/* Scrolling Speed: may be manually tweaked using myoptions.h */
/* check dspcore.h for actual defaults, especially for LCD displays */
// pixels per second = scrolldelta * 1000 / scrolltime]
// Here are the defaults for OLED and TFT displays:
// #define SCROLLDELAY 5000 // delay time (ms) for widgets: meta, title1, title2 / playlist mode scroll divides by 5
// #define SCROLLTIME 15 // time (ms) per pixel-column movement (a column of font pixels, not display pixels)
// if using an LCD screen, check dspcore.h for safe values

/* Pre-processed Text: Prefer ALL CAPS? Maybe all latin accents removed from your display? */
// #define PRETEXT_ALLCAPS
// #define PRETEXT_FOLDACCENT

/* If using PRETEXT_ALLCAPS, why not do the same to your WebUI? */
// #define WWW_CASETRANSFORM

/* ============================== SPI BUSES AND PINS ============================== */

/* To allow multiple devices to use the same/different SPI buses, we name them */
/* VSPI is patched to FSPI for third-party library compatibility on ESP32-S3/C3 (Adafruit etc.) */
#include <SPI.h>
#if !defined(CONFIG_IDF_TARGET_ESP32)
  #define VSPI FSPI
#endif

/* --- NAMED SPI BUSES --- */
/* Two hardware SPI buses are available (Bus A = &SPI default, Bus B = secondary). */

/* Bus A/Primary SPI Bus (&SPI default) is important to use default pins (but can be overridden if needed) */
/* Define all manually or use shorthand #define SPIA_DEFAULT to use defaults */
/* For displays that do not use MISO, use shorthand #define SPIA_DEFAULT_XMISO */
#if defined(SPIA_DEFAULT) || defined(SPIA_DEFAULT_XMISO)
  #if !defined(SPIA_SCK) && !defined(SPIA_MISO) && !defined(SPIA_MOSI)
    #if defined(CONFIG_IDF_TARGET_ESP32) // ESP32 default VSPI/SPI3
      #define SPIA_SCK 18
      #define SPIA_MISO 19
      #define SPIA_MOSI 23
    #elif defined(CONFIG_IDF_TARGET_ESP32S3) // ESP32-S3 default FSPI/SPI2
      #define SPIA_SCK 12
      #define SPIA_MISO 13
      #define SPIA_MOSI 11
    #elif defined(CONFIG_IDF_TARGET_ESP32C3) // ESP32-C3 default FSPI/SPI2
      #define SPIA_SCK 4
      #define SPIA_MISO 5
      #define SPIA_MOSI 6
    #endif
	  #if defined(SPIA_DEFAULT_XMISO)
      #undef SPIA_MISO
      #define SPIA_MISO 255 // unused (most SPI displays)
    #endif
  #endif
#endif

/* Bus B / Secondary SPI Bus is less-important to use default pins (and may not be needed at all) */
/* Nevertheless, shorthand #define SPIB_DEFAULT may be used to set defaults for ESP32 */
#if defined(SPIB_DEFAULT)
  #if !defined(SPIB_SCK) && !defined(SPIB_MISO) && !defined(SPIB_MOSI)
    #if defined(CONFIG_IDF_TARGET_ESP32) // ESP32 default VSPI/SPI3
      #define SPIB_SCK 14
      #define SPIB_MISO 12
      #define SPIB_MOSI 13
    #elif defined(CONFIG_IDF_TARGET_ESP32C3) // ESP32-C3 default FSPI/SPI2
      #error SPIB_DEFAULT defined but ESP32-C3 can not use a secondary SPI bus!
    #else defined(CONFIG_IDF_TARGET_ESP32S3)
      #error SPIB_DEFAULT defined but ESP32-S3 does not have default secondary SPI pins!
    #endif
  #endif
#endif
// Display (if SPI) will always use SPIA / Primary bus.
// Define other peripheral SPI bus assignments in myoptions.h as so:
//       #define VS1053_SPI 'A' // VS1053 decoder on Bus A (if no SPI Display)
//       #define SD_SPI     'B' // SD card on Bus B
//       #define TS_SPI     'B' // Touchscreen on Bus B
//
// Internal macros SPIA, SPI_BUS_PRIMARY, SPI_BUS_SECONDARY, VS1053_SPIBUS are
// auto-derived below.  DO NOT SET THESE in myoptions.h.
#define SPIA SPI // Bus A alias — always the default &SPI instance
/* Auto-derive SPI bus controller numbers. Use symbolic constants (FSPI, HSPI, VSPI)
   defined by the Arduino framework so the correct hardware peripheral is used. */
#if defined(CONFIG_IDF_TARGET_ESP32)
  #define SPI_BUS_PRIMARY   VSPI  // 3 — default &SPI bus on ESP32
  #define SPI_BUS_SECONDARY HSPI  // 2 — secondary bus on ESP32
#else
  // ESP32-S3/C3: FSPI=SPI2_HOST (default), HSPI=SPI3_HOST (secondary)
  #define SPI_BUS_PRIMARY   FSPI
  #define SPI_BUS_SECONDARY HSPI
#endif

/* Override SPI, I2C Speeds and Addresses with myoptions.h */
// may not work for all display drivers, especially if custom libraries are included. ie. ILI9488 which is fixed to 40000000UL
// #define DEF_SPI_FREQ 8000000UL // defaults usually OK; may range from 8000000UL (8 MHz) to 80000000UL (80 MHz); check your datasheet before changing! set to 0 for factory default (will override codebase default)
// #define I2CFREQ_HZ   400000UL // OLED driver default is 4000000UL (4 MHz); lower e.g. to 400000UL (400 kHz) if display is glitchy; range: 100000UL (100 kHz) to 4000000UL (4 MHz)
// #define SCREEN_ADDRESS 0x3C // see datasheet for address or scan it https://create.arduino.cc/projecthub/abdularbi17/how-to-scan-i2c-address-in-arduino-eaadda


/* ============================== AUDIO ============================== */

/* --- VS1053 PINS --- */
#ifndef VS1053_CS
  #define VS1053_CS 255
#endif
#ifndef VS1053_DCS
  #define VS1053_DCS 255
#endif
#ifndef VS1053_DREQ
  #define VS1053_DREQ 255
#endif
#ifndef VS1053_RST
  #define VS1053_RST -1 // set to -1 if connected to Esp EN pin
#endif
// myoptions.h should also define which SPI bus will be used - VS1053 should be alone on this bus
// #define VS1053_SPI 'A' // VS1053 decoder on Bus A (no display on A)
// #define VS1053_SPI 'B' // VS1053 decoder on Bus B
#if VS1053_CS!=255 && !defined(VS1053_SPI)
  #error VS1053_SPI not defined in myoptions.h
#endif
/* VS1053 bus assignment: auto-derived from which bus VS1053_SCK belongs to. */
/* Helper for VS1053 library */
#if defined(VS1053_SPI) && !defined(VS1053_SCK)
  #if VS1053_SPI == 'A' && defined(SPIA_SCK)
    #define VS1053_SCK  SPIA_SCK
    #define VS1053_MISO SPIA_MISO
    #define VS1053_MOSI SPIA_MOSI
    #define VS1053_SPI_BUS 'A'
  #elif VS1053_SPI == 'B' && defined(SPIB_SCK)
    #define VS1053_SCK  SPIB_SCK
    #define VS1053_MISO SPIB_MISO
    #define VS1053_MOSI SPIB_MOSI
    #define VS1053_SPI_BUS 'B'
  #endif
  #undef VS1053_SPI // audioVS1053Ex.h declares 'SPISettings VS1053_SPI' so now we need to undefine it (saving it first for bootlog in VS1053_SPI_BUS)
#endif
/* Do not set VS1053_SPIBUS in myoptions.h */
#if VS1053_CS != 255
  #if !defined(VS1053_SCK)
    #error define error in myoptions.h: VS1053 enabled (VS1053_CS != 255) but VS1053_SCK not defined. Set VS1053_SPI 'A' or 'B' with matching SPIA_/SPIB_ bus pins, or define VS1053_SCK/MISO/MOSI directly.
  #elif defined(SPIB_SCK) && (VS1053_SCK == SPIB_SCK)
    #define VS1053_SPIBUS SPIB // VS1053 on Bus B
  #else
    #define VS1053_SPIBUS SPIA // VS1053 on Bus A
  #endif
#endif
/* Enables flac decoding on true VS1053B boards - will be disabled unless explicitly set true in myoptions.h */
#ifndef VS_PATCH_ENABLE
  #define VS_PATCH_ENABLE false /* Enables FLAC playback on VS1053B boards but should be false (the default) for VS1003 and VS1053 (non-B) boards. Some boards sold as VS1053 but actually VS1003 will have 2.5V voltage regulator instead of 1.8V. */
#endif
#if VS_PATCH_ENABLE==false && VS1053_CS != 255 // unfortunately, the VU Meter doesn't work on VS1053 without the patch
  #undef SHOW_VU_METER
  #define SHOW_VU_METER false
#endif
/* Three volume curves are available on the VS1053 */
// the original is a perceptual log scale... it's kind of a steep volume on low numbers:
//#define VS1053_VOL_LOG
// this one follows the I2S polynomial curve exactly (starting at -60dB) but an unamplified VS1053 may be mute for the first 25% of the volume scale:
//#define VS1053_VOL_CURVE
// Add one of those to your myoptions.h to override the default which is the same polynomial curve but starts at -35dB

/* --- I2S PCM DAC --- */
#ifndef I2S_DOUT
  #define I2S_DOUT 255 // DIN connection
#endif
#ifndef I2S_BCLK
  #define I2S_BCLK 255 // BCLK Bit clock
#endif
#ifndef I2S_LRC
  #define I2S_LRC 255 // WSEL Left Right Clock
#endif
#ifndef I2S_DIN
  #define I2S_DIN 255 // optional DIN (not wired by default)
#endif
#ifndef I2S_MCLK
  #define I2S_MCLK 255 // optional MCLK (not wired by default)
#endif

/* --- I2S ES8311 DECODER --- */

/* a special define for a special decoder */
/* #define USE_ES8311 activates the ES8311 mono decoder */
/* requires I2S DOUT BCLK LRC (and MCLK probably too) pins defined */
#ifdef USE_ES8311
  #ifndef ES8311_MAX_I2S
    #define ES8311_MAX_I2S 180 // Maximum I2S value to allow when mapping to ES8311 codec (0..VOLUME_SCALE)
  #endif
  #ifndef PLAYER_FORCE_MONO
    #define PLAYER_FORCE_MONO true // forces the VU meter mono (setting false doesn't change hardware capability)
  #endif
  #if defined(ES8311_I2C_SCL) && ES8311_I2C_SCL != 255 && defined(ES8311_I2C_SDA) && ES8311_I2C_SCL != 255
    // may fix volume on boot issues (if defined and not 255)
    // #define ES8311_I2C_SCL  15
    // #define ES8311_I2C_SDA  16
  #else
    #undef ES8311_I2C_SCL
    #undef ES8311_I2C_SDA
  #endif
#endif

/* --- DECODER OPTIONS --- */
#ifndef MUTE_PIN
  #define MUTE_PIN 255 // MUTE Pin
#endif
#ifndef MUTE_VAL
  #define MUTE_VAL HIGH // Write this to MUTE_PIN when player is stopped
#endif
#ifndef MUTE_LOCK
  #define MUTE_LOCK false // for vs1053 Shield rev2 - lock MUTE_PIN to !MUTE_VAL
#endif
#ifndef PLAYER_FORCE_MONO
  #define PLAYER_FORCE_MONO false // mono option - false stereo, true mono (also add for mono I2S decoders for the VU)
#endif

/* --- VOLUME SCALE --- */
#ifndef VOLUME_SCALE // Default 42 doubles upstream library's scale of 21; 50-100 gives extremely fine control
  #define VOLUME_SCALE 42
#endif
#if VOLUME_SCALE < 21 || VOLUME_SCALE > 255
  #error VOLUME_SCALE must be between 21 and 255
#endif


/* --- CHECK DECODER OPTIONS --- */
#if I2S_DOUT!=255 && VS1053_CS!=255
  #error define error in myoptions.h: both I2S_DOUT and VS1053_CS are active - set I2S_DOUT 255 or VS1053_CS 255 to disable one
#endif

/* Derived audio decoder gates - do NOT define these directly in myoptions.h. */
/* USE_AUDIO_VS1053 is defined when all six required VS1053 pins are present. */
/* USE_AUDIO_I2S is defined when the three required I2S pins are present. */
/* These replace the old I2S_DOUT==255 / VS1053_CS==255 gate pattern used in yoRadio */
#if VS1053_CS!=255 && VS1053_DCS!=255 && VS1053_DREQ!=255 && VS1053_MOSI!=255 && VS1053_MISO!=255 && VS1053_SCK!=255
  #define USE_AUDIO_VS1053
#endif
#if I2S_DOUT != 255 && I2S_BCLK!=255 && I2S_LRC!=255
  #define USE_AUDIO_I2S
#endif
#if defined(USE_AUDIO_VS1053) && defined(USE_AUDIO_I2S)
  #error Both VS1053 audio and I2S audio are active. Check your pin definitions.
#endif
#if !defined(USE_AUDIO_VS1053) && !defined(USE_AUDIO_I2S)
  #error No audio decoder active. Define VS1053 SPI pins or I2S pins in myoptions.h.
#endif


/* ============================== SD CARD ============================== */
#ifndef SD_CS
  #define SD_CS 255 // SDCARD CS pin: 255 = disabled
#endif
// myoptions.h should also define which SPI bus will be used:
// #define SD_SPI 'A' // SD card on Bus A
// #define SD_SPI 'B' // SD card on Bus B
#if SD_CS!=255
  #if !defined(SD_SPI)
    #error SD_SPI not defined in myoptions.h
  #else
    #define USE_SD
  #endif
#endif
#ifndef SDSPISPEED
  #if defined(ARDUINO_ESP32_DEV)
    #define SDSPISPEED 20000000 // safe
  #elif defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)
    #define SDSPISPEED 40000000 // S3 known to work at this speed (even with custom pins)
  #else
    #define SDSPISPEED 20000000 // safe
  #endif
#endif
#ifndef SD_CARD_DETECT_PIN
  #define SD_CARD_DETECT_PIN 255 // GPIO pin for mechanical SD card-detect switch (LOW=card present, HIGH=slot empty). 255 = disabled.
#endif
#ifndef SD_AUTOPLAY
  #define SD_AUTOPLAY false // auto-switch to SD card mode when card is inserted (requires SD_CARD_DETECT_PIN != 255)
#endif
#ifndef SD_MAX_LEVELS
  #define SD_MAX_LEVELS 5 // search depth for files on the SD card
#endif
#if SD_MAX_LEVELS < 1 || SD_MAX_LEVELS > 10
  #error define error in myoptions.h: SD_MAX_LEVELS must be between 1 and 10
#endif


/* ============================== INPUT ============================== */

/* --- ROTARY ENCODER --- */
#ifndef ENC_DT
  #define ENC_DT 255
#endif
#ifndef ENC_SW
  #define ENC_SW 255
#endif
#ifndef ENC_CLK
  #define ENC_CLK 255
#endif
#ifndef ENC_PULLUP // use internal pullup on rotary Credit: Buska1968 https://4pda.to/forum/index.php?s=&showtopic=1010378&view=findpost&p=113385448
  #define ENC_PULLUP true
#endif
#ifndef ENC_SW_PULLUP // use internal pullup on button
  #define ENC_SW_PULLUP true
#endif
#ifdef ENC_STEPS
  #if !(ENC_STEPS == 1 || ENC_STEPS == 2 || ENC_STEPS == 4) // KY-040 requires 2, bare encoders 4
    #error ENC_STEPS 1 or 2 or 4 only please (2 is default)
  #endif
#else
  #define ENC_STEPS 2
#endif

#ifndef ENC2_DT
  #define ENC2_DT 255
#endif
#ifndef ENC2_SW
  #define ENC2_SW 255
#endif
#ifndef ENC2_CLK
  #define ENC2_CLK 255
#endif
#ifndef ENC2_PULLUP // use internal pullup on rotary
  #define ENC2_PULLUP true
#endif
#ifndef ENC2_SW_PULLUP // use internal pullup on button
  #define ENC2_SW_PULLUP true
#endif
#ifdef ENC2_STEPS
  #if !(ENC2_STEPS == 1 || ENC2_STEPS == 2 || ENC2_STEPS == 4) // KY-040 requires 2, bare encoders 4
    #error ENC2_STEPS 1 or 2 or 4 only please (2 is default)
  #endif
#else
  #define ENC2_STEPS 2
#endif

/* --- BUTTONS --- */
/* Useful if you want to apply false to all pullups with one define (otherwise true) */
#ifdef BTN_INTERNALPULLUP
  #define BTN_PREV_PULLUP BTN_INTERNALPULLUP
  #define BTN_PLAY_PULLUP BTN_INTERNALPULLUP
  #define BTN_NEXT_PULLUP BTN_INTERNALPULLUP
  #define BTN_UP_PULLUP BTN_INTERNALPULLUP
  #define BTN_DOWN_PULLUP BTN_INTERNALPULLUP
  #define BTN_MODE_PULLUP BTN_INTERNALPULLUP
#endif
/* ehRadio Buttons */
#ifndef BTN_DOWN
  #define BTN_DOWN 255
#endif
#ifndef BTN_DOWN_PULLUP
  #define BTN_DOWN_PULLUP true
#endif
#ifndef BTN_PLAY
  #define BTN_PLAY 255
#endif
#ifndef BTN_PLAY_PULLUP
  #define BTN_PLAY_PULLUP true
#endif
#ifndef BTN_UP
  #define BTN_UP 255
#endif
#ifndef BTN_UP_PULLUP
  #define BTN_UP_PULLUP true
#endif
#ifndef BTN_PREV
  #define BTN_PREV 255
#endif
#ifndef BTN_PREV_PULLUP
  #define BTN_PREV_PULLUP true
#endif
#ifndef BTN_NEXT
  #define BTN_NEXT 255
#endif
#ifndef BTN_NEXT_PULLUP
  #define BTN_NEXT_PULLUP true
#endif
#ifndef BTN_MODE
  #define BTN_MODE 255
#endif
#ifndef BTN_MODE_PULLUP
  #define BTN_MODE_PULLUP true
#endif
#ifndef BTN_LONGPRESS_LOOP_DELAY
  #define BTN_LONGPRESS_LOOP_DELAY 200 // delay between calling DuringLongPress event
#endif
#ifndef BTN_CLICK_TICKS
  #define BTN_CLICK_TICKS 300
#endif
#ifndef BTN_PRESS_TICKS
  #define BTN_PRESS_TICKS 500
#endif
#if BTN_PRESS_TICKS <= BTN_CLICK_TICKS
  #error define error in myoptions.h: BTN_PRESS_TICKS must be greater than BTN_CLICK_TICKS
#endif

/* --- TOUCH SCREEN --- */
#define TS_MODEL_UNDEFINED 0
#define TS_MODEL_XPT2046 1
#define TS_MODEL_GT911 2
#define TS_MODEL_FT6336 3

#ifndef TS_MODEL
  #define TS_MODEL TS_MODEL_UNDEFINED
#endif
#if (TS_MODEL < 0) || (TS_MODEL > 3)
  #error define error in myoptions.h: TS_MODEL must be TS_MODEL_XPT2046, TS_MODEL_GT911, or TS_MODEL_FT6336
#endif

#ifndef TS_CS
  #define TS_CS 255
#endif
#ifndef TS_SDA
  #define TS_SDA 255
#endif
#ifndef TS_SCL
  #define TS_SCL 255
#endif
#ifndef TS_INT
  #define TS_INT 255
#endif
#ifndef TS_RST
  #define TS_RST 255
#endif
// myoptions.h should also define which SPI bus will be used (if an SPI Touchscreen):
// #define TS_SPI 'A' // Touchscreen on Bus A
// #define TS_SPI 'B' // Touchscreen on Bus B
#if TS_CS!=255 && !defined(TS_SPI)
  #error TS_SPI not defined in myoptions.h
#endif

// Minimum px movement before swipe direction is detected (default: 20 for XPT2046 resistive, 12 for GT911/FT6336 capacitive)
// #define TS_SWIPE_THRESHOLD_PX 20
// Converts screen dimensions to steps (default: 40) ie. higher = more sensitive, lower = less sensitive
// #define TS_STEPS 40
// Post-release debounce in ms (default 150)
// #define TS_COOLDOWN_MS 150
// Window for double-tap detection in ms (default 400)
// #define TS_DOUBLETAP_MS 400
// Stationary hold duration before deep sleep in ms (default 5000)
// #define TS_DEEPSLEEP_MS 5000

/* --- SD OFFLINE MODE BUTTON --- */
// SD Offline Mode is activated by holding the Mode Switch Button or a Rotary Encoder Switch at boot.
// Use this if your build does not include these or if using all buttons interferes with boot
// ...although this actually likely means you should be pulling up the pin.
// #define SDOFFLINE_BTN BTN_MODE
// Use this to deactivate this method of booting to SD Offline Mode:
// #define SDOFFLINE_BTN 255

// You can also use a GPIO directly with this
// #define SDOFFLINE_BTN 2
// ...and you can manually override how the pin is treated (defaults below)
// #define SDOFFLINE_BTN_ACTIVE_LOW true
// #define SDOFFLINE_BTN_PULLUP true


/* --- IR --- */
#ifndef IR_PIN
  #define IR_PIN 255
#endif
#ifndef IR_TIMEOUT
  #define IR_TIMEOUT 80 // kTimeout, see IRremoteESP8266 documentation
#endif

/* --- Deep Sleep --- */
// Wake is only possible on RTC-capable pins. ESP32 RTC GPIOs: 0, 2, 4, 12-15, 25-27, 32-39 / ESP32-S3/C3 RTC GPIOs: 0-21.
// Inputs assigned to these pins will automatically be used for Wake. This includes TS_INT, and all ENC_*, ENC2_* and all BTN_* inputs.
// Use this to disable Deep Sleep entirely:
// #define DEEP_SLEEP_DISABLE


/* ============================== RTC ============================== */

#define RTC_MODULE_UNDEFINED 0
#define DS3231 1
#define DS1307 2

#ifndef RTC_MODULE
  #define RTC_MODULE RTC_MODULE_UNDEFINED  /*  DS3231 or DS1307  */
#endif
#if RTC_MODULE < 0 || RTC_MODULE > 2
  #error define error in myoptions.h: RTC_MODULE must be DS3231 or DS1307 (or leave undefined)
#endif
#ifndef RTC_SDA
  #define RTC_SDA 255
#endif
#ifndef RTC_SCL
  #define RTC_SCL 255
#endif


/* ============================== LED ============================== */

/* You can try using #define LED_PIN LED_BUILTIN but it is better to define the actual pin */
#ifdef LED_PIN
 //#define LED_PIN 8
#else
  #define LED_PIN 255 // unused
#endif
#ifndef LED_INVERT // can define as true in myoptions.h: inverts behavior of above LED
  #define LED_INVERT false
#endif
#ifdef RGB_LED_PIN // will use Neopixel library to control RGB LED with something like:
 //#define RGB_LED_PIN 42
#else
  #define RGB_LED_PIN 255 // unused
#endif
#ifdef RGB_LED_ORDER // Most WS2812 LEDs are actually GRB but can be over-ridden
 // #define RGB_LED_ORDER NEO_GRB
#endif


/* ============================== SYSTEM OVERRIDES ============================== */

/* --- SYSTEM TWEAKS --- */
#ifndef WIFI_ATTEMPTS // about 2 attempts per second
  #define WIFI_ATTEMPTS 16
#endif
#if WIFI_ATTEMPTS < 1
  #error define error in myoptions.h: WIFI_ATTEMPTS must be at least 1
#endif
// How many seconds to wait after boot completed to Start the Async Services (other services are starting and too soon can crash netserver stack).  The less-important services started here (can take a full minute to complete if server connection issues):
// verifies/downloads locale JSON file, checks for new version (triggers autoupdate), downloads PLAYLIST_DEFAULT_URL (if set), updates timezones.json.gz and rb_srvrs.json, cleans up stale search results
#ifndef STARTUP_ASYNC_SERVICES_DELAY
  #define STARTUP_ASYNC_SERVICES_DELAY 20
#endif
 // How many seconds to wait after boot completed (including smart start) to consider successful, if rebooted during that time, will enter safe mode (disables smart start, autoupdate, boots to web not SD)
 #ifndef BOOT_STABLE_TIME
  #define BOOT_STABLE_TIME 30
#endif
#ifndef SEARCHRESULTS_BUFFER
 // Buffer for chunked HTTP transfers from radio-browser.info. Defined in KB; conversion to bytes done in netserver.cpp.
 // ESP32-C3 has less RAM than base ESP32 — keep conservative at 4KB like base ESP32.
  #if defined(ARDUINO_ESP32S3_DEV)
    #define SEARCHRESULTS_BUFFER 32 // KB; matches radio-browser.info chunk size
  #else // ESP32 and ESP32-C3
    #define SEARCHRESULTS_BUFFER 4 // KB
  #endif
#elif SEARCHRESULTS_BUFFER < 4 || SEARCHRESULTS_BUFFER > 64
  #error define error in myoptions.h: SEARCHRESULTS_BUFFER must be between 4 and 64 (value in KB)
#endif
#ifndef SEARCHRESULTS_YIELDINTERVAL
  #define SEARCHRESULTS_YIELDINTERVAL 0 // With a large buffer, skipping is almost eliminated with 0
#endif
#ifdef MAX_PL_READ_BYTES
  //#define MAX_PL_READ_BYTES 1024*64 // Makes chunked HTML transfers but only for playlist.csv and wifi.csv... might help I2S decoder with large playlists
#endif
/* Maximum lengths of character buffers */
/* Notes have been made regarding old yoRadio values */
#ifndef WEATHER_STRING_L
  #define WEATHER_STRING_L 512 // size of weather string, formerly 254
#endif
#ifndef WEBSOCKET_BUFFER
  #define WEBSOCKET_BUFFER 512 // formerly 340
#endif
#ifndef MQTT_URL_SIZE
  #define MQTT_URL_SIZE 512 // shared URL buffer cap for MQTT commands, artwork URLs, and browse URLs
#endif
#ifndef STATION_FIELD_LENGTH
  #define STATION_FIELD_LENGTH 170 // max length for station name, URL, and title fields
#endif
#if STATION_FIELD_LENGTH < 64
  #error define error in myoptions.h: STATION_FIELD_LENGTH is too small (minimum 64, default 170)
#endif
// How many times to retry a failed stream connection before giving up
#ifndef MAX_STREAM_RETRIES
  #define MAX_STREAM_RETRIES 3
#endif
// Connection timeouts for socket connect/read (consumed by setConnectionTimeout() in player.cpp).
// Leave undefined for library defaults (250ms HTTP, 2700ms SSL), or define in myoptions.h.
#ifndef CONNECT_HTTP_HTTPS_TIMEOUT
  #define CONNECT_HTTP_HTTPS_TIMEOUT 1700, 3700
#endif
// Timeout in ms for receiving HTTP response headers (server redirects, slow streams).
// Separate from socket-level timeouts above and only includes final hop in redirects
#ifndef STREAM_TIMEOUT_MS
  #define STREAM_TIMEOUT_MS 3000
#endif

// PSRAM Frame Buffer
#ifndef USE_FBUFFER
  #define USE_FBUFFER true // framebuffer: best to leave this on (will use PSRAM if available and SRAM if not)
#endif

// PSRAM Buffers (highest-case estimates, in allocation order: display.init() → player.init() → netserver.begin())
//   Display framebuffer (480×320): ~74 KB  (allocated first, display.init())
//   VS1053 audio buffer:          ~293 KB  (300000 bytes, player.init())
//   I2S audio buffer:             ~640 KB  (UINT16_MAX * 10, player.init())
//   WebUI files cache:       up to 300 KB  (actually ~60KB if using .gz files, allocated last, netserver.begin(); dynamic, falls back to SPIFFS)
// ---------------------------------------
//   VS1053 total:                 ~667 KB  or ~427KB with .gz WebUI files
//   I2S total:                   ~1014 KB  or ~774KB with .gz WebUI files
// Note: WebUI cache is opportunistic so if PSRAM runs low, files stay in SPIFFS instead.

// Since the audio buffer can never technically fill up (most streams prevent reading-ahead excessively),
// the visual buffer bar should look "full" when the buffer is near to maximum potential (250KB is ~6 seconds at 320kbps)
// there is no 
#ifndef BUFFERBAR_VISUAL_FULL_KB
  #define BUFFERBAR_VISUAL_FULL_KB 250
#endif

/* --- CPU CORES --- */
/* ESP32 and ESP32-S3 have 2 cores (Main loop runs on Core 1). ESP32-C3 has 1 core (Main loop runs on Core 0) .*/
/* Default VS1053 assignments: Core 0 Audio + Net + TCP / Core 1 Main + Display */
/* Default I2S assignments: Core 0 Audio / Core 1 Main + Display + Net + TCP */
#if defined(CONFIG_FREERTOS_UNICORE) // will automatically activate on compiling for ESP32-C3 or other single-core ESPs
  #ifdef AUDIO_CORE
    #error Do not try to define AUDIO_CORE on a single-core ESP - it will be handled automatically!
  #else
    #define AUDIO_CORE 0
  #endif
#else // If not 1 Core, then define core processes
  #ifndef AUDIO_CORE
    #define AUDIO_CORE 0
  #endif
#endif
#if defined(CONFIG_FREERTOS_UNICORE)
  #ifdef NETWORK_CORE
    #error Do not try to define NETWORK_CORE on a single-core ESP - it will be handled automatically!
  #else
    #define NETWORK_CORE 0
  #endif
#else
  #ifndef NETWORK_CORE
    #if VS1053_CS!=255
      #define NETWORK_CORE 0
    #else
      #define NETWORK_CORE 1
    #endif
  #endif
#endif
#if defined(CONFIG_FREERTOS_UNICORE)
  #ifdef DSP_TASK_CORE_ID
    #error Do not try to define DSP_TASK_CORE_ID on a single-core ESP - it will be handled automatically!
  #else
    #define DSP_TASK_CORE_ID 0
  #endif
#else
  #ifndef DSP_TASK_CORE_ID
    #define DSP_TASK_CORE_ID 1
  #endif
#endif

/* --- TWEAKS FOR CORE PROCESSES --- */
/* Board-scaled stack size multiplier */
/* Applied automatically to FreeRTOS task stack defaults based on board SRAM capacity */
/* Override in myoptions.h only if needed: #define STACK_MULTIPLIER 1 to disable scaling on S3 */
/* Note: ESP32-C3 has LESS RAM than base ESP32 and defaults to 1x — same as base ESP32 */
#ifndef STACK_MULTIPLIER
  #if defined(ARDUINO_ESP32S3_DEV)
    #define STACK_MULTIPLIER 2 // ESP32-S3: double stack sizes (most SRAM available)
  #else
    #define STACK_MULTIPLIER 1 // ESP32 and ESP32-C3: conservative defaults
  #endif
#endif
#if STACK_MULTIPLIER != 1 && STACK_MULTIPLIER != 2
  #error define error in myoptions.h: STACK_MULTIPLIER must be 1 or 2
#endif

/* Stack sizes are in KB; conversion to bytes is done locally in each .cpp file via a _BYTES macro */
/* Delay values are in ms; pdMS_TO_TICKS() conversion is done locally in each .cpp file via a SET_ macro */
/* The straight number without multiplier is from yoRadio ESP32 defaults - ESP32-S3 uses the multiplier */
/* If working on an ESP32 or ESP32-C3 be warned that these numbers are actually untested and feedback is welcome! */

/* Arduino loop() task (main.cpp) — SET_LOOP_TASK_STACK_SIZE() uses this directly in bytes */
#ifndef LOOP_TASK_STACK_SIZE
  #define LOOP_TASK_STACK_SIZE (8 * STACK_MULTIPLIER) // KB; 8 (ESP32/C3) or 16 (S3)
#elif LOOP_TASK_STACK_SIZE < 4 || LOOP_TASK_STACK_SIZE > 64
  #error define error in myoptions.h: LOOP_TASK_STACK_SIZE must be between 4 and 64 (value in KB)
#endif

/* DspTask (display.cpp): render loop task */
#ifndef DSP_TASK_STACK_SIZE
  #define DSP_TASK_STACK_SIZE (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif DSP_TASK_STACK_SIZE < 2 || DSP_TASK_STACK_SIZE > 32
  #error define error in myoptions.h: DSP_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif
#ifndef DSP_TASK_DELAY
  #define DSP_TASK_DELAY 10 // ms; minimum sleep between display iterations. Actual frame rate depends on display SPI write time — typically ~50fps at slow SPI speeds, up to 100fps on faster displays
#endif
#ifndef DSP_QUEUE_TICKS
  #define DSP_QUEUE_TICKS 0 // ticks; xQueueReceive timeout inside display.loop(). 0 = non-blocking poll. Higher values (e.g. 5) reduce latency when queue is empty but are rarely needed; per-display conf files may override
#endif
#ifndef DSQ_SEND_DELAY
  #define DSQ_SEND_DELAY 200 // ms; xQueueSend timeout in display.putRequest(). If queue full, calling task blocks up to this long before dropping the request silently — preferable to blocking the audio task
#endif
#ifndef PLQ_SEND_DELAY
  #define PLQ_SEND_DELAY 100 // ms; xQueueSend timeout in player.sendCommand(). Short timeout prevents blocking audio decode while still absorbing brief queue pressure
#endif
#if defined(ARDUINO_ESP32S3_DEV) // Minimum allocation bytes; min free heap before spawning a background task (search, curated, playback, rb_click)
  #define MIN_MALLOC 24112 // ESP32-S3: known to be good, generous
#else
  #define MIN_MALLOC 12056 // ESP32 and ESP32-C3: tight...? good luck!
#endif

/* netserverLoopTask (netserver.cpp): runs netserver.loop() on its own pinned task */
#ifndef NETSERVER_TASK_STACK_SIZE
  #define NETSERVER_TASK_STACK_SIZE (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif NETSERVER_TASK_STACK_SIZE < 2 || NETSERVER_TASK_STACK_SIZE > 32
  #error define error in myoptions.h: NETSERVER_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif
#ifndef NETSERVER_TASK_DELAY
  #define NETSERVER_TASK_DELAY 1 // ms; yield between netserver.loop() iterations
#endif
#ifndef NSQ_SEND_DELAY
  #define NSQ_SEND_DELAY 300 // ms; xQueueSend timeout for nsQueue (requestOnChange). Use portMAX_DELAY to block indefinitely
#endif
#ifndef NS_QUEUE_DELAY
  #define NS_QUEUE_DELAY 0 // ms; xQueueReceive timeout for nsQueue (processQueue). 0 = non-blocking poll
#endif

/* Network utility tasks (network.cpp, player.cpp): doSync, searchWiFi, retryStreamConnection */
#ifndef NETWORK_TASK_STACK_SIZE
  #define NETWORK_TASK_STACK_SIZE (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif NETWORK_TASK_STACK_SIZE < 2 || NETWORK_TASK_STACK_SIZE > 32
  #error define error in myoptions.h: NETWORK_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif

/* Priority scale for all pinned tasks (FreeRTOS: higher number = more CPU, preempts lower tasks) */
/* Arduino loop() runs at priority 1. Priority 0 = idle-level (starved by any other task — do not use). */
#ifndef DSP_TASK_PRIORITY
  #define DSP_TASK_PRIORITY 2 // 2 = above Arduino loop() (1), below audio-critical tasks (3)
#endif
#ifndef NETSERVER_TASK_PRIORITY
  #define NETSERVER_TASK_PRIORITY 2 // 2 = above Arduino loop() (1), same tier as display
#endif
#ifndef NET_TASK_PRIORITY
  #define NET_TASK_PRIORITY 3 // highest: WiFi search, stream retry, OTA download
#endif
#ifndef PLAYBACK_TASK_PRIORITY
  #define PLAYBACK_TASK_PRIORITY 3 // highest: stream connection / playback start
#endif
#ifndef LOW_TASK_PRIORITY
  #define LOW_TASK_PRIORITY 1 // lowest: background/deferrable tasks (round-robin with loop())
#endif


/* --- LIBRARY OVERRIDES --- */
/* These are overrides for external libraries */
#ifndef CONFIG_ASYNC_TCP_QUEUE_SIZE
  #if defined(ARDUINO_ESP32S3_DEV)
    #define CONFIG_ASYNC_TCP_QUEUE_SIZE 64 // ESP32-S3: larger queue for higher network throughput
  #else
    #define CONFIG_ASYNC_TCP_QUEUE_SIZE 32 // ESP32 and ESP32-C3
  #endif
#endif
#ifndef CONFIG_ASYNC_TCP_RUNNING_CORE
  #define CONFIG_ASYNC_TCP_RUNNING_CORE NETWORK_CORE // -1 = any available core (NETWORK_CORE is default)
#endif
#ifndef CONFIG_ASYNC_TCP_USE_WDT
  #define CONFIG_ASYNC_TCP_USE_WDT 0 // 1 = watchdog enabled (adds between 33us and 200us per event)
#endif


/* ============================== SYSTEM DEFAULTS ============================== */

/* --- SOURCE OF UPDATE FILES --- */
/* only used if FIRMWARE is defined as it is in Trip5's automatic Github builds */
#ifndef GITHUBURL
  #define GITHUBURL "https://github.com/trip5/ehradio" // used by the ESPFileUpdater in BrowserClient (and in URLs below)
#endif

#ifdef ENABLE_UPDATER // if this is defined, enables online updates
  #ifndef FIRMWARE // this is the filename.bin online
    #error ENABLE_UPDATER defined but FIRMWARE is not
  #endif
  // #define FIRMWARE_NAME "Trip5's Big Screen Radio" optional name of the firmware (appears only in eh Device Protocol and will appear as the filename (without .bin) by default if not defined)
  #ifndef FILESURL
    #define FILESURL GITHUBURL "/releases/download/" RADIOVERSION "/" // + FILE for SPIFFS files (this version)
  #endif
  #ifndef UPDATEURL
    #define UPDATEURL GITHUBURL "/releases/latest/download/" // + FIRMWARE for the file
  #endif
  #ifndef CHECKUPDATEURL
    #define CHECKUPDATEURL GITHUBURL "/releases/latest/download/version.txt" // automatically extracted from options.h during Github workflow
  #endif
  #ifndef VERSIONSTRING
    #define VERSIONSTRING "ehRadio Version" // the file above should have a line that starts with this followed by a version number
  #endif
  #ifndef CHECKUPDATEURL_TIME
    #define CHECKUPDATEURL_TIME "1 day"
  #endif
#else
  #undef FILESURL
  #undef UPDATEURL
  #undef CHECKUPDATEURL
  #undef VERSIONSTRING
  #undef CHECKUPDATEURL_TIME
#endif

/* --- SOURCE OF JSON FILES --- */
#ifndef TIMEZONES_JSON_URL
  #define TIMEZONES_JSON_URL "https://raw.githubusercontent.com/trip5/timezones.json/master/timezones.json.gz"
#endif
#ifndef TIMEZONES_JSON_CHECKTIME
  #define TIMEZONES_JSON_CHECKTIME "4 weeks"
#endif
#ifndef RADIO_BROWSER_SERVERS_URL 
  #define RADIO_BROWSER_SERVERS_URL "https://all.api.radio-browser.info/json/servers"
#endif
#ifndef RB_SERVERS_CHECKTIME
  #define RB_SERVERS_CHECKTIME "1 day"
#endif

/* --- SOURCE OF CURATED PLAYLISTS --- */
#ifndef CURATED_LISTS
  #define CURATED_LISTS "Trip5's webstations"
  #ifndef CURATED_LISTS_LINK
    #define CURATED_LISTS_LINK "https://github.com/trip5/webstations"
  #endif
  #ifndef CURATED_LISTS_URL
    #define CURATED_LISTS_URL "https://github.com/trip5/webstations/releases/latest/download/"
  #endif
  #ifndef CURATED_LISTS_INDEX
    #define CURATED_LISTS_INDEX "index.json"
  #endif
#else
  #if !defined(CURATED_LISTS_LINK) || !defined(CURATED_LISTS_URL) || !defined(CURATED_LISTS_INDEX)
    #undef CURATED_LISTS
    #undef CURATED_LISTS_LINK
    #undef CURATED_LISTS_URL
    #undef CURATED_LISTS_INDEX
  #endif
#endif

// Is the hardcoded text in the HTML files not English?  If yes, then you should override this
// OVERRIDE WITH EXTREME CAUTION !!!  You must prepare the HTML files with hardcode_locale_to_html.py
#ifndef HARDCODED_WEBUI_LOCALE
  #define HARDCODED_WEBUI_LOCALE "en_US"
#endif

/* --- RADIO BROWSER API SERVER --- */
/* Used as fallback for search and primary for sending clicks */
#ifndef RADIO_BROWSER_SERVER
  #define RADIO_BROWSER_SERVER "all.api.radio-browser.info"
#endif
/* Opt-out sending clicks to Radio-browser API with #define RADIO_BROWSER_NO_SEND_CLICKS */
#ifndef RADIO_BROWSER_NO_SEND_CLICKS
  #ifndef RADIO_BROWSER_SEND_CLICKS
    #define RADIO_BROWSER_SEND_CLICKS
  #endif
  #ifndef RADIO_BROWSER_SEND_CLICK_DELAY
    #define RADIO_BROWSER_SEND_CLICK_DELAY 10000 // wait 10 seconds before sending the click
  #endif
#else
  #undef RADIO_BROWSER_SEND_CLICKS
#endif

/* --- OTHER COMPILE OPTIONS --- */
/*  Here are other #defines that may be added to myoptions.h   */
#ifdef MQTT_ENABLE
 // This enables MQTT. A nice option to have but not available in the code without this #define in myoptions.h
#endif
#ifdef PLAYLIST_DEFAULT_URL
 // This will download a playlist when first-booting and no playlist is present on SPIFFS.  Can be CSV or JSON format.  Example:
 // #define PLAYLIST_DEFAULT_URL "https://github.com/trip5/webstations/releases/latest/download/trip5-radio-playlist.csv"
#endif
#ifndef SCREENSAVERSTARTUPDELAY // initial delay
  #define SCREENSAVERSTARTUPDELAY 5
#endif
#ifndef SCREENSAVERMOVE // how often to move the screensaver (in seconds)
  #define SCREENSAVERMOVE 15
#endif
#ifndef HEADER_TIMEOUT
  #define HEADER_TIMEOUT 5000
#endif
#ifndef USE_OTA // define true to enable Arduino OTA
  #define USE_OTA false
#endif
#ifdef OTA_PASS
  //#define OTA_PASS "myotapassword12345"
#endif
#ifndef AP_SSID // name of hotspot in AP Mode
  #define AP_SSID "ehRadio"
#endif
#ifdef AP_PASSWORD
  #if (AP_PASSWORD)[0] == '\0' // if it's empty, undefine
    #undef AP_PASSWORD
  #endif
#endif

/* This bit will actually do something but needs to be handled a different way - configurable would be better */
/* But I'm very concerned that a forgotten password means needing a way to factory-reset using hardware... */
/* So this may never actually be implemented in a proper way */
//#define HTTP_USER "user"
//#define HTTP_PASS "password"
/* It was left here by e2002 for yoRadio and just never moved */
/* Thank you for reading, by the way */
/* And thank you to e2002 for making yoRadio */


/* ============================== DEBUG ============================== */

/* Enable all the debug logs with #define ALL_DEBUG_LOGS */
/* BATTERY_DEBUG is included elsewhere */
#ifdef ALL_DEBUG_LOGS
  #ifndef ESPFILEUPDATER_DEBUG
    #define ESPFILEUPDATER_DEBUG // This enables ESPFileUpdater's debug log in serial.  Only add if you really want to watch serial log for what may be causing fetch errors.
  #endif
  #ifndef NETSERVER_DEBUG
   #define NETSERVER_DEBUG // This enables Netserver logging: GET client requests and sending files in chunks
  #endif
  #ifndef CORE_MONITOR
    #define CORE_MONITOR // This shows the ESP32 CPU Core Monitor in serial and telnet (updated every 5s), includes SPIFFS information
  #endif
  #ifndef CORE_MONITOR_ETC_LOOPS
    #define CORE_MONITOR_ETC_LOOPS 5 // Show SPIFFS + PSRAM info every N core monitor cycles (default: 5, every 25s)
  #endif
  #ifdef WIDGET_DEBUG
    #define WIDGET_DEBUG // This shows the Widget's Text in logging.  It's extremely noisy.
  #endif
#endif
#ifdef CORS_DEBUG
 // This enables CORS policy: 'Access-Control-Allow-Origin' (for testing)
#endif

/* CPU CORE NAMES: Name the Cores for what they do... */
/* Do not use any of these macros directly in myoptions.h! */
/* Use #define CORE_MONITOR to show how busy the cores are... this gives them friendly names */
#if !CONFIG_FREERTOS_UNICORE && defined(CORE_MONITOR)
  #if AUDIO_CORE==0
    #define CORE_0A "Audio"
    #define CORE_1A ""
  #elif AUDIO_CORE==1
    #define CORE_0A ""
    #define CORE_1A "+Audio"
  #endif
  #if NETWORK_CORE==0
    #if AUDIO_CORE==0
      #define CORE_0B "+Net"
    #else
      #define CORE_0B "Net"
    #endif
    #define CORE_1B ""
  #elif NETWORK_CORE==1
    #define CORE_0B ""
    #define CORE_1B "+Net"
  #endif
  #if CONFIG_ASYNC_TCP_RUNNING_CORE==0
    #if AUDIO_CORE==0 || NETWORK_CORE==0
      #define CORE_0C "+TCP"
    #else
      #define CORE_0C "TCP"
    #endif
    #define CORE_1C ""
  #elif CONFIG_ASYNC_TCP_RUNNING_CORE==1
    #define CORE_0C ""
    #define CORE_1C "+TCP"
  #endif
  #if DSP_TASK_CORE_ID==0
    #if AUDIO_CORE==0 || NETWORK_CORE==0 || CONFIG_ASYNC_TCP_RUNNING_CORE==0
      #define CORE_0D "+Disp"
    #else
      #define CORE_0D "Disp"
    #endif
    #define CORE_1D ""
  #elif DSP_TASK_CORE_ID==1
    #define CORE_0D ""
    #define CORE_1D "+Disp"
  #endif
  #define CORE_0 "(" CORE_0A CORE_0B CORE_0C CORE_0D ")"
  #define CORE_1 "(Main" CORE_1A CORE_1B CORE_1C CORE_1D ")"
#endif

/* ============================== BATTERY ============================== */
#ifndef BATTERY_PIN
  #define BATTERY_PIN 255 // GPIO pin for battery voltage ADC reading
#endif
#ifndef BATTERY_CHARGE_PIN
  #define BATTERY_CHARGE_PIN 255 // GPIO pin for charging status (TP4054 CHRG pin, active LOW)
#endif
#ifndef BATTERY_DIVIDER_RATIO
  #define BATTERY_DIVIDER_RATIO 2.0 // Voltage divider ratio (battery voltage / ADC voltage)
#endif
#ifndef BATTERY_ADC_REF_MV
  #define BATTERY_ADC_REF_MV 3300 // ADC reference voltage in millivolts
#endif
#ifndef BATTERY_UPDATE_INTERVAL
  #define BATTERY_UPDATE_INTERVAL 5 // Update interval in seconds
#endif
#ifndef BATTERY_SAMPLES
  #define BATTERY_SAMPLES 10 // Number of ADC samples to average
#endif
#ifndef BATTERY_DIM_BRIGHTNESS
  #define BATTERY_DIM_BRIGHTNESS 20 // Battery dim fixed brightness when LOW battery (percentage 0-100)
#endif
#if (BATTERY_DIM_BRIGHTNESS < 0) || (BATTERY_DIM_BRIGHTNESS > 100)
  #error define error in myoptions.h: BATTERY_DIM_BRIGHTNESS must be a percentage between 0 and 100
#endif
#ifndef BATTERY_RECOVER_HYSTERESIS_PCT
  #define BATTERY_RECOVER_HYSTERESIS_PCT 5 // Hysteresis for recovering from low-battery dimming (percent)
#endif
/* Inference tuning defaults: control sensitivity for charging/discharging detection. */
#ifndef BATTERY_CHARGE_INFER_HOLD_SAMPLES
  #define BATTERY_CHARGE_INFER_HOLD_SAMPLES 3 // number of measurements (samples) to hold (e.g., 3 readings)
#endif
#ifndef BATTERY_IMMEDIATE_PERCENT_THRESHOLD
  #define BATTERY_IMMEDIATE_PERCENT_THRESHOLD 3 // percent; immediate single-reading threshold
#endif
#ifndef BATTERY_CANDIDATE_PERCENT_DELTA
  #define BATTERY_CANDIDATE_PERCENT_DELTA 1 // percent; minimal delta to start a candidate
#endif
#ifndef BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD
  #define BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD 0 // percent over hold window required to confirm
#endif
/* Battery presence detection (mV) - default single-cell LiPo safe range. */
#ifndef BATTERY_PRESENT_MIN_MV
  #define BATTERY_PRESENT_MIN_MV 3000 // Minimum battery voltage (mV) considered present (single-cell LiPo)
#endif
#ifndef BATTERY_PRESENT_MAX_MV
  #define BATTERY_PRESENT_MAX_MV 4300 // Maximum battery voltage (mV) considered present (single-cell LiPo)
#endif
/* Battery discharge curve defaults (mV -> percent). */
#ifndef BATTERY_CURVE_MV
  #define BATTERY_CURVE_MV 4240, 4100, 4000, 3900, 3800, 3700, 3600, 3400, 3200
#endif
#ifndef BATTERY_CURVE_PCT
  #define BATTERY_CURVE_PCT 100, 95, 90, 80, 70, 55, 30, 10, 0
#endif
#ifndef BATTERY_LOW_THRESHOLD
  #define BATTERY_LOW_THRESHOLD 25 // Low battery warning threshold (percentage, 0-100)
#endif
#if (BATTERY_LOW_THRESHOLD < 0) || (BATTERY_LOW_THRESHOLD > 100)
  #error define error in myoptions.h: BATTERY_LOW_THRESHOLD must be a percentage between 0 and 100
#endif
#ifndef BATTERY_CRITICAL_THRESHOLD
  #define BATTERY_CRITICAL_THRESHOLD 5 // Critical battery threshold (percentage, 0-100)
#endif
#if BATTERY_CRITICAL_THRESHOLD < 0 || BATTERY_CRITICAL_THRESHOLD > 100
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be a percentage between 0 and 100
#endif
#if BATTERY_CRITICAL_THRESHOLD >= BATTERY_LOW_THRESHOLD
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be less than BATTERY_LOW_THRESHOLD
#endif
#ifdef BATTERY_DEBUG
 // if defined enables full information about battery in serial log
#endif


/* ============================== USER DEFAULTS ============================== */
/* Sets defaults but still editable in WebUI */

#if defined(SOUND_VOLUME) && (SOUND_VOLUME < 0 || SOUND_VOLUME > VOLUME_SCALE)
  #warning "define warning in myoptions.h: SOUND_VOLUME is out of range (0-" #VOLUME_SCALE "), reverting to a safe default"
  #undef SOUND_VOLUME
#endif
#ifndef SOUND_VOLUME
  #define SOUND_VOLUME (VOLUME_SCALE / 21 * 9) // a little below middle
#endif
#if defined(SOUND_BALANCE) && (SOUND_BALANCE < -16 || SOUND_BALANCE > 16)
  #warning "define warning in myoptions.h: SOUND_BALANCE is out of range (-16 to 16), reverting to default 0"
  #undef SOUND_BALANCE
#endif
#ifndef SOUND_BALANCE
  #define SOUND_BALANCE 0
#endif
#if defined(EQ_TREBLE) && (EQ_TREBLE < -16 || EQ_TREBLE > 16)
  #warning "define warning in myoptions.h: EQ_TREBLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_TREBLE
#endif
#ifndef EQ_TREBLE
  #define EQ_TREBLE 0
#endif
#if defined(EQ_MIDDLE) && (EQ_MIDDLE < -16 || EQ_MIDDLE > 16)
  #warning "define warning in myoptions.h: EQ_MIDDLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_MIDDLE
#endif
#ifndef EQ_MIDDLE
  #define EQ_MIDDLE 0
#endif
#if defined(EQ_BASS) && (EQ_BASS < -16 || EQ_BASS > 16)
  #warning "define warning in myoptions.h: EQ_BASS is out of range (-16 to 16), reverting to default 0"
  #undef EQ_BASS
#endif
#ifndef EQ_BASS
  #define EQ_BASS 0
#endif
#ifndef SD_SHUFFLE
  #define SD_SHUFFLE false
#endif
#ifndef SMART_START
  #define SMART_START true
#endif
#ifndef SHOW_BUFFERBAR
  #define SHOW_BUFFERBAR false
#endif
#ifndef SHOW_VU_METER
  #define SHOW_VU_METER false
#endif
#ifndef WIFI_SCAN_BEST_RSSI
  #define WIFI_SCAN_BEST_RSSI true
#endif
#ifndef EHDP
  #define EHDP true
#endif
#if defined(SOFTAP_REBOOT_DELAY) && ((SOFTAP_REBOOT_DELAY < 0) || (SOFTAP_REBOOT_DELAY > 20))
  #warning "define warning in myoptions.h: SOFTAP_REBOOT_DELAY is out of range (0-20), reverting to default 0"
  #undef SOFTAP_REBOOT_DELAY
#endif
#ifndef SOFTAP_REBOOT_DELAY
  #define SOFTAP_REBOOT_DELAY 0
#endif
#ifndef SCREEN_FLIP
  #define SCREEN_FLIP false
#endif
#ifndef SCREEN_INVERT
  #define SCREEN_INVERT false
#endif
#ifndef INVERT_TITLE
  #ifdef DSP_OLED // from dspcore.h - OLEDS look better with this mode on
    #define INVERT_TITLE true
  #else
    #define INVERT_TITLE false
  #endif
#endif
#ifndef NUMBERED_PLAYLIST
  #define NUMBERED_PLAYLIST false
#endif
#ifndef CLOCK_TWELVE
  #define CLOCK_TWELVE false
#endif
#ifndef VOLUME_PAGE
  #define VOLUME_PAGE false
#endif
#if defined(SCREEN_BRIGHTNESS) && (SCREEN_BRIGHTNESS < 1 || SCREEN_BRIGHTNESS > 100)
  #warning "define warning in myoptions.h: SCREEN_BRIGHTNESS is out of range (1-100), reverting to default 100"
  #undef SCREEN_BRIGHTNESS
#endif
#ifndef SCREEN_BRIGHTNESS
  #define SCREEN_BRIGHTNESS 100
#endif
#if defined(SCREEN_CONTRAST) && (SCREEN_CONTRAST < 1 || SCREEN_CONTRAST > 100)
  #warning "define warning in myoptions.h: SCREEN_CONTRAST is out of range (1-100), reverting to default 55"
  #undef SCREEN_CONTRAST
#endif
#ifndef SCREEN_CONTRAST
  #define SCREEN_CONTRAST 55
#endif
#ifndef SS_NOTPLAYING
  #define SS_NOTPLAYING false
#endif
#ifndef SS_NOTPLAYING_BLANK
  #define SS_NOTPLAYING_BLANK false
#endif
#if defined(SS_NOTPLAYING_TIME) && (SS_NOTPLAYING_TIME < 5 || SS_NOTPLAYING_TIME > 65520)
  #warning "define warning in myoptions.h: SS_NOTPLAYING_TIME is out of range (5-65520), reverting to default 120"
  #undef SS_NOTPLAYING_TIME
#endif
#ifndef SS_NOTPLAYING_TIME
  #define SS_NOTPLAYING_TIME 120
#endif
#ifndef SS_PLAYING
  #define SS_PLAYING false
#endif
#ifndef SS_PLAYING_BLANK
  #define SS_PLAYING_BLANK false
#endif
#if defined(SS_PLAYING_TIME) && (SS_PLAYING_TIME < 1 || SS_PLAYING_TIME > 1080)
  #warning "define warning in myoptions.h: SS_PLAYING_TIME is out of range (1-1080), reverting to default 5"
  #undef SS_PLAYING_TIME
#endif
#ifndef SS_PLAYING_TIME
  #define SS_PLAYING_TIME 5
#endif
#ifndef SS_FULL_DATETIME
  #define SS_FULL_DATETIME false
#endif
#ifndef DIMMING_ENABLED
    #define DIMMING_ENABLED false
#endif  
#if defined(DIMMING_TIMEOUT) && (DIMMING_TIMEOUT < 5 || DIMMING_TIMEOUT > 65520)
  #warning "define warning in myoptions.h: DIMMING_TIMEOUT is out of range (5-65520), reverting to default 120"
  #undef DIMMING_TIMEOUT
#endif
#ifndef DIMMING_TIMEOUT
  #define DIMMING_TIMEOUT 120
#endif
#if defined(DIMMING_BRIGHTNESS) && (DIMMING_BRIGHTNESS < 0 || DIMMING_BRIGHTNESS > 100)
  #warning "define warning in myoptions.h: DIMMING_BRIGHTNESS is out of range (0-100), reverting to default 50"
  #undef DIMMING_BRIGHTNESS
#elif defined(DIMMING_BRIGHTNESS) && DIMMING_BRIGHTNESS < SCREEN_BRIGHTNESS
  #warning "define warning in myoptions.h: DIMMING_BRIGHTNESS is less than SCREEN_BRIGHTNESS, reverting to default 50 and 100"
  #undef SCREEN_BRIGHTNESS
  #undef DIMMING_BRIGHTNESS
  #define SCREEN_BRIGHTNESS 100
#endif
#ifndef DIMMING_BRIGHTNESS
  #define DIMMING_BRIGHTNESS 50
#endif
#ifndef TOUCH_FLIP
  #define TOUCH_FLIP false
#endif
#ifndef TOUCH_DEBUG
  #define TOUCH_DEBUG false
#endif
#if defined(ROTARY_ACCEL) && (ROTARY_ACCEL < 0 || ROTARY_ACCEL > 7)
  #warning "define warning in myoptions.h: ROTARY_ACCEL is out of range (0-7), reverting to default 2"
  #undef ROTARY_ACCEL
#endif
#ifndef ROTARY_ACCEL
  #define ROTARY_ACCEL 2
#endif
#ifndef ONE_CLICK_SWITCH
  #define ONE_CLICK_SWITCH false
#endif
#if defined(IR_TOLERANCE) && (IR_TOLERANCE < 10 || IR_TOLERANCE > 80)
  #warning "define warning in myoptions.h: IR_TOLERANCE is out of range (10-80), reverting to default 35"
  #undef IR_TOLERANCE
#endif
#ifndef IR_TOLERANCE
  #define IR_TOLERANCE 35
#endif
// The Display Locale is changeable!  (Check locale/dsplocales.json for full list)
#ifndef DSP_LOCALE
  #define DSP_LOCALE "en_US"
#endif
// WebUI locale which can differ from display locale (check locale/locales.json for full list)
#ifndef WEBUI_LOCALE
  #define WEBUI_LOCALE DSP_LOCALE // use the same as display by default
#endif
// OpenWeatherMap API requires its own language code https://openweathermap.org/current?collection=current_forecast#multi
#ifndef WEATHER_LANG_OWM
  #define WEATHER_LANG_OWM "en"
#endif
#ifndef TIMEZONE_NAME
  #define TIMEZONE_NAME "Canada/Atlantic"
#endif
#ifndef TIMEZONE_POSIX
  #define TIMEZONE_POSIX "AST4ADT,M3.2.0,M11.1.0"
#endif
#ifndef SNTP_1
  #define SNTP_1 "0.pool.ntp.or"
#endif
#ifndef SNTP_2
  #define SNTP_2 "pool.ntp.org"
#endif
#ifndef TIME_SYNC_INTERVAL // hours
  #if RTCSUPPORTED
    #define TIME_SYNC_INTERVAL 8
  #else
    #define TIME_SYNC_INTERVAL 1
  #endif
#endif
#if TIME_SYNC_INTERVAL < 1 || TIME_SYNC_INTERVAL > 24
  #error define error in myoptions.h: TIME_SYNC_INTERVAL must be a number from 1 to 24 (hours)
#endif
#ifndef WEATHER_API
  #define WEATHER_API "OM1"
#endif
static_assert(
  __builtin_strcmp(WEATHER_API, "OM1")  == 0 ||
  __builtin_strcmp(WEATHER_API, "OW25") == 0 ||
  __builtin_strcmp(WEATHER_API, "OW30") == 0,
  "define error in myoptions.h: WEATHER_API must be \"OM1\", \"OW25\", or \"OW30\""
);
#ifndef WEATHER_LAT
  #define WEATHER_LAT "44.64738"
#endif
#ifndef WEATHER_LON
  #define WEATHER_LON "-63.58029"
#endif
#ifndef WEATHER_SYNC_INTERVAL // minutes
  #define WEATHER_SYNC_INTERVAL 15
#endif
#if WEATHER_SYNC_INTERVAL < 10 || WEATHER_SYNC_INTERVAL > 60
  #error define error in myoptions.h: WEATHER_SYNC_INTERVAL must be a number from 10 to 60 (minutes)
#endif
/* Most of the world uses Metric but you can override in myoptions.h */
#ifndef WEATHER_METRIC
  #define WEATHER_METRIC true
#endif
/* The exact units can also be over-ridden in myoptions.h */
/* valid choices for wind speed are "kph" (km/h), "mph", "ms" (m/s), "kn" (knots) */
#if WEATHER_METRIC
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F false
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG false
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "kmh"
  #endif
#else
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F true
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG true
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "mph"
  #endif
#endif
static_assert(
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kmh") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "mph") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kn")  == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "m/s") == 0,
  "define error in myoptions.h: WEATHER_WIND_SPEED_UNITS must be \"kmh\", \"mph\", \"kn\", or \"m/s\""
);
#ifndef MQTT_HOST
  #define MQTT_HOST "192.168.1.2"
#endif
#ifndef MQTT_PORT
  #define MQTT_PORT 1883
#endif
#ifndef MQTT_USER
  #define MQTT_USER "mqttuser"
#endif
#ifndef MQTT_PASS
  #define MQTT_PASS ""
#endif
#ifndef MQTT_TOPIC
  #define MQTT_TOPIC "ehradio/myradio/"
#endif

#endif // options_h
