#ifndef options_h
#define options_h
#pragma once

#define RADIOVERSION "2026.05.19"

/*******************************************************
THIS FILE IS THE DEFINITIVE HANDLER OF COMPILE OPTIONS.
Most macros used in the codebase are here somewhere.
There are notes and options and examples that can be
used in myoptions.h when compiling.

                                   DO NOT EDIT THIS FILE!

myoptions.h should exist in the root folder.
Examine the examples in builds/trip5 and make your own!
Read other notes in builds/ for more details regarding how
to build your own and contribute your own myoptions.h!
You may also create your own mytheme.h in the root folder.

Locales are guarded seperately in locale.h so check
that file if you need non-English language options.
********************************************************/

#if __has_include("../../myoptions.h")
  #include "../../myoptions.h" // write your variable values here
#endif
#if __has_include("../../mytheme.h")
  #include "../../mytheme.h" // Theme file
#endif

#if !(defined(ARDUINO_ESP32_DEV) || defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV))
  #error define error in platformio.ini: only ARDUINO_ESP32_DEV, ARDUINO_ESP32S3_DEV, or ARDUINO_ESP32C3_DEV boards are supported
#endif


/*******************************************************
Use this tool to setup connections:
https://trip5.github.io/ehRadio/myoptions/generator.html
(a basic tool and not definitive for all possible configurations)
********************************************************/


/* ============================== DISPLAY ============================== */

/* --- DISPLAYS ENUM --- */

#define DSP_DUMMY       0 // without display
#define DSP_ST7735      1 // 160x128  1.8"  or 128x128  1.44"  or 160x80   0.96"  https://aliexpress.com/item/1005002822797745.html
#define DSP_SSD1306     2 // 128x64   0.96" https://aliexpress.com/item/1005001621806398.html
#define DSP_NOKIA5110   3 // 84x48    1.6"  https://aliexpress.com/item/1005001621837569.html
#define DSP_ST7789      4 // 320x240  2.4"  https://aliexpress.com/item/32960241206.html 
#define DSP_SH1106      5 // 128x64   1.3"  https://aliexpress.com/item/32683094040.html
#define DSP_1602I2C     6 // 16x2           https://aliexpress.com/item/32305776560.html
#define DSP_SSD1306x32  7 // 128x32   0.91" https://aliexpress.com/item/32798439084.html
#define DSP_SSD1327     8 // 128x128  1.5"  https://aliexpress.com/item/1005001414175498.html
#define DSP_ILI9341     9 // 320x240  3.2"  https://aliexpress.com/item/33048191074.html
#define DSP_SSD1305     10 // 128x64   2.4"  SSD1305 and SSD1309 SPI https://aliexpress.com/item/32950307344.html
#define DSP_SH1107      11 // 128x64   1.3"  https://aliexpress.com/item/4000551696674.html
#define DSP_1602        12 // 16x2           https://aliexpress.com/item/32685016568.html
#define DSP_GC9106      13 // 160x80   0.96" (looks like ST7735S, but it"s not him) https://aliexpress.com/item/32947890530.html
#define DSP_2004I2C     14 // 20x4           https://aliexpress.com/item/32783128355.html
#define DSP_2004        15 // 20x4           https://aliexpress.com/item/32783128355.html
#define DSP_SSD1305I2C  16 // 128x64   2.4"  SSD1305 and SSD1309 I2C https://aliexpress.com/item/32950307344.html
#define DSP_ILI9225     17 // 220x176  2.0"  https://aliexpress.com/item/32952021835.html
#define DSP_ST7789_240  18 // 240x240  1.3"  https://aliexpress.com/item/32996979276.html
/* !!! DSP_ST7789_240 requires further development when used in conjunction with the VS1053 module !!! See the link https://www.instructables.com/Adding-CS-Pin-to-13-LCD/ */
#define DSP_ST7796      19 // 480x320  3.5"  https://aliexpress.com/item/1005004632953455.html?sku_id=12000029911293172
#define DSP_GC9A01A     20 // 240x240  1.28" https://aliexpress.com/item/1005004069703494.html?sku_id=12000029869654615
#define DSP_ILI9488     21 // 480x320  3.5"  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356570
#define DSP_ILI9486     22 // (Testing mode) 480x320  3.5"  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356568
#define DSP_SSD1322     23 // 256x64   2.8"  https://aliexpress.com/item/1005003480981568.html
#define DSP_ST7920      24 // 128x64   2.6"  https://aliexpress.com/item/32699482638.html
#define DSP_ST7789_76   25 // 284x76 2.25"   https://aliexpress.ru/item/1005009016973081.html
#define DSP_CUSTOM      101 // your display

/* Define your display as #define DSP_MODEL DSP_ILI9488 */
#ifndef DSP_MODEL
  #define DSP_MODEL DSP_DUMMY
#endif
#if DSP_MODEL==DSP_DUMMY
  #define DUMMYDISPLAY
#endif

/* --- TFT DISPLAY --- */
/* SPI displays always use SPIA bus by default (see below for more) */
#ifndef TFT_CS
  #define TFT_CS 255
#endif
#ifndef TFT_RST
  #define TFT_RST -1 // Or set to -1 and connect to Esp EN pin
#endif
#ifndef TFT_DC
  #define TFT_DC 255
#endif
#ifndef USE_FBUFFER
  #define USE_FBUFFER true
#endif
#ifndef FULL_SCR_CLOCK
  #define FULL_SCR_CLOCK true
#endif

/* ST7735 display submodel */
// INITR_BLACKTAB // 1.8" https://aliexpress.ru/item/1005002822797745.html
//     See this note If INITR_BLACKTAB have a noisy line on one side of the screen https://github.com/e2002/yoradio#note-if-initr_blacktab-dsp-have-a-noisy-line-on-one-side-of-the-screen-then-in-adafruit_st7735cpp
// INITR_144GREENTAB // 1.44" https://aliexpress.ru/item/1005002822797745.html
// INITR_MINI160x80 // 0.96" 160x80 ST7735S   https://????
// INITR_GREENTAB
// INITR_REDTAB
#ifndef DTYPE
  #define DTYPE INITR_BLACKTAB
#endif

/* --- I2C DISPLAY PINS --- */
#ifndef I2C_SDA
  #define I2C_SDA 255 // Defaults: ESP32 21, ESP32-S3 8
#endif
#ifndef I2C_SCL
  #define I2C_SCL 255 // Defaults: ESP32 22, ESP32-S3 9
#endif
#ifndef I2C_RST
  #define I2C_RST -1 // -1 means not used
#endif

/* --- LCD DISPLAY PINS --- */
#ifndef LCD_RS
  #define LCD_RS 255
#endif
#ifndef LCD_E
  #define LCD_E 255
#endif
#ifndef LCD_D4
  #define LCD_D4 255
#endif
#ifndef LCD_D5
  #define LCD_D5 255
#endif
#ifndef LCD_D6
  #define LCD_D6 255
#endif
#ifndef LCD_D7
  #define LCD_D7 255
#endif

/* --- DISPLAY OPTIONS --- */
#ifndef ROTATE_90
  #define ROTATE_90 false // Optional 90 degree rotation for square displays
#endif
#ifndef BRIGHTNESS_PIN
  #define BRIGHTNESS_PIN 255 // BRIGHTNESS Pin
#endif

/* Can the display be dimmed? If it is set to true but the Brightness Pin is not set... */
/* This enables / disables the ability, not the default option DIMMING_ENABLED */

#if defined(DSP_DIMMING_ENABLED) && DSP_DIMMING_ENABLED && BRIGHTNESS_PIN==255
  #warning DSP_DIMMING_ENABLED is true but BRIGHTNESS_PIN is not set so setting DSP_DIMMING_ENABLED false
  #undef DSP_DIMMING_ENABLED
#endif
#ifndef DSP_DIMMING_ENABLED
    #define DSP_DIMMING_ENABLED false
#endif  

#ifndef LIGHT_SENSOR
  #define LIGHT_SENSOR 255 // Light sensor
#endif
#ifndef AUTOBACKLIGHT // Auto-dimming with the light sensor (not related to DSP_DIMMING_ENABLED)
  #ifndef AUTOBACKLIGHT_MAX
    #define AUTOBACKLIGHT_MAX 2500
  #endif
  #ifndef AUTOBACKLIGHT_MIN
    #define AUTOBACKLIGHT_MIN 12
  #endif
  #define AUTOBACKLIGHT(x) ({uint16_t _lh=(x>AUTOBACKLIGHT_MAX?AUTOBACKLIGHT_MAX:x); map(_lh, AUTOBACKLIGHT_MAX, 0, AUTOBACKLIGHT_MIN, 100);}) // autobacklight function
#endif

/* --- DISPLAY TRANSFORM --- */

#ifndef DSP_INVERT_QUIRK
  #define DSP_INVERT_QUIRK false // if a display shows inverted colors by default, override it by setting this to true
#endif
#ifndef DSP_INVERT_TITLE
  #define DSP_INVERT_TITLE true // Invert title colors for displays
#endif
#ifndef RSSI_DIGIT
  #define RSSI_DIGIT false // display RSSI as number
#endif
#ifndef RSSI_STEPS
  #define RSSI_STEPS -50,-60,-70,-80
#endif
#ifndef CLOCKFONT_MONO
  #define CLOCKFONT_MONO true // monospace clock font
#endif
#ifndef BITRATE_FULL
  #define BITRATE_FULL true // display bitrate badge
#endif

/* Use #define #BIG_BOOT_LOGO with 480x320 displays if you want a bigger boot logo */
#ifdef BIG_BOOT_LOGO
  #if (DSP_MODEL!=DSP_ST7796 && DSP_MODEL!=DSP_ILI9488 && DSP_MODEL!=DSP_ILI9486)
    #warning Your display may handle BIG_BOOT_LOGO badly!
  #endif
#endif


/* ============================== SPI BUSES AND PINS ============================== */

/* To allow multiple devices to use the same/different SPI buses, we name them */
/* VSPI is patched to FSPI for third-party library compatibility on ESP32-S3/C3 (Adafruit etc.) */
#include <SPI.h>
#if !defined(CONFIG_IDF_TARGET_ESP32)
  #define VSPI FSPI
#endif

/* --- NAMED SPI BUSES --- */
/* Two hardware SPI buses are available (Bus A = &SPI default, Bus B = secondary). */

/* Bus A/Primary SPI Bus (&SPI default) is important to use default pins (but can be overridden if needed) */
/* Define all manually or use shorthand #define SPIA_DEFAULT to use defaults */
/* For displays that do not use MISO, use shorthand #define SPIA_DEFAULT_XMISO */
#if defined(SPIA_DEFAULT) || defined(SPIA_DEFAULT_XMISO)
  #if !defined(SPIA_SCK) && !defined(SPIA_MISO) && !defined(SPIA_MOSI)
    #if defined(CONFIG_IDF_TARGET_ESP32) // ESP32 default VSPI/SPI3
      #define SPIA_SCK 18
      #define SPIA_MISO 19
      #define SPIA_MOSI 23
    #elif defined(CONFIG_IDF_TARGET_ESP32S3) // ESP32-S3 default FSPI/SPI2
      #define SPIA_SCK 12
      #define SPIA_MISO 13
      #define SPIA_MOSI 11
    #elif defined(CONFIG_IDF_TARGET_ESP32C3) // ESP32-C3 default FSPI/SPI2
      #define SPIA_SCK 4
      #define SPIA_MISO 5
      #define SPIA_MOSI 6
    #endif
	  #if defined(SPIA_DEFAULT_XMISO)
      #undef SPIA_MISO
      #define SPIA_MISO 255 // unused (most SPI displays)
    #endif
  #endif
#endif

/* Bus B / Secondary SPI Bus is less-important to use default pins (and may not be needed at all) */
/* Nevertheless, shorthand #define SPIB_DEFAULT may be used to set defaults */
#if defined(SPIB_DEFAULT)
  #if !defined(SPIB_SCK) && !defined(SPIB_MISO) && !defined(SPIB_MOSI)
    #if defined(CONFIG_IDF_TARGET_ESP32) // ESP32 default VSPI/SPI3
      #define SPIB_SCK 14
      #define SPIB_MISO 12
      #define SPIB_MOSI 13
    #elif defined(CONFIG_IDF_TARGET_ESP32S3) // ESP32-S3 default FSPI/SPI2
      #define SPIB_SCK 36
      #define SPIB_MISO 37
      #define SPIB_MOSI 35
    #elif defined(CONFIG_IDF_TARGET_ESP32C3) // ESP32-C3 default FSPI/SPI2
      #error SPIB_DEFAULT defined but ESP32-C3 can not use a secondary SPI bus!
    #endif
  #endif
#endif
// Display (if SPI) will always use SPIA / Primary bus.
// Define other peripheral SPI bus assignments in myoptions.h as so:
//       #define VS1053_SPI 'A' // VS1053 decoder on Bus A (if no SPI Display)
//       #define SD_SPI     'B' // SD card on Bus B
//       #define TS_SPI     'B' // Touchscreen on Bus B
//
// Internal macros SPIA, SPI_BUS_SECONDARY, VS1053_SPIBUS are auto-derived below - do not set them in myoptions.h
#define SPIA SPI // Bus A alias — always the default &SPI instance
/* Auto-derive Bus B controller number when Bus B pins are set. DO NOT SET THIS IN myoptions.h */
#if defined(SPIB_SCK)
  #if defined(CONFIG_IDF_TARGET_ESP32)
    #define SPI_BUS_SECONDARY 2 // peripheral formerly called HSPI on ESP32
  #else
    #define SPI_BUS_SECONDARY 1 // peripheral called HSPI on ESP32-S3/C3
  #endif
#endif

/* Override SPI, I2C Speeds and Addresses with myoptions.h */
// may not work for all display drivers, especially if custom libraries are included. ie. ILI9488 which is fixed to 40000000UL
// #define DEF_SPI_FREQ 8000000UL // defaults usually OK; may range from 8000000UL (8 MHz) to 80000000UL (80 MHz); check your datasheet before changing! set to 0 
// #define I2CFREQ_HZ   400000UL // OLED driver default is 4000000UL (4 MHz); lower e.g. to 400000UL (400 kHz) if display is glitchy; range: 100000UL (100 kHz) to 4000000UL (4 MHz)
// #define SCREEN_ADDRESS 0x3C // see datasheet for address or scan it https://create.arduino.cc/projecthub/abdularbi17/how-to-scan-i2c-address-in-arduino-eaadda


/* ============================== AUDIO ============================== */

/* --- VS1053 PINS --- */
#ifndef VS1053_CS
  #define VS1053_CS 255
#endif
#ifndef VS1053_DCS
  #define VS1053_DCS 255
#endif
#ifndef VS1053_DREQ
  #define VS1053_DREQ 255
#endif
#ifndef VS1053_RST
  #define VS1053_RST -1 // set to -1 if connected to Esp EN pin
#endif
// myoptions.h should also define which SPI bus will be used:
// #define VS1053_SPI 'A' // VS1053 decoder on Bus A (no display on A)
// #define VS1053_SPI 'B' // VS1053 decoder on Bus B
#if VS1053_CS!=255 && !defined(VS1053_SPI)
  #error VS1053_SPI not defined in myoptions.h
#endif
/* VS1053 bus assignment: auto-derived from which bus VS1053_SCK belongs to. */
/* Helper for VS1053 library */
#if defined(VS1053_SPI) && !defined(VS1053_SCK)
  #if VS1053_SPI == 'A' && defined(SPIA_SCK)
    #define VS1053_SCK  SPIA_SCK
    #define VS1053_MISO SPIA_MISO
    #define VS1053_MOSI SPIA_MOSI
  #elif VS1053_SPI == 'B' && defined(SPIB_SCK)
    #define VS1053_SCK  SPIB_SCK
    #define VS1053_MISO SPIB_MISO
    #define VS1053_MOSI SPIB_MOSI
  #endif
#endif
// This next bit should not be needed later when upgrading the VS1053 library
// Do not set VS1053_SPIBUS in myoptions.h
#if VS1053_CS != 255
  #if !defined(VS1053_SCK)
    #error define error in myoptions.h: VS1053 enabled (VS1053_CS != 255) but VS1053_SCK not defined. Set VS1053_SPI 'A' or 'B' with matching SPIA_/SPIB_ bus pins, or define VS1053_SCK/MISO/MOSI directly.
  #elif defined(SPIB_SCK) && (VS1053_SCK == SPIB_SCK)
    #define VS1053_SPIBUS SPIB // VS1053 on Bus B
  #else
    #define VS1053_SPIBUS SPIA // VS1053 on Bus A
  #endif
#endif

/* --- ESP32 INTERNAL DAC --- */
/* The ESP32 has an internal DAC - these are the pins needed to use it */
/* It is NOT recommended to use and not officially supported */
#ifdef USE_AUDIO_ESP32_DAC
  #ifndef I2S_BCLK
    #define I2S_BCLK 26
  #endif
  #ifndef I2S_LRC
    #define I2S_LRC 25
  #endif
#endif

/* --- I2S PCM DAC --- */
#ifndef I2S_DOUT
  #define I2S_DOUT 255 // DIN connection
#endif
#ifndef I2S_BCLK
  #define I2S_BCLK 255 // BCLK Bit clock
#endif
#ifndef I2S_LRC
  #define I2S_LRC 255 // WSEL Left Right Clock
#endif
#ifndef I2S_DIN
  #define I2S_DIN 255 // optional DIN (not wired by default)
#endif
#ifndef I2S_MCLK
  #define I2S_MCLK 255 // optional MCLK (not wired by default)
#endif

/* --- I2S ES8311 DECODER --- */

/* a special define for a special decoder */
/* #define USE_ES8311 activates the ES8311 mono decoder */
/* requires I2S DOUT BCLK LRC (and MCLK probably too) pins defined */
#ifdef USE_ES8311
  #ifndef ES8311_MAX_I2S
    #define ES8311_MAX_I2S 180 // Maximum I2S value to allow when mapping to ES8311 codec (0..254)
  #endif
  #ifndef PLAYER_FORCE_MONO
    #define PLAYER_FORCE_MONO true // forces the VU meter mono (setting false doesn't change hardware capability)
  #endif
  #if defined(ES8311_I2C_SCL) && ES8311_I2C_SCL != 255 && defined(ES8311_I2C_SDA) && ES8311_I2C_SCL != 255
    // may fix volume on boot issues (if defined and not 255)
    // #define ES8311_I2C_SCL  15
    // #define ES8311_I2C_SDA  16
  #else
    #undef ES8311_I2C_SCL
    #undef ES8311_I2C_SDA
  #endif
#endif

/* --- DECODER OPTIONS --- */
#ifndef MUTE_PIN
  #define MUTE_PIN 255 // MUTE Pin
#endif
#ifndef MUTE_VAL
  #define MUTE_VAL HIGH // Write this to MUTE_PIN when player is stopped
#endif
#ifndef MUTE_LOCK
  #define MUTE_LOCK false // for vs1053 Shield rev2 - lock MUTE_PIN to !MUTE_VAL
#endif
#ifndef PLAYER_FORCE_MONO
  #define PLAYER_FORCE_MONO false // mono option - false stereo, true mono (also add for mono I2S decoders for the VU)
#endif

/* --- CHECK DECODER OPTIONS --- */
#if (I2S_DOUT!=255) && (VS1053_CS!=255)
  #error define error in myoptions.h: both I2S_DOUT and VS1053_CS are active - set I2S_DOUT 255 or VS1053_CS 255 to disable one
#endif

/* Derived audio decoder gates - do NOT define these directly in myoptions.h. */
/* USE_AUDIO_VS1053 is defined when all six required VS1053 pins are present. */
/* USE_AUDIO_I2S is defined when the three required I2S pins are present. */
/* These replace the old I2S_DOUT==255 / VS1053_CS==255 gate pattern used in yoRadio */
#if (VS1053_CS!=255) && (VS1053_DCS!=255) && (VS1053_DREQ!=255) && (VS1053_MOSI!=255) && (VS1053_MISO!=255) && (VS1053_SCK!=255)
  #define USE_AUDIO_VS1053
#endif
#if (I2S_DOUT != 255) && (I2S_BCLK!=255) && (I2S_LRC!=255)
  #define USE_AUDIO_I2S
#endif
#if defined(USE_AUDIO_ESP32_DAC) && !defined(ARDUINO_ESP32_DEV)
  #error Only the ESP32 (not S3 or C4) can use the internal DAC. Do not define USE_AUDIO_ESP32_DAC.
#endif
#if defined(USE_AUDIO_ESP32_DAC)
  #if defined(USE_AUDIO_VS1053) || defined(USE_AUDIO_I2S)
    #error Both ESP32 Internal DAC and either VS1053 audio or I2S audio are active.  Do not define USE_AUDIO_ESP32_DAC.
  #endif
#else
  #if defined(USE_AUDIO_VS1053) && defined(USE_AUDIO_I2S)
    #error Both VS1053 audio and I2S audio are active. Check your pin definitions.
  #endif
#endif
#if !defined(USE_AUDIO_VS1053) && !defined(USE_AUDIO_I2S) && !defined(USE_AUDIO_ESP32_DAC)
  #error No audio decoder active. Define VS1053 SPI pins or I2S pins in myoptions.h.
#endif


/* ============================== SD CARD ============================== */
#ifndef SD_CS
  #define SD_CS 255 // SDCARD CS pin: 255 = disabled
#endif
// myoptions.h should also define which SPI bus will be used:
// #define SD_SPI 'A' // SD card on Bus A
// #define SD_SPI 'B' // SD card on Bus B
#if SD_CS!=255
  #if !defined(SD_SPI)
    #error SD_SPI not defined in myoptions.h
  #else
    #define USE_SD
  #endif
#endif
#ifndef SDSPISPEED
  #if defined(ARDUINO_ESP32_DEV)
    #define SDSPISPEED 20000000 // safe
  #elif defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)
    #define SDSPISPEED 40000000 // S3 known to work at this speed (even with custom pins)
  #else
    #define SDSPISPEED 20000000 // safe
  #endif
#endif
#ifndef SD_CARD_DETECT_PIN
  #define SD_CARD_DETECT_PIN 255 // GPIO pin for mechanical SD card-detect switch (LOW=card present, HIGH=slot empty). 255 = disabled.
#endif
#ifndef SD_AUTOPLAY
  #define SD_AUTOPLAY false // auto-switch to SD card mode when card is inserted (requires SD_CARD_DETECT_PIN != 255)
#endif
#ifndef SD_MAX_LEVELS
  #define SD_MAX_LEVELS 5 // search depth for files on the SD card
#endif
#if (SD_MAX_LEVELS < 1) || (SD_MAX_LEVELS > 10)
  #error define error in myoptions.h: SD_MAX_LEVELS must be between 1 and 10
#endif


/* ============================== INPUT ============================== */

/* --- ROTARY ENCODER --- */
#ifndef ENC_BTNL
  #define ENC_BTNL 255
#endif
#ifndef ENC_BTNB
  #define ENC_BTNB 255
#endif
#ifndef ENC_BTNR
  #define ENC_BTNR 255
#endif
#ifndef ENC_PULLUP // use internal pullup on rotary Credit: Buska1968 https://4pda.to/forum/index.php?s=&showtopic=1010378&view=findpost&p=113385448
  #define ENC_PULLUP true
#endif
#ifndef ENC_BTNB_PULLUP // use internal pullup on button
  #define ENC_BTNB_PULLUP true
#endif
#ifdef ENC_STEPS
  #if !(ENC_STEPS == 1  ENC_STEPS == 2 | ENC_STEPS == 4 // 1 is acceptable but 2 for more accuracy
    #error ENC_STEPS 1 or 2 or 4 only please
  #endif
#else
  #define ENC_STEPS 1
#endif

#ifndef ENC2_BTNL
  #define ENC2_BTNL 255
#endif
#ifndef ENC2_BTNB
  #define ENC2_BTNB 255
#endif
#ifndef ENC2_BTNR
  #define ENC2_BTNR 255
#endif
#ifndef ENC2_PULLUP // use internal pullup on rotary
  #define ENC2_PULLUP true
#endif
#ifndef ENC2_BTNB_PULLUP // use internal pullup on button
  #define ENC2_BTNB_PULLUP true
#endif
#ifdef ENC2_STEPS
  #if !(ENC2_STEPS==1  ENC2_STEPS==2 | ENC2_STEPS==4 // 1 is acceptable but 2 for more accuracy
    #error ENC2_STEPS 1 or 2 or 4 only please
  #endif
#else
  #define ENC2_STEPS 1
#endif

/* --- BUTTONS --- */
/* First, compatibility with yoRadio defines */
#ifdef BTN_LEFT
  #define BTN_PREV BTN_LEFT
#endif
#ifdef BTN_CENTER
  #define BTN_PLAY BTN_CENTER
#endif
#ifdef BTN_RIGHT
  #define BTN_NEXT BTN_RIGHT
#endif
/* Useful if you want to apply false to all pullups with one define (otherwise true) */
#ifdef BTN_INTERNALPULLUP
  #define BTN_PREV_PULLUP BTN_INTERNALPULLUP
  #define BTN_PLAY_PULLUP BTN_INTERNALPULLUP
  #define BTN_NEXT_PULLUP BTN_INTERNALPULLUP
  #define BTN_UP_PULLUP BTN_INTERNALPULLUP
  #define BTN_DOWN_PULLUP BTN_INTERNALPULLUP
  #define BTN_MODE_PULLUP BTN_INTERNALPULLUP
#endif
/* ehRadio Buttons */
#ifndef BTN_PREV
  #define BTN_PREV 255
#endif
#ifndef BTN_PREV_PULLUP
  #define BTN_PREV_PULLUP true
#endif
#ifndef BTN_PLAY
  #define BTN_PLAY 255
#endif
#ifndef BTN_PLAY_PULLUP
  #define BTN_PLAY_PULLUP true
#endif
#ifndef BTN_NEXT
  #define BTN_NEXT 255
#endif
#ifndef BTN_NEXT_PULLUP
  #define BTN_NEXT_PULLUP true
#endif
#ifndef BTN_UP
  #define BTN_UP 255
#endif
#ifndef BTN_UP_PULLUP
  #define BTN_UP_PULLUP true
#endif
#ifndef BTN_DOWN
  #define BTN_DOWN 255
#endif
#ifndef BTN_DOWN_PULLUP
  #define BTN_DOWN_PULLUP true
#endif
#ifndef BTN_MODE
  #define BTN_MODE 255
#endif
#ifndef BTN_MODE_PULLUP
  #define BTN_MODE_PULLUP true
#endif
#ifndef BTN_LONGPRESS_LOOP_DELAY
  #define BTN_LONGPRESS_LOOP_DELAY 200 // delay between calling DuringLongPress event
#endif
#ifndef BTN_CLICK_TICKS
  #define BTN_CLICK_TICKS 300
#endif
#ifndef BTN_PRESS_TICKS
  #define BTN_PRESS_TICKS 500
#endif
#if BTN_PRESS_TICKS <= BTN_CLICK_TICKS
  #error define error in myoptions.h: BTN_PRESS_TICKS must be greater than BTN_CLICK_TICKS
#endif
/* Use this button to wake from deep sleep (other buttons can be reused) */
#ifndef WAKE_PIN
  #define WAKE_PIN 255 // Wake Pin (manual wakeup from deep sleep. can match with BTN_XXXX, ENC_BTNB, ENC2_BTNB)
                // ESP32: RTC-capable GPIOs only: 0,2,4,12-15,25-27,32-39
                // ESP32-S3: RTC-capable GPIOs only: 0-21
                // ESP32-C3: RTC-capable GPIOs only: 0-5
#endif
// WAKE_PIN polarity default: LOW = active-low button (pin held HIGH by pull-up; wakes when button pulls to GND)
// #define WAKE_PIN_STATE HIGH for active-high circuits (pin held LOW by pull-down; wakes when button pulls to VCC)
#ifndef WAKE_PIN_STATE
  #define WAKE_PIN_STATE LOW
#endif

/* --- NEXTION --- */
#ifndef NEXTION_RX
  #define NEXTION_RX 255
#endif
#ifndef NEXTION_TX
  #define NEXTION_TX 255
#endif
#if NEXTION_RX!=255 && NEXTION_TX!=255
  #define USE_NEXTION
#endif

/* --- TOUCH SCREEN --- */
#define TS_MODEL_UNDEFINED 0
#define TS_MODEL_XPT2046 1
#define TS_MODEL_GT911 2
#define TS_MODEL_FT6336 3

#ifndef TS_MODEL
  #define TS_MODEL TS_MODEL_UNDEFINED
#endif
#if (TS_MODEL < 0) || (TS_MODEL > 3)
  #error define error in myoptions.h: TS_MODEL must be TS_MODEL_XPT2046, TS_MODEL_GT911, or TS_MODEL_FT6336
#endif

#ifndef TS_CS
  #define TS_CS 255
#endif
#ifndef TS_SDA
  #define TS_SDA 255
#endif
#ifndef TS_SCL
  #define TS_SCL 255
#endif
#ifndef TS_INT
  #define TS_INT 255
#endif
#ifndef TS_RST
  #define TS_RST 255
#endif
// myoptions.h should also define which SPI bus will be used (if an SPI Touchscreen):
// #define TS_SPI 'A' // Touchscreen on Bus A
// #define TS_SPI 'B' // Touchscreen on Bus B
#if TS_CS!=255 && !defined(TS_SPI)
  #error TS_SPI not defined in myoptions.h
#endif

/* --- IR --- */
#ifndef IR_PIN
  #define IR_PIN 255
#endif
#ifndef IR_TIMEOUT
  #define IR_TIMEOUT 80 // kTimeout, see IRremoteESP8266 documentation
#endif


/* ============================== RTC ============================== */

#define RTC_MODULE_UNDEFINED 0
#define DS3231 1
#define DS1307 2

#ifndef RTC_MODULE
  #define RTC_MODULE RTC_MODULE_UNDEFINED  /*  DS3231 or DS1307  */
#endif
#if (RTC_MODULE < 0) || (RTC_MODULE > 2)
  #error define error in myoptions.h: RTC_MODULE must be DS3231 or DS1307 (or leave undefined)
#endif
#ifndef RTC_SDA
  #define RTC_SDA 255
#endif
#ifndef RTC_SCL
  #define RTC_SCL 255
#endif


/* ============================== LED ============================== */

/* You can try using #define LED_PIN LED_BUILTIN but it is better to define the actual pin */
#ifdef LED_PIN
 //#define LED_PIN 8
#else
  #define LED_PIN 255 // unused
#endif
#ifndef LED_INVERT // can define as true in myoptions.h: inverts behavior of above LED
  #define LED_INVERT false
#endif
#ifdef RGB_LED_PIN // will use Neopixel library to control RGB LED with something like:
 //#define RGB_LED_PIN 42
#else
  #define RGB_LED_PIN 255 // unused
#endif
#ifdef RGB_LED_ORDER // Most WS2812 LEDs are actually GRB but can be over-ridden
 // #define RGB_LED_ORDER NEO_GRB
#endif


/* ============================== SYSTEM OVERRIDES ============================== */

/* --- SYSTEM TWEAKS --- */
#ifndef WIFI_ATTEMPTS
  #define WIFI_ATTEMPTS 16
#endif
#if WIFI_ATTEMPTS < 1
  #error define error in myoptions.h: WIFI_ATTEMPTS must be at least 1
#endif
#ifndef SEARCHRESULTS_BUFFER
 // Buffer for chunked HTTP transfers from radio-browser.info. Defined in KB; conversion to bytes done in netserver.cpp.
 // ESP32-C3 has less RAM than base ESP32 — keep conservative at 4KB like base ESP32.
  #if defined(ARDUINO_ESP32S3_DEV)
    #define SEARCHRESULTS_BUFFER 32 // KB; matches radio-browser.info chunk size
  #else // ESP32 and ESP32-C3
    #define SEARCHRESULTS_BUFFER 4 // KB
  #endif
#elif (SEARCHRESULTS_BUFFER < 4) || (SEARCHRESULTS_BUFFER > 64)
  #error define error in myoptions.h: SEARCHRESULTS_BUFFER must be between 4 and 64 (value in KB)
#endif
#ifndef SEARCHRESULTS_YIELDINTERVAL
  #define SEARCHRESULTS_YIELDINTERVAL 0 // With a large buffer, skipping is almost eliminated with 0
#endif
#ifdef MAX_PL_READ_BYTES
 //#define MAX_PL_READ_BYTES 65536 // Makes chunked HTML transfers... possibly enable if experiencing slowdowns when sending web UI to client. Untested.
#endif
/* Maximum lengths of character buffers */
/* Notes have been made regarding old yoRadio values */
#ifndef WEATHER_STRING_L
  #define WEATHER_STRING_L 512 // size of weather string, formerly 254
#endif
#ifndef WEBSOCKET_BUFFER
  #define WEBSOCKET_BUFFER 512 // formerly 340
#endif
#ifndef MQTT_URL_SIZE
  #define MQTT_URL_SIZE 512 // shared URL buffer cap for MQTT commands, artwork URLs, and browse URLs
#endif
#ifndef STATION_FIELD_LENGTH
  #define STATION_FIELD_LENGTH 170 // max length for station name, URL, and title fields
#endif
#if STATION_FIELD_LENGTH < 64
  #error define error in myoptions.h: STATION_FIELD_LENGTH is too small (minimum 64, default 170)
#endif
#ifndef CONNECT_HTTP_HTTPS_TIMEOUT
 // Connection timeout in milliseconds: HTTP, HTTPS(SSL)
 // Library defaults: 250ms HTTP, 2700ms SSL
 // Conservative values for slower networks: 1700ms HTTP, 3700ms SSL
 // #define CONNECT_HTTP_HTTPS_TIMEOUT 1700, 3700 /* For ESP32? */
 // undefined means using library defaults (preferred)
#endif

/* --- CPU CORES --- */
/* ESP32 and ESP32-S3 have 2 cores. Core 0 will handle audio processes. */
/* Core 1 will handle everything else. Overrides are possible with these but be careful. */
#if defined(CONFIG_FREERTOS_UNICORE) // will automatically activate on compiling for ESP32-C3 or other single-core ESPs
  #ifdef AUDIO_CORE
    #error Do not try to define AUDIO_CORE on a single-core ESP - it will be handled automatically!
  #else
    #define AUDIO_CORE 0
  #endif
#else // If not 1 Core, then define core processes
  #ifndef AUDIO_CORE
    #define AUDIO_CORE 0
  #else
    #if (AUDIO_CORE!=1)
	    #error Only add #define AUDIO_CORE 1 to options.h to move Audio to CPU core 1. Leave it undefined for core 0.
    #endif
  #endif
#endif
#if defined(CONFIG_FREERTOS_UNICORE)
  #ifdef NETWORK_CORE
    #error Do not try to define NETWORK_CORE on a single-core ESP - it will be handled automatically!
  #else
    #define NETWORK_CORE 0
  #endif
#else
  #ifndef NETWORK_CORE
    #define NETWORK_CORE 1
  #else
    #if (NETWORK_CORE!=0)
	    #error Only add #define NETWORK_CORE 0 to options.h to move Netserver to CPU core 0. Leave it undefined for core 1.
    #endif
  #endif
#endif
#if defined(CONFIG_FREERTOS_UNICORE)
  #ifdef DSP_TASK_CORE_ID
    #error Do not try to define DSP_TASK_CORE_ID on a single-core ESP - it will be handled automatically!
  #else
    #define DSP_TASK_CORE_ID 0
  #endif
#else
  #ifndef DSP_TASK_CORE_ID
    #define DSP_TASK_CORE_ID 1
  #else
    #if (DSP_TASK_CORE_ID!=0)
	    #error Only add #define DSP_TASK_CORE_ID 0 to options.h to move Netserver to CPU core 0. Leave it undefined for core 1.
    #endif
  #endif
#endif


/* --- TWEAKS FOR CORE PROCESSES --- */
/* Board-scaled stack size multiplier */
/* Applied automatically to FreeRTOS task stack defaults based on board SRAM capacity */
/* Override in myoptions.h only if needed: #define STACK_MULTIPLIER 1 to disable scaling on S3 */
/* Note: ESP32-C3 has LESS RAM than base ESP32 and defaults to 1x — same as base ESP32 */
#ifndef STACK_MULTIPLIER
  #if defined(ARDUINO_ESP32S3_DEV)
    #define STACK_MULTIPLIER 2 // ESP32-S3: double stack sizes (most SRAM available)
  #else
    #define STACK_MULTIPLIER 1 // ESP32 and ESP32-C3: conservative defaults
  #endif
#endif
#if (STACK_MULTIPLIER != 1 && STACK_MULTIPLIER != 2)
  #error define error in myoptions.h: STACK_MULTIPLIER must be 1 or 2
#endif

/* Stack sizes are in KB; conversion to bytes is done locally in each .cpp file via a _BYTES macro */
/* Delay values are in ms; pdMS_TO_TICKS() conversion is done locally in each .cpp file via a SET_ macro */
/* The straight number without multiplier is from yoRadio ESP32 defaults - ESP32-S3 uses the multiplier */
/* If working on an ESP32 or ESP32-C3 be warned that these numbers are actually untested and feedback is welcome! */

/* Arduino loop() task (main.cpp) — SET_LOOP_TASK_STACK_SIZE() uses this directly in bytes */
#ifndef LOOP_TASK_STACK_SIZE
  #define LOOP_TASK_STACK_SIZE (8 * STACK_MULTIPLIER) // KB; 8 (ESP32/C3) or 16 (S3)
#elif (LOOP_TASK_STACK_SIZE < 4) || (LOOP_TASK_STACK_SIZE > 64)
  #error define error in myoptions.h: LOOP_TASK_STACK_SIZE must be between 4 and 64 (value in KB)
#endif

/* DspTask (display.cpp): render loop task */
#ifndef DSP_TASK_STACK_SIZE
  #define DSP_TASK_STACK_SIZE  (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif (DSP_TASK_STACK_SIZE < 2) || (DSP_TASK_STACK_SIZE > 32)
  #error define error in myoptions.h: DSP_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif
#ifndef DSP_TASK_PRIORITY
  #define DSP_TASK_PRIORITY 2 // 2 = above Arduino loop() (1), below audio-critical tasks (3)
#endif
#ifndef DSP_TASK_DELAY
  #define DSP_TASK_DELAY 10 // ms; minimum sleep between display iterations. Actual frame rate depends on display SPI write time — typically ~50fps at slow SPI speeds, up to 100fps on faster displays
#endif
#ifndef DSP_QUEUE_TICKS
  #define DSP_QUEUE_TICKS 0 // ticks; xQueueReceive timeout inside display.loop(). 0 = non-blocking poll. Higher values (e.g. 5) reduce latency when queue is empty but are rarely needed; per-display conf files may override
#endif
#ifndef DSQ_SEND_DELAY
  #define DSQ_SEND_DELAY 200 // ms; xQueueSend timeout in display.putRequest(). If queue full, calling task blocks up to this long before dropping the request silently — preferable to blocking the audio task
#endif
#ifndef PLQ_SEND_DELAY
  #define PLQ_SEND_DELAY 100 // ms; xQueueSend timeout in player.sendCommand(). Short timeout prevents blocking audio decode while still absorbing brief queue pressure
#endif
#if defined(ARDUINO_ESP32S3_DEV) // Minimum allocation bytes; min free heap before spawning a background task (search, curated, playback, rb_click)
  #define MIN_MALLOC 24112 // ESP32-S3: known to be good, generous
#else
  #define MIN_MALLOC 12056 // ESP32 and ESP32-C3: tight...? good luck!
#endif

/* netserverLoopTask (netserver.cpp): runs netserver.loop() on its own pinned task */
#ifndef NETSERVER_TASK_STACK_SIZE
  #define NETSERVER_TASK_STACK_SIZE  (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif (NETSERVER_TASK_STACK_SIZE < 2) || (NETSERVER_TASK_STACK_SIZE > 32)
  #error define error in myoptions.h: NETSERVER_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif
#ifndef NETSERVER_TASK_PRIORITY
  #define NETSERVER_TASK_PRIORITY 2 // 2 = above Arduino loop() (1), same tier as display
#endif
#ifndef NETSERVER_TASK_DELAY
  #define NETSERVER_TASK_DELAY 1 // ms; yield between netserver.loop() iterations
#endif
#ifndef NSQ_SEND_DELAY
  #define NSQ_SEND_DELAY 300 // ms; xQueueSend timeout for nsQueue (requestOnChange). Use portMAX_DELAY to block indefinitely
#endif
#ifndef NS_QUEUE_DELAY
  #define NS_QUEUE_DELAY 0 // ms; xQueueReceive timeout for nsQueue (processQueue). 0 = non-blocking poll
#endif

/* nextionCore0 (nextion.cpp): Nextion display task */
#ifndef NEXTION_TASK_STACK_SIZE
  #define NEXTION_TASK_STACK_SIZE (3 * STACK_MULTIPLIER) // KB; 3 (ESP32/C3) or 6 (S3)
#elif (NEXTION_TASK_STACK_SIZE < 2) || (NEXTION_TASK_STACK_SIZE > 16)
  #error define error in myoptions.h: NEXTION_TASK_STACK_SIZE must be between 2 and 16 (value in KB)
#endif
#ifndef NEXTION_TASK_PRIORITY
  #define NEXTION_TASK_PRIORITY 2 // 2 = same tier as display
#endif

/* Network utility tasks (network.cpp, player.cpp): doSync, searchWiFi, retryStreamConnection */
#ifndef NETWORK_TASK_STACK_SIZE
  #define NETWORK_TASK_STACK_SIZE (4 * STACK_MULTIPLIER) // KB; 4 (ESP32/C3) or 8 (S3)
#elif (NETWORK_TASK_STACK_SIZE < 2) || (NETWORK_TASK_STACK_SIZE > 32)
  #error define error in myoptions.h: NETWORK_TASK_STACK_SIZE must be between 2 and 32 (value in KB)
#endif

/* Priority scale for all pinned tasks (FreeRTOS: higher number = more CPU, preempts lower tasks) */
/* Arduino loop() runs at priority 1. Priority 0 = idle-level (starved by any other task — do not use). */
#ifndef PLAYBACK_TASK_PRIORITY
  #define PLAYBACK_TASK_PRIORITY 3 // highest: stream connection / playback start
#endif
#ifndef NET_TASK_PRIORITY
  #define NET_TASK_PRIORITY 3 // highest: WiFi search, stream retry, OTA download
#endif
#ifndef LOW_TASK_PRIORITY
  #define LOW_TASK_PRIORITY 1 // lowest: background/deferrable tasks (round-robin with loop())
#endif


/* --- LIBRARY OVERRIDES --- */
/* These are overrides for external libraries */
#ifndef CONFIG_ASYNC_TCP_QUEUE_SIZE
  #if defined(ARDUINO_ESP32S3_DEV)
    #define CONFIG_ASYNC_TCP_QUEUE_SIZE 64 // ESP32-S3: larger queue for higher network throughput
  #else
    #define CONFIG_ASYNC_TCP_QUEUE_SIZE 32 // ESP32 and ESP32-C3
  #endif
#endif
#ifndef CONFIG_ASYNC_TCP_RUNNING_CORE
  #define CONFIG_ASYNC_TCP_RUNNING_CORE NETWORK_CORE // -1 = any available core (NETWORK_CORE is default)
#endif
#ifndef CONFIG_ASYNC_TCP_USE_WDT
  #define CONFIG_ASYNC_TCP_USE_WDT 0 // 1 = watchdog enabled (adds between 33us and 200us per event)
#endif

/* ============================== COLOR ============================== */
/* ehRadio Color Theme: over-ridden by mytheme.h (if it exists) */
/*        color name                R,   G,   B  */
#ifndef COLOR_BACKGROUND // background
  #define COLOR_BACKGROUND          0,   0,   0
#endif
#ifndef COLOR_STATION_NAME // station text color
  #define COLOR_STATION_NAME        0,   0,   0
#endif
#ifndef COLOR_STATION_BG // current station background
  #define COLOR_STATION_BG          0, 100, 255
#endif
#ifndef COLOR_STATION_FILL // fill color (outside bg)
  #define COLOR_STATION_FILL        0,  98, 250
#endif
#ifndef COLOR_SNG_TITLE_1 // first title
  #define COLOR_SNG_TITLE_1       255, 255, 255
#endif
#ifndef COLOR_SNG_TITLE_2 // second title
  #define COLOR_SNG_TITLE_2       220, 220, 220
#endif
#ifndef COLOR_WEATHER // weather string
  #define COLOR_WEATHER           224, 124,  16
#endif
#ifndef COLOR_VU_MAX // max of VU meter "FireBrick"
  #define COLOR_VU_MAX            178,  34,  34
#endif
#ifndef COLOR_VU_MIN // min of VU meter "Green"
  #define COLOR_VU_MIN              0, 128,   0
#endif
#ifndef COLOR_CLOCK // clock color
  #define COLOR_CLOCK             255,  32,  16
#endif
#ifndef COLOR_CLOCK_BG // clock color background
  #define COLOR_CLOCK_BG           30,   2,   2
#endif
#ifndef COLOR_SECONDS // seconds color (DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_SECONDS           255,  16,   4
#endif
#ifndef COLOR_DAY_OF_W // day of week color (for DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_DAY_OF_W          240, 240, 240
#endif
#ifndef COLOR_DATE // date color (DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_DATE              255, 255, 255
#endif
#ifndef COLOR_HEAP // heap string
  #define COLOR_HEAP              224, 124,  16
#endif
#ifndef COLOR_BUFFER // buffer line
  #define COLOR_BUFFER            224, 64,  192
#endif
#ifndef COLOR_IP // IP address
  #define COLOR_IP                  0, 200, 220
#endif
#ifndef COLOR_VOLUME_VALUE // volume number
  #define COLOR_VOLUME_VALUE      15,  180,  15
#endif
#ifndef COLOR_RSSI // rssi
  #define COLOR_RSSI                0, 200, 220
#endif
#ifndef COLOR_BATTERY // battery
  #define COLOR_BATTERY           224, 124,  16
#endif
#ifndef COLOR_VOLBAR_OUT // border of volume bar
  #define COLOR_VOLBAR_OUT        30,  200,  30
#endif
#ifndef COLOR_VOLBAR_IN // inside volume bar
  #define COLOR_VOLBAR_IN         5,   140,   5
#endif
#ifndef COLOR_DIGITS // numbers...?
  #define COLOR_DIGITS            255, 255, 255
#endif
#ifndef COLOR_DIVIDER // lines around clock
  #define COLOR_DIVIDER           132, 132, 165
#endif
#ifndef COLOR_PL_CURRENT // playlist current item
  #define COLOR_PL_CURRENT          0, 170, 250
#endif
#ifndef COLOR_PL_CURRENT_BG // playlist current item background
  #define COLOR_PL_CURRENT_BG      30,  30,  30
#endif
#ifndef COLOR_PL_CURRENT_FILL // playlist current item fill background
  #define COLOR_PL_CURRENT_FILL    60,  60,  60
#endif
#ifndef COLOR_PLAYLIST_0 // playlist string 0
  #define COLOR_PLAYLIST_0        250, 250, 250
#endif
#ifndef COLOR_PLAYLIST_1 // playlist string 1
  #define COLOR_PLAYLIST_1        230, 230, 230
#endif
#ifndef COLOR_PLAYLIST_2 // playlist string 2
  #define COLOR_PLAYLIST_2        210, 210, 210
#endif
#ifndef COLOR_PLAYLIST_3 // playlist string 3
  #define COLOR_PLAYLIST_3        190, 190, 190
#endif
#ifndef COLOR_PLAYLIST_4 // playlist string 4
  #define COLOR_PLAYLIST_4        170, 170, 170
#endif
#ifndef COLOR_BITRATE // stream bitrate
  #define COLOR_BITRATE           220, 220,  90
#endif


/* ============================== SYSTEM DEFAULTS ============================== */

/* --- SOURCE OF UPDATE FILES --- */
/* only used if FIRMWARE is defined as it is in Trip5's automatic Github builds */
#ifndef GITHUBURL
  #define GITHUBURL "https://github.com/trip5/ehradio" // used by the ESPFileUpdater in BrowserClient (and in URLs below)
#endif
#ifdef FIRMWARE // this is the filename.bin online
 // #define FIRMWARE_NAME "Trip5's Big Screen Radio" optional name of the firmware (appears only in eh Device Protocol and will appear as the filename (without .bin) by default if not defined)
  #ifndef FILESURL
    #define FILESURL GITHUBURL "/releases/download/" RADIOVERSION "/" // + FILE for SPIFFS files (this version)
  #endif
  #ifndef UPDATEURL
    #define UPDATEURL GITHUBURL "/releases/latest/download/" // + FIRMWARE for the file
  #endif
  #ifndef CHECKUPDATEURL
    #define CHECKUPDATEURL GITHUBURL "/releases/latest/download/version.txt" // automatically extracted from options.h during Github workflow
  #endif
  #ifndef VERSIONSTRING
    #define VERSIONSTRING "ehRadio Version" // the file above should have a line that starts with this followed by a version number
  #endif
  #ifndef CHECKUPDATEURL_TIME
    #define CHECKUPDATEURL_TIME "1 day"
  #endif
#else
  #undef FILESURL
  #undef UPDATEURL
  #undef CHECKUPDATEURL
  #undef VERSIONSTRING
  #undef CHECKUPDATEURL_TIME
#endif
#ifdef DISABLE_UPDATER // if this is defined, disables online updates
  #undef FILESURL
  #undef UPDATEURL
  #undef CHECKUPDATEURL
  #undef VERSIONSTRING
  #undef CHECKUPDATEURL_TIME
#endif

/* --- SOURCE OF JSON FILES --- */
#ifndef TIMEZONES_JSON_URL
  #define TIMEZONES_JSON_URL "https://raw.githubusercontent.com/trip5/timezones.json/master/timezones.json.gz"
#endif
#ifndef TIMEZONES_JSON_CHECKTIME
  #define TIMEZONES_JSON_CHECKTIME "4 weeks"
#endif
#ifndef RADIO_BROWSER_SERVERS_URL 
  #define RADIO_BROWSER_SERVERS_URL "https://all.api.radio-browser.info/json/servers"
#endif
#ifndef RB_SERVERS_CHECKTIME
  #define RB_SERVERS_CHECKTIME "1 day"
#endif

/* --- SOURCE OF CURATED PLAYLISTS --- */
#ifndef CURATED_LISTS
  #define CURATED_LISTS "Trip5's webstations"
  #ifndef CURATED_LISTS_LINK
    #define CURATED_LISTS_LINK "https://github.com/trip5/webstations"
  #endif
  #ifndef CURATED_LISTS_URL
    #define CURATED_LISTS_URL "https://github.com/trip5/webstations/releases/latest/download/"
  #endif
  #ifndef CURATED_LISTS_INDEX
    #define CURATED_LISTS_INDEX "index.json"
  #endif
#else
  #if !defined(CURATED_LISTS_LINK) || !defined(CURATED_LISTS_URL) || !defined(CURATED_LISTS_INDEX)
    #undef CURATED_LISTS
    #undef CURATED_LISTS_LINK
    #undef CURATED_LISTS_URL
    #undef CURATED_LISTS_INDEX
  #endif
#endif

/* --- RADIO BROWSER API SERVER --- */
/* Used as fallback for search and primary for sending clicks */
#ifndef RADIO_BROWSER_SERVER
  #define RADIO_BROWSER_SERVER "all.api.radio-browser.info"
#endif
/* Opt-out sending clicks to Radio-browser API with #define RADIO_BROWSER_NO_SEND_CLICKS */
#ifndef RADIO_BROWSER_NO_SEND_CLICKS
  #ifndef RADIO_BROWSER_SEND_CLICKS
    #define RADIO_BROWSER_SEND_CLICKS
  #endif
  #ifndef RADIO_BROWSER_SEND_CLICK_DELAY
    #define RADIO_BROWSER_SEND_CLICK_DELAY 10000 // wait 10 seconds before sending the click
  #endif
#else
  #undef RADIO_BROWSER_SEND_CLICKS
#endif

/* --- OTHER COMPILE OPTIONS --- */
/*  Here are other #defines that may be added to myoptions.h   */
#ifdef MQTT_ENABLE
 // This enables MQTT. A nice option to have but not available in the code without this #define in myoptions.h
#endif
#ifdef PLAYLIST_DEFAULT_URL
 // This will download a playlist when first-booting and no playlist is present on SPIFFS.  Can be CSV or JSON format.  Example:
 // #define PLAYLIST_DEFAULT_URL "https://github.com/trip5/webstations/releases/latest/download/trip5-radio-playlist.csv"
#endif
#ifndef SCREENSAVERSTARTUPDELAY // initial delay
  #define SCREENSAVERSTARTUPDELAY 5
#endif
#ifndef HEADER_TIMEOUT
  #define HEADER_TIMEOUT 5000
#endif
#ifndef USE_OTA // define true to enable Arduino OTA
  #define USE_OTA false
#endif
#ifdef OTA_PASS
  //#define OTA_PASS "myotapassword12345"
#endif
#ifndef AP_SSID // name of hotspot in AP Mode
  #define AP_SSID "ehRadio"
#endif
#ifdef AP_PASSWORD
  #if (AP_PASSWORD)[0] == '\0' // if it's empty, undefine
    #undef AP_PASSWORD
  #endif
#endif

/* This bit will actually do something but needs to be handled a different way - configurable would be better */
/* But I'm very concerned that a forgotten password means needing a way to factory-reset using hardware... */
/* So this may never actually be implemented in a proper way */
//#define HTTP_USER "user"
//#define HTTP_PASS "password"
/* It was left here by e2002 for yoRadio and just never moved */
/* Thank you for reading, by the way */
/* And thank you to e2002 for making yoRadio */


/* ============================== DUBUG ============================== */

/* Enable all the debug logs with #define ALL_DEBUG_LOGS */
/* BATTERY_DEBUG is included elsewhere */
#ifdef ALL_DEBUG_LOGS
  #ifndef ESPFILEUPDATER_DEBUG
    #define ESPFILEUPDATER_DEBUG // This enables ESPFileUpdater's debug log in serial.  Only add if you really want to watch serial log for what may be causing fetch errors.
  #endif
  #ifndef NETSERVER_DEBUG
   #define NETSERVER_DEBUG // This enables Netserver logging: GET client requests and sending files in chunks
  #endif
  #ifndef CORE_MONITOR
    #define CORE_MONITOR // This shows the ESP32 CPU Core Monitor in serial and telnet (updated every 5s)
  #endif
  #ifdef WIDGET_DEBUG
    #define WIDGET_DEBUG // This shows the Widget's Text in logging.  It's extremely noisy.
  #endif
#endif
#ifdef CORS_DEBUG
 // This enables CORS policy: 'Access-Control-Allow-Origin' (for testing)
#endif

/* CPU CORE NAMES: Name the Cores For What They Do */
/* Do not use any of these macros directly in myoptions.h! */
/* Use #define CORE_MONITOR to show how busy the cores are... this gives them friendly names */
#if (!CONFIG_FREERTOS_UNICORE && defined(CORE_MONITOR))
  #if (AUDIO_CORE==0)
    #define CORE_0A "+Audio"
    #define CORE_1A ""
  #elif (AUDIO_CORE==1)
    #define CORE_0A ""
    #define CORE_1A "+Audio"
  #endif
  #if (NETWORK_CORE==0)
    #define CORE_0B "+Net"
    #define CORE_1B ""
  #elif (NETWORK_CORE==1)
    #define CORE_0B ""
    #define CORE_1B "+Net"
  #endif
  #if (CONFIG_ASYNC_TCP_RUNNING_CORE==0)
    #define CORE_0C "+TCP"
    #define CORE_1C ""
  #elif (CONFIG_ASYNC_TCP_RUNNING_CORE==1)
    #define CORE_0C ""
    #define CORE_1C "+TCP"
  #endif
  #if (DSP_TASK_CORE_ID==0)
    #define CORE_0D "+Disp"
    #define CORE_1D ""
  #elif (DSP_TASK_CORE_ID==1)
    #define CORE_0D ""
    #define CORE_1D "+Disp"
  #endif
  #define CORE_0 "(" CORE_0A CORE_0B CORE_0C CORE_0D ")"
  #define CORE_1 "(Main" CORE_1A CORE_1B CORE_1C CORE_1D ")"
#endif

/* ============================== BATTERY ============================== */
#ifndef BATTERY_PIN
  #define BATTERY_PIN 255 // GPIO pin for battery voltage ADC reading
#endif
#ifndef BATTERY_CHARGE_PIN
  #define BATTERY_CHARGE_PIN 255 // GPIO pin for charging status (TP4054 CHRG pin, active LOW)
#endif
#ifndef BATTERY_DIVIDER_RATIO
  #define BATTERY_DIVIDER_RATIO 2.0 // Voltage divider ratio (battery voltage / ADC voltage)
#endif
#ifndef BATTERY_ADC_REF_MV
  #define BATTERY_ADC_REF_MV 3300 // ADC reference voltage in millivolts
#endif
#ifndef BATTERY_UPDATE_INTERVAL
  #define BATTERY_UPDATE_INTERVAL 60000 // Update interval in milliseconds
#endif
#ifndef BATTERY_SAMPLES
  #define BATTERY_SAMPLES 10 // Number of ADC samples to average
#endif
#ifndef BATTERY_DIM_BRIGHTNESS
  #define BATTERY_DIM_BRIGHTNESS 20 // Battery dim fixed brightness when LOW battery (percentage 0-100)
#endif
#if (BATTERY_DIM_BRIGHTNESS < 0) || (BATTERY_DIM_BRIGHTNESS > 100)
  #error define error in myoptions.h: BATTERY_DIM_BRIGHTNESS must be a percentage between 0 and 100
#endif
#ifndef BATTERY_RECOVER_HYSTERESIS_PCT
  #define BATTERY_RECOVER_HYSTERESIS_PCT 5 // Hysteresis for recovering from low-battery dimming (percent)
#endif
/* Inference tuning defaults: control sensitivity for charging/discharging detection. */
#ifndef BATTERY_CHARGE_INFER_HOLD_SAMPLES
  #define BATTERY_CHARGE_INFER_HOLD_SAMPLES 3 // number of measurements (samples) to hold (e.g., 3 readings)
#endif
#ifndef BATTERY_IMMEDIATE_PERCENT_THRESHOLD
  #define BATTERY_IMMEDIATE_PERCENT_THRESHOLD 3 // percent; immediate single-reading threshold
#endif
#ifndef BATTERY_CANDIDATE_PERCENT_DELTA
  #define BATTERY_CANDIDATE_PERCENT_DELTA 1 // percent; minimal delta to start a candidate
#endif
#ifndef BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD
  #define BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD 0 // percent over hold window required to confirm
#endif
/* Battery presence detection (mV) - default single-cell LiPo safe range. */
#ifndef BATTERY_PRESENT_MIN_MV
  #define BATTERY_PRESENT_MIN_MV 3000 // Minimum battery voltage (mV) considered present (single-cell LiPo)
#endif
#ifndef BATTERY_PRESENT_MAX_MV
  #define BATTERY_PRESENT_MAX_MV 4300 // Maximum battery voltage (mV) considered present (single-cell LiPo)
#endif
/* Battery discharge curve defaults (mV -> percent). */
#ifndef BATTERY_CURVE_MV
  #define BATTERY_CURVE_MV 4240, 4100, 4000, 3900, 3800, 3700, 3600, 3400, 3200
#endif
#ifndef BATTERY_CURVE_PCT
  #define BATTERY_CURVE_PCT 100, 95, 90, 80, 70, 55, 30, 10, 0
#endif
#ifndef BATTERY_LOW_THRESHOLD
  #define BATTERY_LOW_THRESHOLD 25 // Low battery warning threshold (percentage, 0-100)
#endif
#if (BATTERY_LOW_THRESHOLD < 0) || (BATTERY_LOW_THRESHOLD > 100)
  #error define error in myoptions.h: BATTERY_LOW_THRESHOLD must be a percentage between 0 and 100
#endif
#ifndef BATTERY_CRITICAL_THRESHOLD
  #define BATTERY_CRITICAL_THRESHOLD 5 // Critical battery threshold (percentage, 0-100)
#endif
#if (BATTERY_CRITICAL_THRESHOLD < 0) || (BATTERY_CRITICAL_THRESHOLD > 100)
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be a percentage between 0 and 100
#endif
#if BATTERY_CRITICAL_THRESHOLD >= BATTERY_LOW_THRESHOLD
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be less than BATTERY_LOW_THRESHOLD
#endif
#ifdef BATTERY_DEBUG
 // if defined enables full information about battery in serial log
#endif


/* ============================== USER DEFAULTS ============================== */
/* Sets defaults but still editable in WebUI */
#if defined(SOUND_VOLUME) && ((SOUND_VOLUME < 0) || (SOUND_VOLUME > 254))
  #warning "define warning in myoptions.h: SOUND_VOLUME is out of range (0-254), reverting to default 12"
  #undef SOUND_VOLUME
#endif
#ifndef SOUND_VOLUME
  #define SOUND_VOLUME 12
#endif
#if defined(SOUND_BALANCE) && ((SOUND_BALANCE < -16) || (SOUND_BALANCE > 16))
  #warning "define warning in myoptions.h: SOUND_BALANCE is out of range (-16 to 16), reverting to default 0"
  #undef SOUND_BALANCE
#endif
#ifndef SOUND_BALANCE
  #define SOUND_BALANCE 0
#endif
#if defined(EQ_TREBLE) && ((EQ_TREBLE < -16) || (EQ_TREBLE > 16))
  #warning "define warning in myoptions.h: EQ_TREBLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_TREBLE
#endif
#ifndef EQ_TREBLE
  #define EQ_TREBLE 0
#endif
#if defined(EQ_MIDDLE) && ((EQ_MIDDLE < -16) || (EQ_MIDDLE > 16))
  #warning "define warning in myoptions.h: EQ_MIDDLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_MIDDLE
#endif
#ifndef EQ_MIDDLE
  #define EQ_MIDDLE 0
#endif
#if defined(EQ_BASS) && ((EQ_BASS < -16) || (EQ_BASS > 16))
  #warning "define warning in myoptions.h: EQ_BASS is out of range (-16 to 16), reverting to default 0"
  #undef EQ_BASS
#endif
#ifndef EQ_BASS
  #define EQ_BASS 0
#endif
#ifndef SD_SHUFFLE
  #define SD_SHUFFLE false
#endif
#ifndef SMART_START
  #define SMART_START false
#endif
#ifndef SHOW_AUDIO_INFO
  #define SHOW_AUDIO_INFO false
#endif
#ifndef SHOW_VU_METER
  #define SHOW_VU_METER false
#endif
#ifndef WIFI_SCAN_BEST_RSSI
  #define WIFI_SCAN_BEST_RSSI false
#endif
#ifndef EHDP
  #define EHDP true
#endif
#if defined(SOFTAP_REBOOT_DELAY) && ((SOFTAP_REBOOT_DELAY < 0) || (SOFTAP_REBOOT_DELAY > 20))
  #warning "define warning in myoptions.h: SOFTAP_REBOOT_DELAY is out of range (0-20), reverting to default 0"
  #undef SOFTAP_REBOOT_DELAY
#endif
#ifndef SOFTAP_REBOOT_DELAY
  #define SOFTAP_REBOOT_DELAY 0
#endif
#ifndef SCREEN_FLIP
  #define SCREEN_FLIP false
#endif
#ifndef SCREEN_INVERT
  #define SCREEN_INVERT false
#endif
#ifndef NUMBERED_PLAYLIST
  #define NUMBERED_PLAYLIST false
#endif
#ifndef CLOCK_TWELVE
  #define CLOCK_TWELVE false
#endif
#ifndef VOLUME_PAGE
  #define VOLUME_PAGE false
#endif
#if defined(SCREEN_BRIGHTNESS) && ((SCREEN_BRIGHTNESS < 1) || (SCREEN_BRIGHTNESS > 100))
  #warning "define warning in myoptions.h: SCREEN_BRIGHTNESS is out of range (1-100), reverting to default 100"
  #undef SCREEN_BRIGHTNESS
#endif
#ifndef SCREEN_BRIGHTNESS
  #define SCREEN_BRIGHTNESS 100
#endif
#if defined(SCREEN_CONTRAST) && ((SCREEN_CONTRAST < 1) || (SCREEN_CONTRAST > 100))
  #warning "define warning in myoptions.h: SCREEN_CONTRAST is out of range (1-100), reverting to default 55"
  #undef SCREEN_CONTRAST
#endif
#ifndef SCREEN_CONTRAST
  #define SCREEN_CONTRAST 55
#endif
#ifndef SS_NOTPLAYING
  #define SS_NOTPLAYING false
#endif
#ifndef SS_NOTPLAYING_BLANK
  #define SS_NOTPLAYING_BLANK false
#endif
#if defined(SS_NOTPLAYING_TIME) && ((SS_NOTPLAYING_TIME < 1) || (SS_NOTPLAYING_TIME > 65520))
  #warning "define warning in myoptions.h: SS_NOTPLAYING_TIME is out of range (1-65520), reverting to default 1"
  #undef SS_NOTPLAYING_TIME
#endif
#ifndef SS_NOTPLAYING_TIME
  #define SS_NOTPLAYING_TIME 1
#endif
#ifndef SS_PLAYING
  #define SS_PLAYING false
#endif
#ifndef SS_PLAYING_BLANK
  #define SS_PLAYING_BLANK false
#endif
#if defined(SS_PLAYING_TIME) && ((SS_PLAYING_TIME < 1) || (SS_PLAYING_TIME > 1080))
  #warning "define warning in myoptions.h: SS_PLAYING_TIME is out of range (1-1080), reverting to default 5"
  #undef SS_PLAYING_TIME
#endif
#ifndef SS_PLAYING_TIME
  #define SS_PLAYING_TIME 5
#endif
#ifndef DIMMING_ENABLED
    #define DIMMING_ENABLED false
#endif  
#if defined(DIMMING_TIMEOUT) && ((DIMMING_TIMEOUT < 5) || (DIMMING_TIMEOUT > 65520))
  #warning "define warning in myoptions.h: DIMMING_TIMEOUT is out of range (5-65520), reverting to default 120"
  #undef DIMMING_TIMEOUT
#endif
#ifndef DIMMING_TIMEOUT
  #define DIMMING_TIMEOUT 120
#endif
#if defined(DIMMING_BRIGHTNESS) && ((DIMMING_BRIGHTNESS < 0) || (DIMMING_BRIGHTNESS > 100))
  #warning "define warning in myoptions.h: DIMMING_BRIGHTNESS is out of range (0-100), reverting to default 50"
  #undef DIMMING_BRIGHTNESS
#elif defined(DIMMING_BRIGHTNESS) && (DIMMING_BRIGHTNESS < SCREEN_BRIGHTNESS)
  #warning "define warning in myoptions.h: DIMMING_BRIGHTNESS is less than SCREEN_BRIGHTNESS, reverting to default 50 and 100"
  #undef SCREEN_BRIGHTNESS
  #undef DIMMING_BRIGHTNESS
  #define SCREEN_BRIGHTNESS 100
#endif
#ifndef DIMMING_BRIGHTNESS
  #define DIMMING_BRIGHTNESS 50
#endif
#if defined(VOLUME_STEPS) && ((VOLUME_STEPS < 1) || (VOLUME_STEPS > 10))
  #warning "define warning in myoptions.h: VOLUME_STEPS is out of range (1-10), reverting to default 1"
  #undef VOLUME_STEPS
#endif
#ifndef VOLUME_STEPS
  #define VOLUME_STEPS 1
#endif
#ifndef TOUCH_FLIP
  #define TOUCH_FLIP false
#endif
#ifndef TOUCH_DEBUG
  #define TOUCH_DEBUG false
#endif
#if defined(ROTARY_ACCEL) && ((ROTARY_ACCEL < 1) || (ROTARY_ACCEL > 700))
  #warning "define warning in myoptions.h: ROTARY_ACCEL is out of range (1-700), reverting to default 200"
  #undef ROTARY_ACCEL
#endif
#ifndef ROTARY_ACCEL
  #define ROTARY_ACCEL 200
#endif
#ifndef ONE_CLICK_SWITCH
  #define ONE_CLICK_SWITCH false
#endif
#if defined(IR_TOLERANCE) && ((IR_TOLERANCE < 10) || (IR_TOLERANCE > 80))
  #warning "define warning in myoptions.h: IR_TOLERANCE is out of range (10-80), reverting to default 35"
  #undef IR_TOLERANCE
#endif
#ifndef IR_TOLERANCE
  #define IR_TOLERANCE 35
#endif
#ifndef TIMEZONE_NAME
  #define TIMEZONE_NAME "Canada/Atlantic"
#endif
#ifndef TIMEZONE_POSIX
  #define TIMEZONE_POSIX "AST4ADT,M3.2.0,M11.1.0"
#endif
#ifndef SNTP_1
  #define SNTP_1 "ca.pool.ntp.org"
#endif
#ifndef SNTP_2
  #define SNTP_2 "pool.ntp.org"
#endif
#ifndef TIME_SYNC_INTERVAL // hours
  #if RTCSUPPORTED
    #define TIME_SYNC_INTERVAL 8
  #else
    #define TIME_SYNC_INTERVAL 1
  #endif
#endif
#if (TIME_SYNC_INTERVAL < 1) || (TIME_SYNC_INTERVAL > 24)
  #error define error in myoptions.h: TIME_SYNC_INTERVAL must be a number from 1 to 24 (hours)
#endif
#ifndef WEATHER_API
  #define WEATHER_API "OM1"
#endif
static_assert(
  __builtin_strcmp(WEATHER_API, "OM1")  == 0 ||
  __builtin_strcmp(WEATHER_API, "OW25") == 0 ||
  __builtin_strcmp(WEATHER_API, "OW30") == 0,
  "define error in myoptions.h: WEATHER_API must be \"OM1\", \"OW25\", or \"OW30\""
);
#ifndef WEATHER_LAT
  #define WEATHER_LAT "44.64738"
#endif
#ifndef WEATHER_LON
  #define WEATHER_LON "-63.58029"
#endif
#ifndef WEATHER_SYNC_INTERVAL // minutes
  #define WEATHER_SYNC_INTERVAL 15
#endif
#if (WEATHER_SYNC_INTERVAL < 10) || (WEATHER_SYNC_INTERVAL > 60)
  #error define error in myoptions.h: WEATHER_SYNC_INTERVAL must be a number from 10 to 60 (minutes)
#endif
/* Most of the world uses Metric but you can override in myoptions.h */
#ifndef WEATHER_METRIC
  #define WEATHER_METRIC true
#endif
/* The exact units can also be over-ridden in myoptions.h */
/* valid choices for wind speed are "kph" (km/h), "mph", "ms" (m/s), "kn" (knots) */
#if WEATHER_METRIC
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F false
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG false
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "kmh"
  #endif
#else
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F true
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG true
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "mph"
  #endif
#endif
static_assert(
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kmh") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "mph") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kn")  == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "m/s") == 0,
  "define error in myoptions.h: WEATHER_WIND_SPEED_UNITS must be \"kmh\", \"mph\", \"kn\", or \"m/s\""
);
#ifndef MQTT_HOST
  #define MQTT_HOST "192.168.1.2"
#endif
#ifndef MQTT_PORT
  #define MQTT_PORT 1883
#endif
#ifndef MQTT_USER
  #define MQTT_USER "mqttuser"
#endif
#ifndef MQTT_PASS
  #define MQTT_PASS ""
#endif
#ifndef MQTT_TOPIC
  #define MQTT_TOPIC "ehradio/myradio/"
#endif

#endif // options_h
