#ifndef options_h
#define options_h
#pragma once

#define RADIOVERSION "2026.04.09"

/*******************************************************
THIS FILE IS THE DEFINITIVE HANDLER OF COMPILE OPTIONS.
Most macros used in the codebase are here somewhere.
There are notes and options and examples that can be
used in myoptions.h when compiling.

                                   DO NOT EDIT THIS FILE!

myoptions.h and mytheme.h should exist in the root folder.
Examine the examples in builds/trip5 and make your own!
Read other notes in builds/ for more details regarding how
to build your own and contribute your own myoptions.h!

Locales are guarded seperately in locale.h so check
that file if you need non-English language options.
********************************************************/

#if __has_include("../../myoptions.h")
  #include "../../myoptions.h" // write your variable values here
#endif
#if __has_include("../../mytheme.h")
  #include "../../mytheme.h" // Theme file
#endif

#if !(defined(ARDUINO_ESP32_DEV) || defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV))
  #error define error in platformio.ini: only ARDUINO_ESP32_DEV, ARDUINO_ESP32S3_DEV, or ARDUINO_ESP32C3_DEV boards are supported
#endif

/*******************************************************
Use this tool to setup connections:
https://trip5.github.io/ehRadio_myoptions/generator.html
(a basic tool and not definitive for all possible configurations)
********************************************************/

#define DSP_DUMMY       0    // without display
#define DSP_ST7735      1    // 160x128  1.8"  or 128x128  1.44"  or 160x80   0.96"  https://aliexpress.com/item/1005002822797745.html
#define DSP_SSD1306     2    // 128x64   0.96" https://aliexpress.com/item/1005001621806398.html
#define DSP_NOKIA5110   3    // 84x48    1.6"  https://aliexpress.com/item/1005001621837569.html
#define DSP_ST7789      4    // 320x240  2.4"  https://aliexpress.com/item/32960241206.html 
#define DSP_SH1106      5    // 128x64   1.3"  https://aliexpress.com/item/32683094040.html
#define DSP_1602I2C     6    // 16x2           https://aliexpress.com/item/32305776560.html
#define DSP_SSD1306x32  7    // 128x32   0.91" https://aliexpress.com/item/32798439084.html
#define DSP_SSD1327     8    // 128x128  1.5"  https://aliexpress.com/item/1005001414175498.html
#define DSP_ILI9341     9    // 320x240  3.2"  https://aliexpress.com/item/33048191074.html
#define DSP_SSD1305     10   // 128x64   2.4"  SSD1305 and SSD1309 SPI https://aliexpress.com/item/32950307344.html
#define DSP_SH1107      11   // 128x64   1.3"  https://aliexpress.com/item/4000551696674.html
#define DSP_1602        12   // 16x2           https://aliexpress.com/item/32685016568.html
#define DSP_GC9106      13   // 160x80   0.96" (looks like ST7735S, but it"s not him) https://aliexpress.com/item/32947890530.html
#define DSP_2004I2C     14   // 20x4           https://aliexpress.com/item/32783128355.html
#define DSP_2004        15   // 20x4           https://aliexpress.com/item/32783128355.html
#define DSP_SSD1305I2C  16   // 128x64   2.4"  SSD1305 and SSD1309 I2C https://aliexpress.com/item/32950307344.html
#define DSP_ILI9225     17   // 220x176  2.0"  https://aliexpress.com/item/32952021835.html
#define DSP_ST7789_240  18   // 240x240  1.3"  https://aliexpress.com/item/32996979276.html
/* !!! DSP_ST7789_240 requires further development when used in conjunction with the VS1053 module !!! See the link https://www.instructables.com/Adding-CS-Pin-to-13-LCD/ */
#define DSP_ST7796      19   // 480x320  3.5"  https://aliexpress.com/item/1005004632953455.html?sku_id=12000029911293172
#define DSP_GC9A01A     20   // 240x240  1.28" https://aliexpress.com/item/1005004069703494.html?sku_id=12000029869654615
#define DSP_ILI9488     21   // 480x320  3.5"  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356570
#define DSP_ILI9486     22   // (Testing mode) 480x320  3.5"  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356568
#define DSP_SSD1322     23   // 256x64   2.8"  https://aliexpress.com/item/1005003480981568.html
#define DSP_ST7920      24   // 128x64   2.6"  https://aliexpress.com/item/32699482638.html
#define DSP_ST7789_76   25   // 284x76 2.25"   https://aliexpress.ru/item/1005009016973081.html
#define DSP_CUSTOM      101  // your display

#ifndef DSP_MODEL
  #define DSP_MODEL DSP_DUMMY
#endif

#if DSP_MODEL==DSP_DUMMY
  #define DUMMYDISPLAY
#endif

#ifndef DSP_HSPI
  #define DSP_HSPI false // use HSPI for displays (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif

/* Use #define #BIG_BOOT_LOGO with 480x320 displays if you want a bigger boot logo */
#ifdef BIG_BOOT_LOGO
  #if (DSP_MODEL!=DSP_ST7796 && DSP_MODEL!=DSP_ILI9488 && DSP_MODEL!=DSP_ILI9486)
    #undef BIG_BOOT_LOGO
  #endif
#endif

/*          TFT DISPLAY            */
#ifndef TFT_CS
  #define TFT_CS 5
#endif
#ifndef TFT_RST
  #define TFT_RST -1 // Or set to -1 and connect to Esp EN pin
#endif
#ifndef TFT_DC
  #define TFT_DC 4
#endif
#ifndef USE_FBUFFER
  #define USE_FBUFFER true
#endif
#ifndef FULL_SCR_CLOCK
  #define FULL_SCR_CLOCK true
#endif

/*    ST7735 display submodel     */
// INITR_BLACKTAB       // 1.8" https://aliexpress.ru/item/1005002822797745.html
//     See this note If INITR_BLACKTAB have a noisy line on one side of the screen https://github.com/e2002/yoradio#note-if-initr_blacktab-dsp-have-a-noisy-line-on-one-side-of-the-screen-then-in-adafruit_st7735cpp
// INITR_144GREENTAB    // 1.44" https://aliexpress.ru/item/1005002822797745.html
// INITR_MINI160x80     // 0.96" 160x80 ST7735S   https://????
// INITR_GREENTAB
// INITR_REDTAB
#ifndef DTYPE
  #define DTYPE INITR_BLACKTAB
#endif

/* Override SPI, I2C Speeds and Addresses - may not work for all display drivers, especially if custom libraries are included. ie. ILI9488 which is fixed to 40000000UL */
// #define DEF_SPI_FREQ 8000000UL  // defaults usually OK; may range from 8000000UL (8 MHz) to 80000000UL (80 MHz); check your datasheet before changing! set to 0 
// #define I2CFREQ_HZ   400000UL   // OLED driver default is 4000000UL (4 MHz); lower e.g. to 400000UL (400 kHz) if display is glitchy; range: 100000UL (100 kHz) to 4000000UL (4 MHz)
// #define SCREEN_ADDRESS 0x3C     // see datasheet for address or scan it https://create.arduino.cc/projecthub/abdularbi17/how-to-scan-i2c-address-in-arduino-eaadda

/*            NEXTION             */
#ifndef NEXTION_RX
  #define NEXTION_RX 255
#endif
#ifndef NEXTION_TX
  #define NEXTION_TX 255
#endif
#if NEXTION_RX!=255 && NEXTION_TX!=255
  #define USE_NEXTION
#endif

/*     OLED I2C DISPLAY Pins      */
#ifndef I2C_SDA
  #define I2C_SDA 21
#endif
#ifndef I2C_SCL
  #define I2C_SCL 22
#endif
#ifndef I2C_RST
  #define I2C_RST -1 // -1 means not used
#endif

/*          VS1053 Pins           */
#ifndef VS1053_CS
  #define VS1053_CS 255 // 255 means disabled
#endif
#ifndef VS1053_DCS
  #define VS1053_DCS 25
#endif
#ifndef VS1053_DREQ
  #define VS1053_DREQ 26
#endif
#ifndef VS1053_RST
  #define VS1053_RST -1 // set to -1 if connected to Esp EN pin
#endif
#ifndef VS_HSPI
  #define VS_HSPI false // use HSPI for VS1053 (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif

/*            I2S DAC             */
#ifndef I2S_DOUT
  #define I2S_DOUT 27 // DIN connection
#endif
#ifndef I2S_BCLK
  #define I2S_BCLK 26 // BCLK Bit clock
#endif
#ifndef I2S_LRC
  #define I2S_LRC 25 // WSEL Left Right Clock
#endif
#ifndef I2S_DIN
  #define I2S_DIN 255 // optional DIN (not wired by default)
#endif
#ifndef I2S_MCLK
  #define I2S_MCLK 255 // optional MCLK (not wired by default)
#endif
#if (I2S_DOUT!=255) && (VS1053_CS!=255)
  #error define error in myoptions.h: both I2S_DOUT and VS1053_CS are active - set I2S_DOUT 255 or VS1053_CS 255 to disable one
#endif

/*             SDCARD             */
#ifndef SDC_CS
  #define SDC_CS 255 // SDCARD CS pin: 255 = disabled
#endif
#ifndef SD_HSPI
  #define SD_HSPI false // use HSPI for SD (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif
#if SDC_CS!=255
  #define USE_SD
#endif
#ifndef SDSPISPEED
  #if defined(ARDUINO_ESP32_DEV)
    #define SDSPISPEED 20000000 // safe
  #elif defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)
    #define SDSPISPEED 40000000 // S3 known to work at this speed (even with custom pins)
  #else
    #define SDSPISPEED 20000000 // safe
  #endif
#endif
#ifndef SD_CARD_DETECT_PIN
  #define SD_CARD_DETECT_PIN 255 // GPIO pin for mechanical SD card-detect switch (LOW=card present, HIGH=slot empty). 255 = disabled.
#endif
#ifndef SD_AUTOPLAY
  #define SD_AUTOPLAY false // auto-switch to SD card mode when card is inserted (hot-insert detection). Requires SD_CARD_DETECT_PIN != 255
#endif
#ifndef SD_MAX_LEVELS
  #define SD_MAX_LEVELS 3 // search depth for files on the SD card
#endif
#if (SD_MAX_LEVELS < 1) || (SD_MAX_LEVELS > 10)
  #error define error in myoptions.h: SD_MAX_LEVELS must be between 1 and 10
#endif

/*            ENCODER             */
#ifndef ENC_BTNL
  #define ENC_BTNL 255
#endif
#ifndef ENC_BTNB
  #define ENC_BTNB 255
#endif
#ifndef ENC_BTNR
  #define ENC_BTNR 255
#endif
#ifndef ENC_INTERNALPULLUP // Thanks for Buska1968. See this topic: https://4pda.to/forum/index.php?s=&showtopic=1010378&view=findpost&p=113385448
  #define ENC_INTERNALPULLUP true
#endif
#ifndef ENC_HALFQUARD
  #define ENC_HALFQUARD false
#endif

#ifndef ENC2_BTNL
  #define ENC2_BTNL 255
#endif
#ifndef ENC2_BTNB
  #define ENC2_BTNB 255
#endif
#ifndef ENC2_BTNR
  #define ENC2_BTNR 255
#endif
#ifndef ENC2_INTERNALPULLUP
  #define ENC2_INTERNALPULLUP true
#endif
#ifndef ENC2_HALFQUARD
  #define ENC2_HALFQUARD false
#endif

/*            BUTTONS             */
#ifndef BTN_LEFT
  #define BTN_LEFT 255
#endif
#ifndef BTN_CENTER
  #define BTN_CENTER 255
#endif
#ifndef BTN_RIGHT
  #define BTN_RIGHT 255
#endif
#ifndef BTN_UP
  #define BTN_UP 255
#endif
#ifndef BTN_DOWN
  #define BTN_DOWN 255
#endif
#ifndef BTN_MODE
  #define BTN_MODE 255
#endif
#ifndef BTN_INTERNALPULLUP
  #define BTN_INTERNALPULLUP true
#endif
#ifndef BTN_LONGPRESS_LOOP_DELAY
  #define BTN_LONGPRESS_LOOP_DELAY 200 // delay between calling DuringLongPress event
#endif
#ifndef BTN_CLICK_TICKS
  #define BTN_CLICK_TICKS 300
#endif
#ifndef BTN_PRESS_TICKS
  #define BTN_PRESS_TICKS 500
#endif
#if BTN_PRESS_TICKS <= BTN_CLICK_TICKS
  #error define error in myoptions.h: BTN_PRESS_TICKS must be greater than BTN_CLICK_TICKS
#endif

/*          TOUCH SCREEN          */
#define TS_MODEL_UNDEFINED 0
#define TS_MODEL_XPT2046 1
#define TS_MODEL_GT911 2
#define TS_MODEL_FT6336 3

#ifndef TS_MODEL
  #define TS_MODEL TS_MODEL_UNDEFINED
#endif
#if (TS_MODEL < 0) || (TS_MODEL > 3)
  #error define error in myoptions.h: TS_MODEL must be TS_MODEL_UNDEFINED, TS_MODEL_XPT2046, TS_MODEL_GT911, or TS_MODEL_FT6336
#endif

#ifndef TS_CS
  #define TS_CS 13
#endif
#ifndef TS_SDA
  #define TS_SDA 33
#endif
#ifndef TS_SCL
  #define TS_SCL 32
#endif
#ifndef TS_INT
  #define TS_INT 21
#endif
#ifndef TS_RST
  #define TS_RST 25
#endif

#ifndef TS_HSPI
  #define TS_HSPI false // use HSPI for touchscreen (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif

/*          LCD DISPLAY           */
#ifndef LCD_RS
  #define LCD_RS 255
#endif
#ifndef LCD_E
  #define LCD_E 255
#endif
#ifndef LCD_D4
  #define LCD_D4 255
#endif
#ifndef LCD_D5
  #define LCD_D5 255
#endif
#ifndef LCD_D6
  #define LCD_D6 255
#endif
#ifndef LCD_D7
  #define LCD_D7 255
#endif

/*              RTC               */
#define RTC_MODULE_UNDEFINED 0
#define DS3231 1
#define DS1307 2

#ifndef RTC_MODULE
  #define RTC_MODULE RTC_MODULE_UNDEFINED  /*  DS3231 or DS1307  */
#endif
#if (RTC_MODULE < 0) || (RTC_MODULE > 2)
  #error define error in myoptions.h: RTC_MODULE must be DS3231 or DS1307 (or leave undefined)
#endif
#ifndef RTC_SDA
  #define RTC_SDA 255
#endif
#ifndef RTC_SCL
  #define RTC_SCL 255
#endif

/*          ESP DEVBOARD          */
/*           LED stuff            */
#if defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)
    #define ESP_S3C3       1
    #ifndef USE_BUILTIN_LED
      #define USE_BUILTIN_LED true
    #endif
    #ifndef LED_BUILTIN_S3 // Define a pin number for standard RGB LED behavior
      #define LED_BUILTIN_S3 255
    #endif
    #if USE_BUILTIN_LED
      #define REAL_LEDBUILTIN LED_BUILTIN
    #else
      #define REAL_LEDBUILTIN LED_BUILTIN_S3
    #endif
#else
    #ifndef LED_BUILTIN // LED's pin number
      #define LED_BUILTIN 255
    #endif
    #define REAL_LEDBUILTIN LED_BUILTIN
#endif
#ifndef LED_INVERT // can define as true in myoptions.h: inverts behavior of above LED
  #define LED_INVERT false
#endif
#ifdef RGB_LED_PIN // will use Neopixel library to control RGB LED with something like:
 // #define RGB_LED_PIN 42
  #if RGB_LED_PIN==255
    #undef RGB_LED_PIN
  #endif
#endif
#ifdef RGB_LED_ORDER // Most WS2812 LEDs are actually GRB but can be over-ridden
 // #define RGB_LED_ORDER NEO_GRB
#endif

/* PREVENT BOARD-DEFINED PIN RE-USE */
/* Board-assigned LED pins may float high/low and conflict with peripherals that share a reset pin. */
#if REAL_LEDBUILTIN==TFT_RST
  #error define error in myoptions.h: LED_BUILTIN is the same as TFT_RST
#endif
#if REAL_LEDBUILTIN==VS1053_RST
  #error define error in myoptions.h: LED_BUILTIN is the same as VS1053_RST
#endif
#if (REAL_LEDBUILTIN != 255) && (I2C_RST != -1) && (REAL_LEDBUILTIN == I2C_RST)
  #error define error in myoptions.h: LED_BUILTIN is the same as I2C_RST
#endif
#ifdef ESP_S3C3
  #if (LED_BUILTIN_S3 != 255) && (LED_BUILTIN_S3 == TFT_RST)
    #error define error in myoptions.h: LED_BUILTIN_S3 is the same as TFT_RST
  #endif
  #if (LED_BUILTIN_S3 != 255) && (LED_BUILTIN_S3 == VS1053_RST)
    #error define error in myoptions.h: LED_BUILTIN_S3 is the same as VS1053_RST
  #endif
  #if (LED_BUILTIN_S3 != 255) && (I2C_RST != -1) && (LED_BUILTIN_S3 == I2C_RST)
    #error define error in myoptions.h: LED_BUILTIN_S3 is the same as I2C_RST
  #endif
#endif

/*           SPI Stuff            */
#include <SPI.h>
#if !defined(CONFIG_IDF_TARGET_ESP32)
  #define VSPI FSPI
#endif

/*       LIBRARY OVERRIDES        */
/*      DO NOT CHANGE THESE       */
#ifndef CONFIG_ASYNC_TCP_RUNNING_CORE
  #define CONFIG_ASYNC_TCP_RUNNING_CORE 0 // -1 = any available core
#endif
#ifndef CONFIG_ASYNC_TCP_USE_WDT
  #define CONFIG_ASYNC_TCP_USE_WDT 0 // 1 = watchdog enabled (adds between 33us and 200us per event)
#endif

/*        SYSTEM OVERRIDES        */
/*      THESE MAY BE TWEAKED      */
#ifndef WIFI_ATTEMPTS
  #define WIFI_ATTEMPTS 16
#endif
#if WIFI_ATTEMPTS < 1
  #error define error in myoptions.h: WIFI_ATTEMPTS must be at least 1
#endif
#ifndef LOOP_TASK_STACK_SIZE    // sets the stack size for the FreeRTOS task that runs the main loop
  #define LOOP_TASK_STACK_SIZE 8 // Compiler default is 8KB but seems safe on ESP32-S3 to increase to 16KB for audio decoding + concurrent tasks
#endif
#if (LOOP_TASK_STACK_SIZE < 4) || (LOOP_TASK_STACK_SIZE > 64)
  #error define error in myoptions.h: LOOP_TASK_STACK_SIZE must be between 4 and 64 (value in KB)
#endif
#ifndef CONFIG_ASYNC_TCP_QUEUE_SIZE
  #define CONFIG_ASYNC_TCP_QUEUE_SIZE 64 // maybe 32 for ESP32?
#endif
#ifndef SEARCHRESULTS_BUFFER
  #define SEARCHRESULTS_BUFFER 1024*4 // 32KB matches chunk sizes from radio-browser.info but likely only good for ESP32-S3
#endif
#ifndef SEARCHRESULTS_YIELDINTERVAL
  #define SEARCHRESULTS_YIELDINTERVAL 0 // With a large buffer, skipping is almost eliminated with 0
#endif
#ifdef MAX_PL_READ_BYTES
 //#define MAX_PL_READ_BYTES 65536 // Makes chunked HTML transfers... possibly enable if experiencing slowdowns when sending web UI to client. Untested.
#endif
/* Below defines maximum lengths of character buffers */
/* Notes have been made regarding old yoRadio values */
#ifndef WEATHER_STRING_L
  #define WEATHER_STRING_L 512 // size of weather string, formerly 254
#endif
#ifndef WEBSOCKET_BUFFER
  #define WEBSOCKET_BUFFER 384 // formerly BUFLEN * 2 = 340
#endif

#ifndef CONNECT_HTTP_HTTPS_TIMEOUT
 // Connection timeout in milliseconds: HTTP, HTTPS(SSL)
 // Library defaults: 250ms HTTP, 2700ms SSL
 // Conservative values for slower networks: 1700ms HTTP, 3700ms SSL
 // #define CONNECT_HTTP_HTTPS_TIMEOUT 1700, 3700 /* For ESP32? */
 // undefined means using library defaults (preferred)
#endif

/*        Other settings. You can overwrite them in the myoptions.h file        */
#ifndef MUTE_PIN
  #define MUTE_PIN 255 // MUTE Pin
#endif
#ifndef MUTE_VAL
  #define MUTE_VAL HIGH // Write this to MUTE_PIN when player is stopped
#endif
#ifndef MUTE_LOCK
  #define MUTE_LOCK false // for vs1053 Shield rev2 - lock MUTE_PIN to !MUTE_VAL
#endif
#ifndef BRIGHTNESS_PIN
  #define BRIGHTNESS_PIN 255 // BRIGHTNESS Pin
#endif
#ifndef PLAYER_FORCE_MONO
  #define PLAYER_FORCE_MONO false // mono option - false stereo, true mono
#endif
#ifndef I2S_INTERNAL
  #define I2S_INTERNAL false // If true - use esp32 internal DAC
#endif
#ifndef ROTATE_90
  #define ROTATE_90 false // Optional 90 degree rotation for square displays
#endif
#ifndef WAKE_PIN
  #define WAKE_PIN 255 // Wake Pin (manual wakeup from deep sleep. can match with BTN_XXXX, ENC_BTNB, ENC2_BTNB)
                      // ESP32:   RTC-capable GPIOs only: 0,2,4,12-15,25-27,32-39
                      // ESP32-S3: RTC-capable GPIOs only: 0-21
                      // ESP32-C3: RTC-capable GPIOs only: 0-5
#endif
// WAKE_PIN polarity default: LOW = active-low button (pin held HIGH by pull-up; wakes when button pulls to GND)
// #define WAKE_PIN_STATE HIGH for active-high circuits (pin held LOW by pull-down; wakes when button pulls to VCC)
#ifndef WAKE_PIN_STATE
  #define WAKE_PIN_STATE LOW
#endif

#ifndef LIGHT_SENSOR
  #define LIGHT_SENSOR 255 // Light sensor
#endif
#ifndef AUTOBACKLIGHT
  #ifndef AUTOBACKLIGHT_MAX
    #define AUTOBACKLIGHT_MAX 2500
  #endif
  #ifndef AUTOBACKLIGHT_MIN
    #define AUTOBACKLIGHT_MIN 12
  #endif
  #define AUTOBACKLIGHT(x) ({uint16_t _lh=(x>AUTOBACKLIGHT_MAX?AUTOBACKLIGHT_MAX:x); map(_lh, AUTOBACKLIGHT_MAX, 0, AUTOBACKLIGHT_MIN, 100);}) // autobacklight function
#endif
#ifndef DSP_INVERT_TITLE
  #define DSP_INVERT_TITLE true // Invert title colors for displays ?
#endif
#ifndef RSSI_DIGIT
  #define RSSI_DIGIT false // display RSSI as number
#endif
#ifndef RSSI_STEPS
  #define RSSI_STEPS -50,-60,-70,-80
#endif
#ifndef CLOCKFONT_MONO
  #define CLOCKFONT_MONO true // monospace clock font
#endif
#ifndef MAX_AUDIO_SOCKET_TIMEOUT
  #define MAX_AUDIO_SOCKET_TIMEOUT false // max audio socket timeout?
#endif
#ifndef BITRATE_FULL
  #define BITRATE_FULL true // display bitrate badge
#endif

/*               IR               */
#ifndef IR_PIN
  #define IR_PIN 255
#endif
#ifndef IR_TIMEOUT
  #define IR_TIMEOUT 80 // kTimeout, see IRremoteESP8266 documentation
#endif

/* ehRadio Color Theme: over-ridden by mytheme.h */
/*        color name                R,   G,   B  */
#ifndef COLOR_BACKGROUND // background
  #define COLOR_BACKGROUND          0,   0,   0
#endif
#ifndef COLOR_STATION_NAME // station text color
  #define COLOR_STATION_NAME        0,   0,   0
#endif
#ifndef COLOR_STATION_BG // current station background
  #define COLOR_STATION_BG          0, 100, 255
#endif
#ifndef COLOR_STATION_FILL // fill color (outside bg)
  #define COLOR_STATION_FILL        0,  98, 250
#endif
#ifndef COLOR_SNG_TITLE_1 // first title
  #define COLOR_SNG_TITLE_1       255, 255, 255
#endif
#ifndef COLOR_SNG_TITLE_2 // second title
  #define COLOR_SNG_TITLE_2       220, 220, 220
#endif
#ifndef COLOR_WEATHER // weather string
  #define COLOR_WEATHER             0, 255,   0
#endif
#ifndef COLOR_VU_MAX // max of VU meter "FireBrick"
  #define COLOR_VU_MAX            178,  34,  34
#endif
#ifndef COLOR_VU_MIN // min of VU meter "Green"
  #define COLOR_VU_MIN              0, 128,   0
#endif
#ifndef COLOR_CLOCK // clock color
  #define COLOR_CLOCK             255,  32,  16
#endif
#ifndef COLOR_CLOCK_BG // clock color background
  #define COLOR_CLOCK_BG           30,   2,   2
#endif
#ifndef COLOR_SECONDS // seconds color (DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_SECONDS           255,  16,   4
#endif
#ifndef COLOR_DAY_OF_W // day of week color (for DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_DAY_OF_W          240, 240, 240
#endif
#ifndef COLOR_DATE // date color (DSP_ST7789, DSP_ILI9341, DSP_ILI9225)
  #define COLOR_DATE              255, 255, 255
#endif
#ifndef COLOR_HEAP // heap string
  #define COLOR_HEAP              231, 115,   0
#endif
#ifndef COLOR_BUFFER // buffer line
  #define COLOR_BUFFER            220, 220,  90
#endif
#ifndef COLOR_IP // IP address
  #define COLOR_IP                200, 20,  240
#endif
#ifndef COLOR_VOLUME_VALUE // volume number
  #define COLOR_VOLUME_VALUE      15,  180,  15
#endif
#ifndef COLOR_RSSI // rssi
  #define COLOR_RSSI              200,  20, 240
#endif
#ifndef COLOR_VOLBAR_OUT // border of volume bar
  #define COLOR_VOLBAR_OUT        30,  200,  30
#endif
#ifndef COLOR_VOLBAR_IN // inside volume bar
  #define COLOR_VOLBAR_IN         5,   140,   5
#endif
#ifndef COLOR_DIGITS // numbers...?
  #define COLOR_DIGITS            255, 255, 255
#endif
#ifndef COLOR_DIVIDER // lines around clock
  #define COLOR_DIVIDER           132, 132, 165
#endif
#ifndef COLOR_PL_CURRENT // playlist current item
  #define COLOR_PL_CURRENT          0, 170, 250
#endif
#ifndef COLOR_PL_CURRENT_BG // playlist current item background
  #define COLOR_PL_CURRENT_BG      30,  30,  30
#endif
#ifndef COLOR_PL_CURRENT_FILL // playlist current item fill background
  #define COLOR_PL_CURRENT_FILL    60,  60,  60
#endif
#ifndef COLOR_PLAYLIST_0 // playlist string 0
  #define COLOR_PLAYLIST_0        250, 250, 250
#endif
#ifndef COLOR_PLAYLIST_1 // playlist string 1
  #define COLOR_PLAYLIST_1        230, 230, 230
#endif
#ifndef COLOR_PLAYLIST_2 // playlist string 2
  #define COLOR_PLAYLIST_2        210, 210, 210
#endif
#ifndef COLOR_PLAYLIST_3 // playlist string 3
  #define COLOR_PLAYLIST_3        190, 190, 190
#endif
#ifndef COLOR_PLAYLIST_4 // playlist string 4
  #define COLOR_PLAYLIST_4        170, 170, 170
#endif
#ifndef COLOR_BITRATE // stream bitrate
  #define COLOR_BITRATE           220, 220,  90
#endif

/*        SYSTEM DEFAULTS         */
#ifndef SCREENSAVERSTARTUPDELAY
  #define SCREENSAVERSTARTUPDELAY 5
#endif
#ifndef HEADER_TIMEOUT
  #define HEADER_TIMEOUT 5000
#endif
#ifndef USE_OTA
  #define USE_OTA false // define true to enable Arduino OTA
#endif
#ifdef OTA_PASS
 // #define OTA_PASS "myotapassword12345" // you can also define an OTA password like this
#endif

#ifndef AP_SSID
  #define AP_SSID "ehRadio"
#endif
#ifdef AP_PASSWORD
  #if (AP_PASSWORD)[0] == '\0' // if it's empty, undefine
    #undef AP_PASSWORD
  #endif
#endif
#ifndef BUFLEN
  #define BUFLEN 170 // 170 seems safe... a lot of multipliers exist in the code...
#endif
#if BUFLEN < 64
  #error define error in myoptions.h: BUFLEN is too small (minimum 64, default 170)
#endif

/* This bit will actually do something but needs to be handled a different way - configurable would be better */
/* But I'm very concerned that a forgotten password means needing a way to factory-reset using hardware... */
/* So this may never actually be implemented in a proper way */
//#define HTTP_USER "user"
//#define HTTP_PASS "password"

/*           BATTERY              */
#ifndef BATTERY_PIN
  #define BATTERY_PIN 255 // GPIO pin for battery voltage ADC reading
#endif
#ifndef BATTERY_CHARGE_PIN
  #define BATTERY_CHARGE_PIN 255 // GPIO pin for charging status (TP4054 CHRG pin, active LOW)
#endif

#ifndef BATTERY_DIVIDER_RATIO
  #define BATTERY_DIVIDER_RATIO 2.0 // Voltage divider ratio (battery voltage / ADC voltage)
#endif
#ifndef BATTERY_ADC_REF_MV
  #define BATTERY_ADC_REF_MV 3300 // ADC reference voltage in millivolts
#endif
#ifndef BATTERY_UPDATE_INTERVAL
  #define BATTERY_UPDATE_INTERVAL 60000 // Update interval in milliseconds
#endif
#ifndef BATTERY_SAMPLES
  #define BATTERY_SAMPLES 10 // Number of ADC samples to average
#endif
#ifndef BATTERY_DIM_BRIGHTNESS
  #define BATTERY_DIM_BRIGHTNESS 20 // Battery dim fixed brightness when LOW battery (percentage 0-100)
#endif
#if (BATTERY_DIM_BRIGHTNESS < 0) || (BATTERY_DIM_BRIGHTNESS > 100)
  #error define error in myoptions.h: BATTERY_DIM_BRIGHTNESS must be a percentage between 0 and 100
#endif
#ifndef BATTERY_RECOVER_HYSTERESIS_PCT
  #define BATTERY_RECOVER_HYSTERESIS_PCT 5 // Hysteresis for recovering from low-battery dimming (percent)
#endif
/* Inference tuning defaults: control sensitivity for charging/discharging detection. */
#ifndef BATTERY_CHARGE_INFER_HOLD_SAMPLES
  #define BATTERY_CHARGE_INFER_HOLD_SAMPLES 3 // number of measurements (samples) to hold (e.g., 3 readings)
#endif
#ifndef BATTERY_IMMEDIATE_PERCENT_THRESHOLD
  #define BATTERY_IMMEDIATE_PERCENT_THRESHOLD 3 // percent; immediate single-reading threshold
#endif
#ifndef BATTERY_CANDIDATE_PERCENT_DELTA
  #define BATTERY_CANDIDATE_PERCENT_DELTA 1 // percent; minimal delta to start a candidate
#endif
#ifndef BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD
  #define BATTERY_SUSTAINED_PERCENT_WINDOW_THRESHOLD 0 // percent over hold window required to confirm
#endif
/* Battery presence detection (mV) - default single-cell LiPo safe range. */
#ifndef BATTERY_PRESENT_MIN_MV
  #define BATTERY_PRESENT_MIN_MV 3000 // Minimum battery voltage (mV) considered present (single-cell LiPo)
#endif
#ifndef BATTERY_PRESENT_MAX_MV
  #define BATTERY_PRESENT_MAX_MV 4300 // Maximum battery voltage (mV) considered present (single-cell LiPo)
#endif
/* Battery discharge curve defaults (mV -> percent). */
#ifndef BATTERY_CURVE_MV
  #define BATTERY_CURVE_MV 4240, 4100, 4000, 3900, 3800, 3700, 3600, 3400, 3200
#endif
#ifndef BATTERY_CURVE_PCT
  #define BATTERY_CURVE_PCT 100, 95, 90, 80, 70, 55, 30, 10, 0
#endif
#ifndef BATTERY_LOW_THRESHOLD
  #define BATTERY_LOW_THRESHOLD 25 // Low battery warning threshold (percentage, 0-100)
#endif
#if (BATTERY_LOW_THRESHOLD < 0) || (BATTERY_LOW_THRESHOLD > 100)
  #error define error in myoptions.h: BATTERY_LOW_THRESHOLD must be a percentage between 0 and 100
#endif
#ifndef BATTERY_CRITICAL_THRESHOLD
  #define BATTERY_CRITICAL_THRESHOLD 5 // Critical battery threshold (percentage, 0-100)
#endif
#if (BATTERY_CRITICAL_THRESHOLD < 0) || (BATTERY_CRITICAL_THRESHOLD > 100)
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be a percentage between 0 and 100
#endif
#if BATTERY_CRITICAL_THRESHOLD >= BATTERY_LOW_THRESHOLD
  #error define error in myoptions.h: BATTERY_CRITICAL_THRESHOLD must be less than BATTERY_LOW_THRESHOLD
#endif
#ifdef BATTERY_DEBUG
 // if defined enables full information about battery in serial log
#endif

/*     SOURCE OF UPDATE FILES     */
/* only used if FIRMWARE is defined as it is in Trip5's automatic Github builds */
#ifndef GITHUBURL
  #define GITHUBURL "https://github.com/trip5/ehradio" // used by the ESPFileUpdater in BrowserClient (and in URLs below)
#endif
#ifdef FIRMWARE // this is the filename.bin online
  #ifndef FIRMWARE_NAME
  // #define FIRMWARE_NAME "Trip5's Big Screen Radio" optional name of the firmware (appears only in eh Device Protocol and will appear as the filename (without .bin) by default if not defined)
  #endif
  #ifndef FILESURL
    #define FILESURL GITHUBURL "/releases/download/" RADIOVERSION "/" // + FILE for SPIFFS files (this version)
  #endif
  #ifndef UPDATEURL
    #define UPDATEURL GITHUBURL "/releases/latest/download/" // + FIRMWARE for the file
  #endif
  #ifndef CHECKUPDATEURL
    #define CHECKUPDATEURL GITHUBURL "/releases/latest/download/version.txt" // automatically extracted from options.h during Github workflow
  #endif
  #ifndef VERSIONSTRING
    #define VERSIONSTRING "#define RADIOVERSION" // the file above should have a line that contains this followed by a version number
  #endif
  #ifndef CHECKUPDATEURL_TIME
    #define CHECKUPDATEURL_TIME "1 day"
  #endif
#else
  #undef FILESURL
  #undef UPDATEURL
  #undef CHECKUPDATEURL
  #undef VERSIONSTRING
  #undef CHECKUPDATEURL_TIME
#endif
#ifdef DISABLE_UPDATER // if this is defined, disables online updates
  #undef FILESURL
  #undef UPDATEURL
  #undef CHECKUPDATEURL
  #undef VERSIONSTRING
  #undef CHECKUPDATEURL_TIME
#endif

/*      SOURCE OF JSON FILES      */
#ifndef TIMEZONES_JSON_URL
  #define TIMEZONES_JSON_URL "https://raw.githubusercontent.com/trip5/timezones.json/master/timezones.json.gz"
#endif
#ifndef TIMEZONES_JSON_CHECKTIME
  #define TIMEZONES_JSON_CHECKTIME "4 weeks"
#endif
#ifndef RADIO_BROWSER_SERVERS_URL 
  #define RADIO_BROWSER_SERVERS_URL "https://all.api.radio-browser.info/json/servers"
#endif
#ifndef RB_SERVERS_CHECKTIME
  #define RB_SERVERS_CHECKTIME "1 day"
#endif

/*  SOURCE OF CURATED PLAYLISTS   */
#ifndef CURATED_LISTS
  #define CURATED_LISTS "Trip5's webstations"
  #ifndef CURATED_LISTS_LINK
    #define CURATED_LISTS_LINK "https://github.com/trip5/webstations"
  #endif
  #ifndef CURATED_LISTS_URL
    #define CURATED_LISTS_URL "https://github.com/trip5/webstations/releases/latest/download/"
  #endif
  #ifndef CURATED_LISTS_INDEX
    #define CURATED_LISTS_INDEX "index.json"
  #endif
#else
  #if !defined(CURATED_LISTS_LINK) || !defined(CURATED_LISTS_URL) || !defined(CURATED_LISTS_INDEX)
    #undef CURATED_LISTS
    #undef CURATED_LISTS_LINK
    #undef CURATED_LISTS_URL
    #undef CURATED_LISTS_INDEX
  #endif
#endif

/*    RADIO BROWSER API SERVER    */
/* Used as fallback for search and primary for sending clicks */
#ifndef RADIO_BROWSER_SERVER
  #define RADIO_BROWSER_SERVER "all.api.radio-browser.info"
#endif

/* OPT-OUT SENDING CLICKS TO RADIO-BROWSER API */
#ifndef RADIO_BROWSER_NO_SEND_CLICKS
  #ifndef RADIO_BROWSER_SEND_CLICKS
    #define RADIO_BROWSER_SEND_CLICKS
  #endif
  #ifndef RADIO_BROWSER_SEND_CLICK_DELAY
    #define RADIO_BROWSER_SEND_CLICK_DELAY 10000 // wait 10 seconds before sending the click
  #endif
#else
  #undef RADIO_BROWSER_SEND_CLICKS
#endif

/*     OTHER COMPILE OPTIONS      */
/*  Here are other #defines that  */
/*  may be added to myoptions.h   */
#ifdef MQTT_ENABLE
 // This enables MQTT. A nice option to have but not available in the code without this #define in myoptions.h
#endif
#ifdef PLAYLIST_DEFAULT_URL
 // This will download a playlist when first-booting and no playlist is present on SPIFFS.  Can be CSV or JSON format.  Example:
 // #define PLAYLIST_DEFAULT_URL "https://github.com/trip5/webstations/releases/latest/download/trip5-radio-playlist.csv"
#endif
/* Debug Options not mentioned elsewhere */
#ifdef ESPFILEUPDATER_DEBUG
 // This enables ESPFileUpdater's debug log in serial.  Only add if you really want to watch serial log for what may be causing fetch errors.
#endif
#ifdef DEBUG_V
 // This enables Netserver logging: GET client requests and sending files in chunks
#endif
#ifdef CORS_DEBUG
 // This enables CORS policy: 'Access-Control-Allow-Origin' (for testing)
#endif

/*         USER DEFAULTS          */
/*   sets defaults in config.h    */
/*    still editable in WebUI     */
#if defined(SOUND_VOLUME) && ((SOUND_VOLUME < 0) || (SOUND_VOLUME > 254))
  #warning "define warning in myoptions.h: SOUND_VOLUME is out of range (0-254), reverting to default 12"
  #undef SOUND_VOLUME
#endif
#ifndef SOUND_VOLUME
  #define SOUND_VOLUME 12
#endif
#if defined(SOUND_BALANCE) && ((SOUND_BALANCE < -16) || (SOUND_BALANCE > 16))
  #warning "define warning in myoptions.h: SOUND_BALANCE is out of range (-16 to 16), reverting to default 0"
  #undef SOUND_BALANCE
#endif
#ifndef SOUND_BALANCE
  #define SOUND_BALANCE 0
#endif
#if defined(EQ_TREBLE) && ((EQ_TREBLE < -16) || (EQ_TREBLE > 16))
  #warning "define warning in myoptions.h: EQ_TREBLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_TREBLE
#endif
#ifndef EQ_TREBLE
  #define EQ_TREBLE 0
#endif
#if defined(EQ_MIDDLE) && ((EQ_MIDDLE < -16) || (EQ_MIDDLE > 16))
  #warning "define warning in myoptions.h: EQ_MIDDLE is out of range (-16 to 16), reverting to default 0"
  #undef EQ_MIDDLE
#endif
#ifndef EQ_MIDDLE
  #define EQ_MIDDLE 0
#endif
#if defined(EQ_BASS) && ((EQ_BASS < -16) || (EQ_BASS > 16))
  #warning "define warning in myoptions.h: EQ_BASS is out of range (-16 to 16), reverting to default 0"
  #undef EQ_BASS
#endif
#ifndef EQ_BASS
  #define EQ_BASS 0
#endif
#ifndef SD_SHUFFLE
  #define SD_SHUFFLE false
#endif
#ifndef SMART_START
  #define SMART_START false
#endif
#ifndef SHOW_AUDIO_INFO
  #define SHOW_AUDIO_INFO false
#endif
#ifndef SHOW_VU_METER
  #define SHOW_VU_METER false
#endif
#ifndef WIFI_SCAN_BEST_RSSI
  #define WIFI_SCAN_BEST_RSSI false
#endif
#ifndef EHDP
  #define EHDP true
#endif
#if defined(SOFTAP_REBOOT_DELAY) && ((SOFTAP_REBOOT_DELAY < 0) || (SOFTAP_REBOOT_DELAY > 20))
  #warning "define warning in myoptions.h: SOFTAP_REBOOT_DELAY is out of range (0-20), reverting to default 0"
  #undef SOFTAP_REBOOT_DELAY
#endif
#ifndef SOFTAP_REBOOT_DELAY
  #define SOFTAP_REBOOT_DELAY 0
#endif
#ifndef SCREEN_FLIP
  #define SCREEN_FLIP false
#endif
#ifndef SCREEN_INVERT
  #define SCREEN_INVERT false
#endif
#ifndef NUMBERED_PLAYLIST
  #define NUMBERED_PLAYLIST false
#endif
#ifndef CLOCK_TWELVE
  #define CLOCK_TWELVE false
#endif
#ifndef VOLUME_PAGE
  #define VOLUME_PAGE false
#endif
#if defined(SCREEN_BRIGHTNESS) && ((SCREEN_BRIGHTNESS < 1) || (SCREEN_BRIGHTNESS > 100))
  #warning "define warning in myoptions.h: SCREEN_BRIGHTNESS is out of range (1-100), reverting to default 100"
  #undef SCREEN_BRIGHTNESS
#endif
#ifndef SCREEN_BRIGHTNESS
  #define SCREEN_BRIGHTNESS 100
#endif
#if defined(SCREEN_CONTRAST) && ((SCREEN_CONTRAST < 1) || (SCREEN_CONTRAST > 100))
  #warning "define warning in myoptions.h: SCREEN_CONTRAST is out of range (1-100), reverting to default 55"
  #undef SCREEN_CONTRAST
#endif
#ifndef SCREEN_CONTRAST
  #define SCREEN_CONTRAST 55
#endif
#ifndef SS_NOTPLAYING
  #define SS_NOTPLAYING false
#endif
#ifndef SS_NOTPLAYING_BLANK
  #define SS_NOTPLAYING_BLANK false
#endif
#if defined(SS_NOTPLAYING_TIME) && ((SS_NOTPLAYING_TIME < 1) || (SS_NOTPLAYING_TIME > 65520))
  #warning "define warning in myoptions.h: SS_NOTPLAYING_TIME is out of range (1-65520), reverting to default 1"
  #undef SS_NOTPLAYING_TIME
#endif
#ifndef SS_NOTPLAYING_TIME
  #define SS_NOTPLAYING_TIME 1
#endif
#ifndef SS_PLAYING
  #define SS_PLAYING false
#endif
#ifndef SS_PLAYING_BLANK
  #define SS_PLAYING_BLANK false
#endif
#if defined(SS_PLAYING_TIME) && ((SS_PLAYING_TIME < 1) || (SS_PLAYING_TIME > 1080))
  #warning "define warning in myoptions.h: SS_PLAYING_TIME is out of range (1-1080), reverting to default 5"
  #undef SS_PLAYING_TIME
#endif
#ifndef SS_PLAYING_TIME
  #define SS_PLAYING_TIME 5
#endif
#if defined(VOLUME_STEPS) && ((VOLUME_STEPS < 1) || (VOLUME_STEPS > 10))
  #warning "define warning in myoptions.h: VOLUME_STEPS is out of range (1-10), reverting to default 1"
  #undef VOLUME_STEPS
#endif
#ifndef VOLUME_STEPS
  #define VOLUME_STEPS 1
#endif
#ifndef TOUCH_FLIP
  #define TOUCH_FLIP false
#endif
#ifndef TOUCH_DEBUG
  #define TOUCH_DEBUG false
#endif
#if defined(ROTARY_ACCEL) && ((ROTARY_ACCEL < 1) || (ROTARY_ACCEL > 700))
  #warning "define warning in myoptions.h: ROTARY_ACCEL is out of range (1-700), reverting to default 200"
  #undef ROTARY_ACCEL
#endif
#ifndef ROTARY_ACCEL
  #define ROTARY_ACCEL 200
#endif
#ifndef ONE_CLICK_SWITCH
  #define ONE_CLICK_SWITCH false
#endif
#if defined(IR_TOLERANCE) && ((IR_TOLERANCE < 10) || (IR_TOLERANCE > 80))
  #warning "define warning in myoptions.h: IR_TOLERANCE is out of range (10-80), reverting to default 35"
  #undef IR_TOLERANCE
#endif
#ifndef IR_TOLERANCE
  #define IR_TOLERANCE 35
#endif
#ifndef TIMEZONE_NAME
  #define TIMEZONE_NAME "Canada/Atlantic"
#endif
#ifndef TIMEZONE_POSIX
  #define TIMEZONE_POSIX "AST4ADT,M3.2.0,M11.1.0"
#endif
#ifndef SNTP_1
  #define SNTP_1 "ca.pool.ntp.org"
#endif
#ifndef SNTP_2
  #define SNTP_2 "pool.ntp.org"
#endif
#ifndef TIME_SYNC_INTERVAL // hours
  #if RTCSUPPORTED
    #define TIME_SYNC_INTERVAL 8
  #else
    #define TIME_SYNC_INTERVAL 1
  #endif
#endif
#if (TIME_SYNC_INTERVAL < 1) || (TIME_SYNC_INTERVAL > 24)
  #error define error in myoptions.h: TIME_SYNC_INTERVAL must be a number from 1 to 24 (hours)
#endif
#ifndef WEATHER_API
  #define WEATHER_API "OM1"
#endif
static_assert(
  __builtin_strcmp(WEATHER_API, "OM1")  == 0 ||
  __builtin_strcmp(WEATHER_API, "OW25") == 0 ||
  __builtin_strcmp(WEATHER_API, "OW30") == 0,
  "define error in myoptions.h: WEATHER_API must be \"OM1\", \"OW25\", or \"OW30\""
);
#ifndef WEATHER_LAT
  #define WEATHER_LAT "44.64738"
#endif
#ifndef WEATHER_LON
  #define WEATHER_LON "-63.58029"
#endif
#ifndef WEATHER_SYNC_INTERVAL // minutes
  #define WEATHER_SYNC_INTERVAL 15
#endif
#if (WEATHER_SYNC_INTERVAL < 10) || (WEATHER_SYNC_INTERVAL > 60)
  #error define error in myoptions.h: WEATHER_SYNC_INTERVAL must be a number from 10 to 60 (minutes)
#endif
/* Most of the world uses Metric but you can over-ride in myoptions.h */
#ifndef WEATHER_METRIC
  #define WEATHER_METRIC true
#endif
/* The exact units can also be over-ridden in myoptions.h */
/* valid choices for wind speed are "kph" (km/h), "mph", "ms" (m/s), "kn" (knots) */
#if WEATHER_METRIC
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F false
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG false
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "kmh"
  #endif
#else
  #ifndef WEATHER_TEMPERATURE_F
    #define WEATHER_TEMPERATURE_F true
  #endif
  #ifndef WEATHER_PRESSURE_MMHG
    #define WEATHER_PRESSURE_MMHG true
  #endif
  #ifndef WEATHER_WIND_SPEED_UNITS
    #define WEATHER_WIND_SPEED_UNITS "mph"
  #endif
#endif
static_assert(
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kmh") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "mph") == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "kn")  == 0 ||
  __builtin_strcmp(WEATHER_WIND_SPEED_UNITS, "m/s") == 0,
  "define error in myoptions.h: WEATHER_WIND_SPEED_UNITS must be \"kmh\", \"mph\", \"kn\", or \"m/s\""
);
#ifndef MQTT_HOST
  #define MQTT_HOST "192.168.1.2"
#endif
#ifndef MQTT_PORT
  #define MQTT_PORT 1883
#endif
#ifndef MQTT_USER
  #define MQTT_USER "mqttuser"
#endif
#ifndef MQTT_PASS
  #define MQTT_PASS ""
#endif
#ifndef MQTT_TOPIC
  #define MQTT_TOPIC "ehradio/myradio/"
#endif

#endif // options_h
