[platformio]
src_dir = ./src
data_dir = ./data

; -----------------------------------------------------------------------
; Kasperaitis's Radio
; https://trip5.github.com/myoptions/generator.html#eyJib2FyZCI6MiwiYm9hcmRfbmFtZSI6IkVTM0MyOFAgKEVTUDMyLVMzLU4xNlI4KSIsImlfRklSTVdBUkVfTkFNRSI6Ik15IGVoUmFkaW8iLCJpX1NQSUFfU0NLIjoiMTIiLCJpX1NQSUFfTUlTTyI6IjI1NSIsImlfU1BJQV9NT1NJIjoiMTEiLCJpX1NQSUJfU0NLIjoiMzgiLCJpX1NQSUJfTUlTTyI6IjM5IiwiaV9TUElCX01PU0kiOiI0MCIsImlfVEZUX0NTIjoiMTAiLCJpX1RGVF9EQyI6IjQ2IiwiaV9URlRfUlNUIjoiLTEiLCJpX0JSSUdIVE5FU1NfUElOIjoiNDUiLCJpX0RTUF9ESU1NSU5HX0VOQUJMRUQiOiJ0cnVlIiwiaV9EU1BfSU5WRVJUX1FVSVJLIjoidHJ1ZSIsImlfSTJTX01DTEsiOiI0IiwiaV9JMlNfQkNMSyI6IjUiLCJpX0kyU19MUkMiOiI3IiwiaV9JMlNfRE9VVCI6IjgiLCJpX0kyU19ESU4iOiI2IiwiaV9NVVRFX1BJTiI6IjEiLCJpX0VTODMxMV9JMkNfU0RBIjoiMTYiLCJpX0VTODMxMV9JMkNfU0NMIjoiMTUiLCJpX01VVEVfVkFMIjoiSElHSCIsImlfRVM4MzExX01BWF9JMlMiOiIxODAiLCJpX1BMQVlFUl9GT1JDRV9NT05PIjoidHJ1ZSIsImlfVFNfQ1MiOiIiLCJpX1RTX1NQSSI6IkEiLCJpX1RTX1NEQSI6IjE2IiwiaV9UU19TQ0wiOiIxNSIsImlfVFNfSU5UIjoiMTciLCJpX1RTX1JTVCI6IjE4IiwiaV9FTkNfQlROTCI6IiIsImlfRU5DX0JUTkIiOiIiLCJpX0VOQ19CVE5SIjoiIiwiaV9FTkNfUFVMTFVQIjoidHJ1ZSIsImlfRU5DX0JUTkJfUFVMTFVQIjoidHJ1ZSIsImlfRU5DMl9CVE5MIjoiIiwiaV9FTkMyX0JUTkIiOiIiLCJpX0VOQzJfQlROUiI6IiIsImlfRU5DMl9QVUxMVVAiOiJ0cnVlIiwiaV9FTkMyX0JUTkJfUFVMTFVQIjoidHJ1ZSIsImlfQlROX1BSRVYiOiIiLCJpX0JUTl9QUkVWX1BVTExVUCI6InRydWUiLCJpX0JUTl9QTEFZIjoiIiwiaV9CVE5fUExBWV9QVUxMVVAiOiJ0cnVlIiwiaV9CVE5fTkVYVCI6IiIsImlfQlROX05FWFRfUFVMTFVQIjoidHJ1ZSIsImlfQlROX1VQIjoiIiwiaV9CVE5fVVBfUFVMTFVQIjoidHJ1ZSIsImlfQlROX0RPV04iOiIwIiwiaV9CVE5fRE9XTl9QVUxMVVAiOiJ0cnVlIiwiaV9CVE5fTU9ERSI6IiIsImlfQlROX01PREVfUFVMTFVQIjoidHJ1ZSIsImlfTEVEX1BJTiI6IiIsImlfTEVEX0lOVkVSVCI6InRydWUiLCJpX1JHQl9MRURfUElOIjoiNDIiLCJpX1JHQl9MRURfT1JERVIiOiJORU9fR1JCIiwiaV9TRF9DUyI6IjQ3IiwiaV9TRF9TUEkiOiJCIiwiaV9TRF9DQVJEX0RFVEVDVF9QSU4iOiIyNTUiLCJpX1NEX0FVVE9QTEFZIjoiZmFsc2UiLCJpX09ORV9DTElDS19TV0lUQ0giOiJ0cnVlIiwiaV9TU19QTEFZSU5HIjoidHJ1ZSIsImlfU0NSRUVOX0ZMSVAiOiJ0cnVlIiwiaV9TSE9XX0FVRElPX0lORk8iOiJ0cnVlIiwiaV9TSE9XX1ZVX01FVEVSIjoidHJ1ZSIsImlfU01BUlRfU1RBUlQiOiJ0cnVlIiwiaV9TTlRQXzEiOiJsdC5udHAucG9vbC5vcmciLCJpX1NOVFBfMiI6Im50cC5wb29sLm9yZyIsImlfVk9MVU1FX1NURVBTIjoiNSIsImlfV0VBVEhFUl9NRVRSSUMiOiJmYWxzZSIsImlfV0VBVEhFUl9MQVQiOiI1NS43MjE5MjQiLCJpX1dFQVRIRVJfTE9OIjoiMjEuMTE3ODY4IiwiaV9XSUZJX1NDQU5fQkVTVF9SU1NJIjoidHJ1ZSIsIm9wdF9URlRfUlNUIjp0cnVlLCJvcHRfQlJJR0hUTkVTU19QSU4iOnRydWUsIm9wdF9EU1BfRElNTUlOR19FTkFCTEVEIjp0cnVlLCJvcHRfRFNQX0lOVkVSVF9RVUlSSyI6dHJ1ZSwib3B0X01VVEVfUElOIjp0cnVlLCJvcHRfRVM4MzExX0kyQ19TREEiOnRydWUsIm9wdF9FUzgzMTFfSTJDX1NDTCI6dHJ1ZSwib3B0X0VOQ19QVUxMVVAiOmZhbHNlLCJvcHRfRU5DX0JUTkJfUFVMTFVQIjpmYWxzZSwib3B0X0VOQzJfUFVMTFVQIjpmYWxzZSwib3B0X0VOQzJfQlROQl9QVUxMVVAiOmZhbHNlLCJvcHRfQlROX1BSRVZfUFVMTFVQIjpmYWxzZSwib3B0X0JUTl9QTEFZX1BVTExVUCI6ZmFsc2UsIm9wdF9CVE5fTkVYVF9QVUxMVVAiOmZhbHNlLCJvcHRfQlROX1VQX1BVTExVUCI6ZmFsc2UsIm9wdF9CVE5fRE9XTl9QVUxMVVAiOmZhbHNlLCJvcHRfQlROX01PREVfUFVMTFVQIjpmYWxzZSwib3B0X0xFRF9JTlZFUlQiOnRydWUsIm9wdF9SR0JfTEVEX09SREVSIjpmYWxzZSwib3B0X1NEX0NBUkRfREVURUNUX1BJTiI6ZmFsc2UsIm9wdF9TRF9BVVRPUExBWSI6ZmFsc2UsIml0ZW1faW5wdXQtc2VjdGlvbi1pdGVtLTAiOmZhbHNlLCJpdGVtX2lucHV0LXNlY3Rpb24taXRlbS0xIjpmYWxzZSwiaXRlbV9pbnB1dC1zZWN0aW9uLWl0ZW0tMiI6dHJ1ZSwiaXRlbV9pbnB1dC1zZWN0aW9uLWl0ZW0tMyI6ZmFsc2UsIml0ZW1faW5wdXQtc2VjdGlvbi1pdGVtLTQiOmZhbHNlLCJpdGVtX2lucHV0LXNlY3Rpb24taXRlbS01IjpmYWxzZSwiaXRlbV9pbnB1dC1zZWN0aW9uLWl0ZW0tNiI6ZmFsc2UsIml0ZW1faW5wdXQtc2VjdGlvbi1pdGVtLTciOmZhbHNlLCJpdGVtX2lucHV0LXNlY3Rpb24taXRlbS04IjpmYWxzZSwiaXRlbV9pbnB1dC1zZWN0aW9uLWl0ZW0tOSI6dHJ1ZSwiaXRlbV9pbnB1dC1zZWN0aW9uLWl0ZW0tMTAiOmZhbHNlLCJpdGVtX3BlcmlwaGVyYWxzLXNlY3Rpb24taXRlbS0wIjpmYWxzZSwiaXRlbV9wZXJpcGhlcmFscy1zZWN0aW9uLWl0ZW0tMSI6dHJ1ZSwiaXRlbV9wZXJpcGhlcmFscy1zZWN0aW9uLWl0ZW0tMiI6dHJ1ZSwiaXRlbV9wZXJpcGhlcmFscy1zZWN0aW9uLWl0ZW0tMyI6ZmFsc2UsImRlZl9PTkVfQ0xJQ0tfU1dJVENIIjp0cnVlLCJkZWZfU1NfUExBWUlORyI6dHJ1ZSwiZGVmX1NDUkVFTl9GTElQIjp0cnVlLCJkZWZfU0hPV19BVURJT19JTkZPIjp0cnVlLCJkZWZfU0hPV19WVV9NRVRFUiI6dHJ1ZSwiZGVmX1NNQVJUX1NUQVJUIjp0cnVlLCJkZWZfU05UUF8xIjp0cnVlLCJkZWZfU05UUF8yIjp0cnVlLCJkZWZfVk9MVU1FX1NURVBTIjp0cnVlLCJkZWZfV0VBVEhFUl9NRVRSSUMiOmZhbHNlLCJkZWZfV0VBVEhFUl9MQVQiOnRydWUsImRlZl9XRUFUSEVSX0xPTiI6dHJ1ZSwiZGVmX1dJRklfU0NBTl9CRVNUX1JTU0kiOnRydWUsImxvY2FsZV9lbmFibGVkIjp0cnVlLCJsb2NhbGVfdmFsIjoibHRfTFQiLCJ0el9lbmFibGVkIjp0cnVlLCJ0el92YWwiOiJFdXJvcGUvVmlsbml1cyIsImRzcF9zZWwiOiI4IiwiZHNwX2RlZmluZSI6IkRTUF9NT0RFTCBEU1BfSUxJOTM0MSIsImRzcF9uYW1lIjoiSUxJOTM0MSAoU1BJIDMyMHgyNDAgVEZUKSIsImF1ZF9zZWwiOiIyIiwiYXVkX2RlZmluZSI6IlVTRV9FUzgzMTEiLCJhdWRfbmFtZSI6IkVTODMxMSAoUENNIEkyUyBNb25vIERlY29kZXIpIn0%3D
; -----------------------------------------------------------------------
; patch_pio_ini_files can automatically patch this file

[ehradio]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
build_flags =
	-DCORE_DEBUG_LEVEL=0 ; Set to 0 for no debug; saves memory / 5 for full debug (> 0 adds 1s delay after cold boot to ensure serial logs fully visible)
lib_deps =
  ; These libraries are not optional (version numbers here should work but you can try newer/older versions)
  bblanchon/ArduinoJson@^7.4.3
  adafruit/Adafruit GFX Library@^1.12.5
  adafruit/Adafruit BusIO@^1.17.4
  ESP32Async/ESPAsyncWebServer@^3.10.1
  ESP32Async/AsyncTCP@^3.4.10
  marvinroger/AsyncMqttClient@^0.9.0
  trip5/ESPFileUpdater@^1.2.0
  trip5/ehDP@^1.0.0
  jnthas/Improv WiFi Library@^0.0.4
build_src_filter =
  -<*> ; exclude all files by default
  +<../myoptions.h>
  +<../mytheme.h>
  +<main.cpp>
  +<core/*>
  +<displays/*>
  +<locale/*>
  ; additional local libraries can be included in each environment as so:
  ;+<libraries/ES8311_Audio/*> ; for ES8311 Audio
  ;+<libraries/LiquidCrystalI2C/*> ; for LC1602 Display
; These scripts package do pre- and post-steps to make sure SPIFFS gets .gz files for www and an edited font for Wi-Fi signal bars
extra_scripts = pre:builds/platformio_pre_localize.py, pre:builds/platformio_pre_gzip_www.py, post:builds/platformio_post_gzip_www.py

; -----------------------------------------------------------------------
; Optional External Libraries (here to simplify version number updating)
; Add them under lib_deps like: ${library.onebutton}
; -----------------------------------------------------------------------
[library]
onebutton          = mathertel/OneButton@^2.6.2
rotaryencoder      = igorantolic/Ai Esp32 Rotary Encoder@^1.7
irremote           = crankyoldgit/IRremoteESP8266@^2.9.0
neopixel           = adafruit/Adafruit NeoPixel@^1.15.4
; Displays (may be incomplete, some are local libraries)
gc9a01a            = adafruit/Adafruit GC9A01A@^1.1.0 ; untested - may need to try 1.0.0
ili9341            = adafruit/Adafruit ILI9341@^1.6.2 ; SPI TFT
n5110              = adafruit/Adafruit PCD8544 Nokia 5110 LCD library@^2.0.3 ; untested
sh110x             = adafruit/Adafruit SH110X@^2.1.14 ; OLED
ssd1305            = adafruit/Adafruit SSD1305^2.2.3 ; untested
ssd1306            = adafruit/Adafruit SSD1306@^2.5.16 ; Tiny OLED
st7735             = adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ; SPI TFT (Red Board, probably others)
st7789             = ${library.st7735} ; alias
; Touchscreens
tamc_gt911         = tamctec/TAMC_GT911@^1.0.2 ; untested but should be fine
xpt2046            = paulstoffregen/XPT2046_Touchscreen ; only 1 version: 0.0.0-alpha+sha.26b691b2c8

; -----------------------------------------------------------------------
; Board: ES3C28P (ESP32-S3-N16R8)
; -----------------------------------------------------------------------
[es3c28p]
extends = ehradio
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  ${ehradio.build_flags}
  -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

; -----------------------------------------------------------------------
; RADIO FIRMWARES
; -----------------------------------------------------------------------
[env:es3c28p]
extends = es3c28p
build_flags =
  ${es3c28p.build_flags}
  -Des3c28p
lib_deps =
  ${ehradio.lib_deps}
  ${library.ili9341}
  ${library.onebutton}
  ${library.neopixel}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/I2S_Audio/*>+<libraries/ES8311_Audio/*>+<libraries/FT6336_Touchscreen/*>
