[platformio]
src_dir = ./src
data_dir = ./data

; -----------------------------------------------------------------------
; Kasperaitis's Radios
; -----------------------------------------------------------------------
; patch_pio_ini_files can automatically patch this file

[ehradio]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
build_flags =
	-DCORE_DEBUG_LEVEL=0 ; Set to 0 for no debug; saves memory / 5 for full debug (> 0 adds 1s delay after cold boot to ensure serial logs fully visible)
  -DARDUINO_USB_MODE=1 ; sets USB mode to Hardware Serial/JTAG (standard for debugging) / 0 is USB-OTG mode
lib_deps =
  ; These libraries are not optional (version numbers here should work but you can try newer/older versions)
  bblanchon/ArduinoJson@^7.4.3
  adafruit/Adafruit GFX Library@^1.12.5
  adafruit/Adafruit BusIO@^1.17.4
  ESP32Async/ESPAsyncWebServer@^3.10.1
  ESP32Async/AsyncTCP@^3.4.10
  marvinroger/AsyncMqttClient@^0.9.0
  trip5/ESPFileUpdater@^1.2.0
  trip5/ehDP@^1.0.0
  jnthas/Improv WiFi Library@^0.0.4
build_src_filter =
  -<*> ; exclude all files by default
  +<../myoptions.h>
  +<../mytheme.h>
  +<main.cpp>
  +<core/*>
  +<displays/*>
  +<locale/*>
  +<libraries/VS1053_Audio/*>
  +<libraries/I2S_Audio/*>
  ; additional local libraries can be included in each environment as so:
  ;+<libraries/ES8311_Audio/*> ; for ES8311 Audio
  ;+<libraries/LiquidCrystalI2C/*> ; for LC1602 Display
; These scripts package do pre- and post-steps to make sure SPIFFS gets .gz files for www and an edited font for Wi-Fi signal bars
extra_scripts = pre:builds/platformio_pre_localize.py, pre:builds/platformio_pre_gzip_www.py, post:builds/platformio_post_gzip_www.py

; -----------------------------------------------------------------------
; Optional External Libraries (here to simplify version number updating)
; Add them under lib_deps as: ${library.onebutton}
; -----------------------------------------------------------------------
[library]
onebutton          = mathertel/OneButton@^2.6.2
rotaryencoder      = igorantolic/Ai Esp32 Rotary Encoder@^1.7
irremote           = crankyoldgit/IRremoteESP8266@^2.9.0
neopixel           = adafruit/Adafruit NeoPixel@^1.15.4
; Displays (may be incomplete, some are local libraries)
gc9a01a            = adafruit/Adafruit GC9A01A@^1.1.0 ; untested - may need to try 1.0.0
ili9341            = adafruit/Adafruit ILI9341@^1.6.2 ; SPI TFT
n5110              = adafruit/Adafruit PCD8544 Nokia 5110 LCD library@^2.0.3 ; untested
sh110x             = adafruit/Adafruit SH110X@^2.1.14 ; OLED
ssd1305            = adafruit/Adafruit SSD1305^2.2.3 ; untested
ssd1306            = adafruit/Adafruit SSD1306@^2.5.16 ; Tiny OLED
st7735             = adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ; SPI TFT (Red Board, probably others)
st7789             = ${library.st7735} ; alias
tamc_gt911         = tamctec/TAMC_GT911@^1.0.2 ; untested but should be fine

; -----------------------------------------------------------------------
; Board: ESP32-S3-DevKitC-1 (16MB flash, OPI PSRAM)
; -----------------------------------------------------------------------
[esp32_s3_n16r8]
extends = ehradio
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  ${ehradio.build_flags}
  -DBOARD_HAS_PSRAM

; -----------------------------------------------------------------------
; RADIO FIRMWARES
; -----------------------------------------------------------------------
[env:es3c28p]
extends = esp32_s3_n16r8
build_flags =
  ${esp32_s3_n16r8.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1 ; initialize internal USB Serial port before code starts running (likely disables serial output on 2-USB port boards)
  -DES3C28P
lib_ignore = Adafruit SH110X ; weird... without this line, it gets included... but no side-effects either way.  So... this is just a note.  Lol.
lib_deps =
  ${ehradio.lib_deps}
  ${library.ili9341}
  ${library.onebutton}
  ${library.neopixel}
build_src_filter =
  ${ehradio.build_src_filter}
  +<libraries/FT6336_Touchscreen/*>
  +<libraries/ES8311_Audio/*>
